"""
tests/e2e/test_ui_stream_resilience.py

Adversarial Stress Test Suite for UI WebSocket Streaming, Client State Resilience,
High-Frequency Broadcasts, Malformed JSON Frames, and Action Serialization Parity.
"""

import json
import time
from datetime import datetime, timezone
import pytest
from starlette.testclient import TestClient

from backend.app.main import app, account, bracket_manager
from backend.app.core.account import Position, PositionSide
from tests.e2e.test_contracts import validate_ui_state_payload


@pytest.fixture
def client():
    """FastAPI in-process test client with zero external ports/lingering daemons."""
    return TestClient(app)


# ============================================================================
# 1. High-Frequency State Message Updates (100 msgs/sec & Burst)
# ============================================================================

def test_high_frequency_broadcast_and_receipt(client):
    """
    Empirically verify high-frequency state updates (100 msgs roundtrip burst) across WebSocket.
    Ensures connection remains open, frames are received, and state payload schema passes.
    """
    # Setup test bracket & position for AAPL
    account.positions["AAPL"] = Position("AAPL", PositionSide.LONG, 100, 150.0, 152.0)
    bracket_manager.create_bracket("brk_hf_test", "AAPL", "LONG", 100, 150.0, 148.0)

    try:
        with client.websocket_connect("/ws/ui") as ws:
            # Initial state broadcast upon connection
            initial_raw = ws.receive_text()
            initial_data = json.loads(initial_raw)
            assert initial_data["type"] == "STATE_UPDATE"
            assert validate_ui_state_payload(initial_data) is True

            # Send a rapid burst of 100 state updates by modulating stop levels
            t0 = time.monotonic()
            for i in range(1, 101):
                new_stop = round(148.0 + (i * 0.01), 2)
                ws.send_text(json.dumps({
                    "action": "TIGHTEN_STOP",
                    "symbol": "AAPL",
                    "new_stop": new_stop,
                }))
                msg_raw = ws.receive_text()
                data = json.loads(msg_raw)
                assert data["type"] == "STATE_UPDATE"
                assert validate_ui_state_payload(data) is True
                assert data["primary_position"]["stop_loss"] == new_stop

            duration = time.monotonic() - t0
            # 100 round-trip broadcasts and receipts should execute cleanly in < 1.0 second
            assert duration < 1.0
            throughput = 100.0 / duration
            assert throughput >= 100.0
    finally:
        bracket_manager.symbol_to_bracket.pop("AAPL", None)
        account.positions.pop("AAPL", None)


# ============================================================================
# 2. Malformed JSON Frame Handling (Graceful Logging, Zero Crash)
# ============================================================================

def test_malformed_json_frames_handled_gracefully(client):
    """
    Verify backend WebSocket handler survives adversarial / malformed payloads:
    - Truncated JSON
    - Non-JSON strings
    - JSON primitives (null, number, boolean)
    - Empty strings
    - Corrupted structures
    Ensures socket is NOT abruptly severed and continues accepting valid messages.
    """
    with client.websocket_connect("/ws/ui") as ws:
        # Discard initial snapshot
        _ = ws.receive_text()

        malformed_inputs = [
            '{"action": "FLATTEN_POSITION", "sym',  # Truncated syntax
            'NOT_A_VALID_JSON_STRING',
            '',                                      # Empty frame
            'null',
            '12345',
            'true',
            '[]',
            '{"unknown_field": 42}',
            '{"action": null}',
            '{"action": "UNKNOWN_ACTION_OPCODE"}',
        ]

        for payload in malformed_inputs:
            # Should not raise WebSocketDisconnect or unhandled backend exception
            ws.send_text(payload)

        # Immediate self-healing / liveness check: send a valid action
        ws.send_text(json.dumps({"action": "FLATTEN_ALL"}))

        # Connection is still alive and responsive: receive reply
        reply = ws.receive_text()
        data = json.loads(reply)
        assert data["type"] == "STATE_UPDATE"
        assert validate_ui_state_payload(data) is True


# ============================================================================
# 3. Action Serialization Parity (Frontend Payload -> Backend Execution)
# ============================================================================

def test_action_serialization_flatten_position(client):
    """
    Verify payload generated by frontend `flattenPosition("NVDA")`:
    `{"action": "FLATTEN_POSITION", "symbol": "NVDA"}`
    matches backend schema and executes correctly.
    """
    # Seed account with a real Position instance
    account.positions["NVDA"] = Position("NVDA", PositionSide.LONG, 100, 125.0, 126.0)

    try:
        with client.websocket_connect("/ws/ui") as ws:
            _ = ws.receive_text()

            # Dispatch frontend serialized payload
            frontend_payload = {"action": "FLATTEN_POSITION", "symbol": "NVDA"}
            ws.send_text(json.dumps(frontend_payload))

            # Backend triggers manual_flatten and broadcasts state
            update_raw = ws.receive_text()
            update = json.loads(update_raw)
            assert update["type"] == "STATE_UPDATE"
            assert "NVDA" not in [p.get("symbol") for p in update.get("all_positions", [])]
    finally:
        account.positions.pop("NVDA", None)


def test_action_serialization_flatten_all(client):
    """
    Verify payload generated by frontend `flattenAll()`:
    `{"action": "FLATTEN_ALL"}`
    matches backend schema and executes correctly.
    """
    account.positions["AAPL"] = Position("AAPL", PositionSide.LONG, 50, 150.0, 151.0)
    account.positions["MSFT"] = Position("MSFT", PositionSide.LONG, 25, 400.0, 402.0)

    try:
        with client.websocket_connect("/ws/ui") as ws:
            _ = ws.receive_text()

            frontend_payload = {"action": "FLATTEN_ALL"}
            ws.send_text(json.dumps(frontend_payload))

            update_raw = ws.receive_text()
            update = json.loads(update_raw)
            assert update["type"] == "STATE_UPDATE"
            assert update["positions_count"] == 0
    finally:
        account.positions.clear()


def test_action_serialization_tighten_stop(client):
    """
    Verify payload generated by frontend `tightenStop("AAPL", 151.50)`:
    `{"action": "TIGHTEN_STOP", "symbol": "AAPL", "new_stop": 151.50}`
    matches backend schema, tightens bracket, and broadcasts updated stop loss.
    """
    # Initialize a bracket for AAPL
    bracket_manager.create_bracket(
        bracket_id="brk_test_aapl",
        symbol="AAPL",
        side="LONG",
        total_qty=100,
        entry_price=150.0,
        stop_price=148.0,
    )
    bracket_manager.activate_bracket_on_fill("brk_test_aapl", 100, 150.0, datetime.now(timezone.utc))

    # Add AAPL position in account
    account.positions["AAPL"] = Position("AAPL", PositionSide.LONG, 100, 150.0, 152.0)

    try:
        with client.websocket_connect("/ws/ui") as ws:
            _ = ws.receive_text()

            frontend_payload = {
                "action": "TIGHTEN_STOP",
                "symbol": "AAPL",
                "new_stop": 151.50,
            }
            ws.send_text(json.dumps(frontend_payload))

            update_raw = ws.receive_text()
            update = json.loads(update_raw)
            assert update["type"] == "STATE_UPDATE"
            assert update["primary_position"]["stop_loss"] == 151.50
    finally:
        # Cleanup test bracket and position
        account.positions.pop("AAPL", None)
        bracket_manager.symbol_to_bracket.pop("AAPL", None)


def test_rest_fallback_endpoints(client):
    """
    Verify REST fallback endpoints for manual intervention (`/api/flatten`):
    - POST /api/flatten with `{"symbol": "TSLA"}`
    - POST /api/flatten with `{}` (flatten all)
    """
    account.positions["TSLA"] = Position("TSLA", PositionSide.LONG, 20, 250.0, 252.0)
    try:
        res1 = client.post("/api/flatten", json={"symbol": "TSLA"})
        assert res1.status_code == 200
        assert "flattened" in res1.json()
        assert "TSLA" in res1.json()["flattened"]

        res2 = client.post("/api/flatten", json={})
        assert res2.status_code == 200
        assert "remaining_positions" in res2.json()
        assert res2.json()["remaining_positions"] == 0
    finally:
        account.positions.pop("TSLA", None)
