import assert from 'node:assert/strict';
import * as g from '../lib/gut.ts';
import { aggregatePerformance } from '../lib/performance.ts';
let count = 0;
const eq = (name, got, want) => { assert.deepEqual(got,want,name); count++; console.log(`  ok   ${name}`); };
const trade = (id,date,pnl,strategy_id='orb') => ({trade_id:id,session_date:date,strategy_id,realized_pnl:pnl,symbol:'A',quantity:1,avg_entry_price:10,avg_exit_price:10+pnl,fees:0,side:'LONG',status:'CLOSED',opened_at:date+'T14:00:00Z',closed_at:date+'T15:00:00Z',exit_reason:'target'});
const session = (date,pnl,extra={}) => ({session_date:date,opening_equity:10000,closing_equity:10000+pnl,realized_pnl:pnl,finished_trade_result:pnl,trades_count:1,fees:0,source:'durable',aggregate_only:false,trade_detail_complete:true,...extra});
const items=[trade('a','2026-10-01',10),trade('b','2026-10-07',-5,'overnight_nvda'),trade('c','2026-10-07',8,'overnight_iren'),trade('d','2026-10-07',9,'overnight_hut')];
eq('grouping, empty day and trade deduplication',g.groupBySessionDate([...items,items[0]],['2026-10-02']).map(d=>[d.date,d.pnl,d.trades]),[['2026-10-01',10,1],['2026-10-02',0,0],['2026-10-07',12,3]]);
eq('seven ET dates, Mon–Fri only',g.tradingDates('2026-10-07'),['2026-10-01','2026-10-02','2026-10-05','2026-10-06','2026-10-07']);
eq('DST-safe date arithmetic',g.tradingDates('2026-11-03'),['2026-10-28','2026-10-29','2026-10-30','2026-11-02','2026-11-03']);
eq('past sessions override items, missing days zero, null remains unknown',g.resultsDays(items,[session('2026-10-01',40),session('2026-10-05',0,{finished_trade_result:null})],'2026-10-07').map(d=>d.pnl),[40,0,null,0,12]);
eq('today uses items',g.resultsDays(items,[session('2026-10-07',999)],'2026-10-07').at(-1).pnl,12);
const sessions=[session('2026-10-01',40),session('2026-10-02',-15,{aggregate_only:true,source:'recovered'})];
const history=aggregatePerformance({period:'week',today:'2026-10-07',currentEquity:10012,dailyOpeningEquity:10000,sessions,trades:items,historyComplete:true});
eq('bar sum equals History Week finished-trade total for same dates',g.resultsDays(items,sessions,'2026-10-07').reduce((n,d)=>n+d.pnl,0),history.finishedTradeResult.signedDollars);
eq('per strategy totals and three overnight ids',g.weekResultByStrategy([...items,items[0]]),{orb:10,overnight_nvda:-5,overnight_iren:8,overnight_hut:9,overnight:12});
const recovered=session('2026-10-02',17,{aggregate_only:true,strategies:{orb:{realized_pnl:17,trades_count:1}}});
eq('recovered aggregates added once',g.weekResultByStrategy(items,[recovered,recovered]).orb,27);
for(const [age,state,want] of [[0,'live','Running · updated 0 s ago'],[60,'live','Running · updated 1 min ago'],[61,'live','stale 1 min'],[12,'reconnecting','stale 12 s'],[30,'stale','stale 30 s'],[120,'live','stale 2 min'],[NaN,'reconnecting','Connecting']]) eq(`freshness ${age}/${state}`,g.freshnessLabel(age,state),want);
for(const status of ['OPEN','FLATTENING']) { eq(`${status} on trading day`,g.isMarketOpen(status,true),true); eq(`${status} on Sunday`,g.isMarketOpen(status,false),false); }
eq('closed stays closed',g.isMarketOpen('CLOSED',true),false);
eq('calendar flag wins',g.tradingDayOf([{window:{trading_day:false}}],new Date('2026-10-07T14:00:00Z')),false);
eq('Sunday fallback',g.tradingDayOf([],new Date('2026-10-11T14:00:00Z')),false);
const ovn={overnight:true,strategy_id:'overnight_nvda'};
for(const [min,td,want] of [[569,true,true],[570,true,false],[952,true,false],[959,true,false],[960,true,true],[600,false,true]]) eq(`stale at ${min}, trading ${td}`,g.overnightPriceIsStale(ovn,min,td),want);
eq('unequal overnight prices still stale after close',g.overnightPriceIsStale({...ovn,entry_price:10,market_price:12},1000,true),true);
eq('day position excluded from overnight stale rule',g.overnightPriceIsStale({strategy_id:'orb'},1000,true),false);
for(const state of ['CAN_TRADE','LIMITED','BLOCKED','MANAGING','NO_TRADE_TODAY']) eq(`${state} opens playbooks`,g.playbooksInitiallyOpen([{window:{state}}],0),true);
for(const state of ['DONE_FOR_DAY','MARKET_CLOSED','PAUSED','WAITING']) eq(`${state} closes playbooks`,g.playbooksInitiallyOpen([{window:{state}}],0),false);
eq('day holding opens playbooks',g.playbooksInitiallyOpen([],1),true);
eq('summary from data',g.playbookSummaryLine([{id:'tsla_asymmetric_dual',name:'Tesla',window:{state:'DONE_FOR_DAY'}}],{tsla_asymmetric_dual:-39},3),'1 done for today · Tesla -$39.00 in 7 days · Overnight holding 3');
const day={symbol:'TSLA',side:'SHORT',strategy_id:'tsla_asymmetric_dual'};
eq('day alarm maps to supported handler',g.firstAlarmAction([{key:'unprotected:TSLA'}],[day]),{label:'Close TSLA now',symbol:'TSLA'});
eq('only first alarm gets action',g.firstAlarmAction([{key:'feed'},{key:'unprotected:TSLA'}],[day]),null);
for(const key of ['unsold','overnight-look:NVDA','mismatch','loss-stop','unprotected:NVDA']) eq(`${key} cannot flatten overnight`,g.firstAlarmAction([{key}],[{...ovn,symbol:'NVDA'}]),null);
eq('swing excluded from day handler',g.firstAlarmAction([{key:'unprotected:SPY'}],[{symbol:'SPY',strategy_id:'swing_panic'}]),null);
const now=new Date('2026-10-07T15:35:00-04:00');
eq('backend lock countdown',g.lockCountdown('2026-10-07T15:49:00-04:00',now,true),'Overnight buy locks in 14 min');
for(const [until,planned] of [[undefined,true],['bad',true],['2026-10-07T15:34:00-04:00',true],['2026-10-07T16:00:00-04:00',true],['2026-10-07T15:49:00-04:00',false]]) eq(`no lock countdown ${until}/${planned}`,g.lockCountdown(until,now,planned),null);
console.log(`\n${count} gut helper checks passed`);
