"""Regenerate / verify the ORBStraddle copies in this package.

Each copied module is ORBStraddle's file at the pinned commit plus ONLY the exact text replacements
listed in SYNC_EDITS.json, with a generated header on top. Used by scripts/orbs_parity/sync_copy.py
(regenerate) and backend/tests/unit/orbs/test_sync.py (verify, so any drift or hand edit is visible).
"""
from __future__ import annotations

import hashlib
import json
import os
from typing import Dict, List, Optional, Tuple

PKG_DIR = os.path.dirname(os.path.abspath(__file__))
EDITS_PATH = os.path.join(PKG_DIR, "SYNC_EDITS.json")
HEADER_END = "# --- end of ADT copy header ---\n"
COPIED_FILES = ("ticks.py", "signals.py", "orbproc.py", "flow.py", "market.py", "scanner.py", "adaptive.py",
                "session_calendar.py")
DEFAULT_SOURCE_DIR = "/Users/mo/ORBStraddle"


def load_spec(path: str = EDITS_PATH) -> dict:
    with open(path) as handle:
        return json.load(handle)


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def apply_edits(name: str, source: str, spec: Optional[dict] = None) -> str:
    """ORBStraddle source text -> copied body (no header). Every edit must match exactly `count` times."""
    spec = spec or load_spec()
    out = source
    for edit in spec["files"][name]:
        found = out.count(edit["old"])
        if found != edit["count"]:
            raise ValueError(f"{name}: edit {edit['why']!r} matched {found} times, expected {edit['count']}")
        out = out.replace(edit["old"], edit["new"])
    return out


def header(name: str, spec: Optional[dict] = None) -> str:
    spec = spec or load_spec()
    edits = spec["files"][name]
    lines = [f"# Copied from ORBStraddle {name} @{spec['source_commit']}; logic unchanged; edits:"
             + (" none" if not edits else "")]
    for i, edit in enumerate(edits, 1):
        lines.append(f"#   {i}. {edit['why']}")
    lines.append("# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not")
    lines.append("# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.")
    return "\n".join(lines) + "\n" + HEADER_END


def render(name: str, source: str, spec: Optional[dict] = None) -> str:
    spec = spec or load_spec()
    return header(name, spec) + apply_edits(name, source, spec)


def split_header(text: str) -> Tuple[str, str]:
    idx = text.find(HEADER_END)
    if idx < 0:
        raise ValueError("copy header marker missing")
    cut = idx + len(HEADER_END)
    return text[:cut], text[cut:]


def check_sources(source_dir: str = DEFAULT_SOURCE_DIR, spec: Optional[dict] = None) -> Dict[str, str]:
    """{file: problem} for every ORBStraddle source file whose content is not the pinned commit's."""
    spec = spec or load_spec()
    problems = {}
    for name, want in spec["source_sha256"].items():
        path = os.path.join(source_dir, name)
        try:
            with open(path, encoding="utf-8") as handle:
                got = sha256_text(handle.read())
        except OSError as exc:
            problems[name] = f"unreadable: {exc}"
            continue
        if got != want:
            problems[name] = f"content differs from {spec['source_commit']} (sha256 {got[:12]} != {want[:12]})"
    return problems


def check_copies(source_dir: str = DEFAULT_SOURCE_DIR, spec: Optional[dict] = None) -> List[str]:
    """Differences between each copied file and render(original). Empty list = copies are exact."""
    spec = spec or load_spec()
    diffs = []
    for name in COPIED_FILES:
        with open(os.path.join(source_dir, name), encoding="utf-8") as handle:
            want = render(name, handle.read(), spec)
        with open(os.path.join(PKG_DIR, name), encoding="utf-8") as handle:
            got = handle.read()
        if got != want:
            diffs.append(name)
    return diffs


def write_copies(source_dir: str = DEFAULT_SOURCE_DIR, spec: Optional[dict] = None) -> List[str]:
    spec = spec or load_spec()
    problems = check_sources(source_dir, spec)
    if problems:
        raise RuntimeError(f"ORBStraddle sources are not the pinned commit: {problems}")
    written = []
    for name in COPIED_FILES:
        with open(os.path.join(source_dir, name), encoding="utf-8") as handle:
            text = render(name, handle.read(), spec)
        with open(os.path.join(PKG_DIR, name), "w", encoding="utf-8") as handle:
            handle.write(text)
        written.append(name)
    return written
