# Copied from ORBStraddle adaptive.py @05d370d; logic unchanged; edits:
#   1. package-relative imports; `core` -> ADT shim (today, now_et, _valid_card, long_only, urlopen)
#   2. package-relative lazy import of flow
#   3. package-relative dynamic import of flow
#   4. HTTP goes through shim.urlopen (default urllib.request.urlopen; injectable for replay): _relay_page (news + index bars, retried) and fetch_deal_headlines
#   5. package-relative lazy import of session_calendar (deal rule prior-close evidence)
#   6. ADT exclude_symbols: excluded names stay on the board (regime unchanged) but leave the eligible pool before pick 1 / pick 2; empty set = original behaviour
#   7. ADT exclude_symbols: audit reason `excluded_symbol` for an excluded candidate
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
"""Experimental multi-signal selector with hand-set weights and payoff assumptions.

Probability and EV are uncalibrated model estimates per $1,000 reference risk.
The participation proxy is not a measured tape-speed z-score. Missing mandatory
market context causes a cash pass; this module does not establish a profit target.
"""
import json, math, os, re, sys, threading, time as _t, urllib.error, urllib.parse, urllib.request
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo
from . import config, signals
from . import shim as core

ET = ZoneInfo("America/New_York")
ADAPTIVE_VERSION = "adaptive-v1.7.1-deal-rule"

# ---- Sector ETF Mapping for Cross-Trade Diversification ----
SECTOR_MAP = {
    # Tech (XLK / SMH)
    "AAPL": "XLK", "MSFT": "XLK", "NVDA": "XLK", "AMD": "XLK", "AVGO": "XLK", "QCOM": "XLK",
    "INTC": "XLK", "CRM": "XLK", "ADBE": "XLK", "ORCL": "XLK", "CSCO": "XLK", "NOW": "XLK",
    "INTU": "XLK", "IBM": "XLK", "TXN": "XLK", "AMAT": "XLK", "LRCX": "XLK", "MU": "XLK",
    "PANW": "XLK", "FTNT": "XLK", "CRWD": "XLK", "SNOW": "XLK", "PLTR": "XLK", "DELL": "XLK",
    "ANET": "XLK", "MDB": "XLK", "DDOG": "XLK", "NET": "XLK", "TEAM": "XLK", "ZS": "XLK",
    "SMCI": "XLK", "ARM": "XLK", "CIEN": "XLK", "MRVL": "XLK", "KLAC": "XLK", "SNPS": "XLK",
    "CDNS": "XLK", "NXPI": "XLK", "ADI": "XLK", "ON": "XLK", "CRDO": "XLK", "APP": "XLK",
    # Communications (XLC)
    "GOOG": "XLC", "GOOGL": "XLC", "META": "XLC", "NFLX": "XLC", "DIS": "XLC", "CMCSA": "XLC",
    "TMUS": "XLC", "VZ": "XLC", "T": "XLC", "SPOT": "XLC", "RBLX": "XLC", "PINS": "XLC",
    "SNAP": "XLC", "TTWO": "XLC", "EA": "XLC", "WBD": "XLC", "CHTR": "XLC", "ROKU": "XLC",
    # Consumer Discretionary (XLY)
    "AMZN": "XLY", "TSLA": "XLY", "HD": "XLY", "MCD": "XLY", "NKE": "XLY", "SBUX": "XLY",
    "LOW": "XLY", "TJX": "XLY", "BKNG": "XLY", "ABNB": "XLY", "MAR": "XLY", "LULU": "XLY",
    "CMG": "XLY", "EBAY": "XLY", "ROST": "XLY", "ORLY": "XLY", "AZO": "XLY", "DHI": "XLY",
    "LEN": "XLY", "GM": "XLY", "F": "XLY", "DKS": "XLY", "BABA": "XLY", "PDD": "XLY",
    "MELI": "XLY", "ULTA": "XLY", "BMNR": "XLY", "CAVA": "XLY",
    # Financials (XLF)
    "JPM": "XLF", "BAC": "XLF", "WFC": "XLF", "C": "XLF", "GS": "XLF", "MS": "XLF",
    "BLK": "XLF", "SCHW": "XLF", "AXP": "XLF", "V": "XLF", "MA": "XLF", "PYPL": "XLF",
    "COIN": "XLF", "HOOD": "XLF", "SOFI": "XLF", "IBKR": "XLF", "MCO": "XLF", "SPGI": "XLF",
    # Health Care (XLV)
    "LLY": "XLV", "UNH": "XLV", "JNJ": "XLV", "ABBV": "XLV", "MRK": "XLV", "TMO": "XLV",
    "ABT": "XLV", "DHR": "XLV", "PFE": "XLV", "AMGN": "XLV", "ISRG": "XLV", "BMY": "XLV",
    "GILD": "XLV", "VRTX": "XLV", "REGN": "XLV", "MDT": "XLV", "ELV": "XLV", "CI": "XLV",
    # Industrials (XLI)
    "CAT": "XLI", "DE": "XLI", "GE": "XLI", "UNP": "XLI", "HON": "XLI", "UPS": "XLI",
    "BA": "XLI", "RTX": "XLI", "LMT": "XLI", "FDX": "XLI", "WM": "XLI", "ETN": "XLI",
    # Energy (XLE)
    "XOM": "XLE", "CVX": "XLE", "COP": "XLE", "EOG": "XLE", "SLB": "XLE", "MPC": "XLE",
    "PSX": "XLE", "VLO": "XLE", "OXY": "XLE", "HES": "XLE", "HAL": "XLE",
    # Materials (XLB)
    "LIN": "XLB", "APD": "XLB", "SHW": "XLB", "FCX": "XLB", "ECL": "XLB", "NEM": "XLB"
}

# Mega-cap tickers (never taken as failed gap/structure)
MEGA = {"AAPL", "MSFT", "NVDA", "GOOGL", "GOOG", "AMZN", "META", "TSLA", "AVGO", "TSM", "BRK.B"}

# ---- Adaptive Core Parameters ----
ADAPTIVE_CONFIG = {
    # Regime Gates
    "SPY_SLOPE_BULL_MIN": 1.5,     # bps/min
    "SPY_SLOPE_BEAR_MAX": -1.5,    # bps/min
    "MIN_BREADTH_EXPANSION": 1.5,  # advancers/decliners
    "MAX_BOARD_SHORT_FRAC": 0.75,  # sit out if board is >75% short
    "MIN_BOARD_SHORT_FRAC": 0.25,  # sit out if board is <25% short

    # Microstructure Gates
    "MAX_SPREAD_BPS": 8.0,
    "MAX_STOP_PCT": 7.5,           # stop distance <= 7.5% of entry
    "MIN_STOP_PCT": 0.5,           # stop distance >= 0.5% of entry
    "MAX_DRIFT_R": 0.25,           # drift <= 25% of stop distance
    "MIN_RVOL": 2.2,               # RVOL >= 2.2x
    "MIN_ATR_PCT": 2.0,            # ATR% >= 2.0%
    "MIN_GAP_REAL": 0.8,           # gap against direction >= 0.8%

    # Utility Gating & Thresholds ($1,000 Risk per Bet on $50k Account)
    "CASH_HURDLE_EV": 250.0,       # top pick must offer >= +$250 expected net edge (+0.25R)
    "SECOND_PICK_HURDLE_EV": 350.0,# second pick must offer >= +$350 edge (+0.35R)
    "MIN_WIN_PROB": 0.54,          # probit-moderated win probability floor
    "LAMBDA_UNCERTAINTY": 0.35,    # parameter variance penalty
    "LAMBDA_TAIL": 0.50,           # hard-stop tail risk penalty
    "MAX_DAILY_PICKS": 2           # strictly 1 or 2 picks
}

def _num(x, d=None):
    try:
        v = float(x)
        return v if (v == v and v not in (float("inf"), float("-inf"))) else d
    except (TypeError, ValueError):
        return d


class NewsDataError(RuntimeError):
    """The news producer did not provide a complete, bounded response."""


def _record_health(key, label, state, detail, action=""):
    """Record fixed, safe producer telemetry without making telemetry a trade guard."""
    try:
        import data_health
        data_health.record(key, label, state, detail, action=action)
    except Exception:
        pass


def _news_error():
    _record_health("news", "Company news", "error",
                   "Company news could not be verified completely; adaptive entries are paused.",
                   "Check the market data connection and retry the decision.")


def _news_ok(n):
    detail = ("Company news was retrieved completely; no qualifying catalyst headlines were found."
              if n == 0 else
              "Company news was retrieved completely; qualifying catalyst headlines were verified.")
    _record_health("news", "Company news", "ok", detail)

# =====================================================================
# SECTION 1: Benzinga NLP Catalyst Classifier (5-Tier Taxonomy)
# =====================================================================

RESULT_LINE = re.compile(
    r"\b(Q[1-4]|H[12]|FY\d{2,4})\b[^|]*?\b(?:Adj\.?|Adjusted|GAAP)?\s*(EPS|EPADS|EPADR)\s*\$?\(?-?[\d.]+\)?\s*(Beats?|Misses|Miss|Tops|In[- ]Line With)\b",
    re.I
)
GUIDANCE_LINE = re.compile(r"\b(Raises|Lowers|Cuts|Boosts|Guides|Sees)\b.*?\b(FY|Q[1-4]|Revenue|Sales|EPS)\b", re.I)
CONTRACT_LINE = re.compile(r"\b(?:FDA (?:Approves|Approval|Clearance)|(?:Awarded|Wins|Secures|Receives)\b[^.;]*\bContract)\b", re.I)
NEGATIVE_CONTRACT = re.compile(r"\b(?:not|denied|rejects?|rejected|withdraws?|withdrawn|terminates?|terminated|cancelled|cancels?|fails?)\b", re.I)
OFFERING_LINE = re.compile(r"\b(Public Offering|Secondary Offering|Form S-3|Priced Offering)\b", re.I)

def classify_catalyst(headline):
    """Classifies a news headline into the 5-Tier NLP Taxonomy:
    T1: Official Earnings Beat/Miss
    T2: Major Structural Contract / FDA Clearance
    T3: Dilutive Secondary Offering (toxic for longs)
    T4: Guidance Revision Alone
    T5: General / Analyst / Ordinary
    """
    if not headline:
        return {"tier": "T5", "type": "none", "grade": None, "score": 0.0}

    # Check T3: Secondary Offering (instant long veto)
    if OFFERING_LINE.search(headline):
        return {"tier": "T3", "type": "offering", "grade": "dilution", "score": -2.0}

    # Check T1: Canonical Results Line
    m = RESULT_LINE.search(headline)
    if m:
        w = m.group(3).lower()
        grade = "beat" if w.startswith(("beat", "top")) else "miss" if w.startswith("miss") else "inline"
        # Check guidance synergy
        guidance = "neutral"
        if GUIDANCE_LINE.search(headline):
            gm = GUIDANCE_LINE.search(headline).group(1).lower()
            if gm in ("raises", "boosts"): guidance = "raised"
            elif gm in ("lowers", "cuts"): guidance = "lowered"
        score = 2.0 if grade == "beat" else -2.0 if grade == "miss" else 0.5
        if guidance == "raised": score += 1.0
        elif guidance == "lowered": score -= 1.0
        return {"tier": "T1", "type": "earnings", "grade": grade, "guidance": guidance, "score": score}

    # Check T2: Contract / FDA Approval
    if CONTRACT_LINE.search(headline) and not NEGATIVE_CONTRACT.search(headline):
        return {"tier": "T2", "type": "contract_fda", "grade": "positive", "score": 1.5}

    # Check T4: Guidance Revision
    if GUIDANCE_LINE.search(headline):
        gm = GUIDANCE_LINE.search(headline).group(1).lower()
        grade = "raised" if gm in ("raises", "boosts") else "lowered" if gm in ("lowers", "cuts") else "neutral"
        score = 1.0 if grade == "raised" else -1.0 if grade == "lowered" else 0.0
        return {"tier": "T4", "type": "guidance", "grade": grade, "score": score}

    return {"tier": "T5", "type": "general", "grade": "neutral", "score": 0.0}

NEWS_PAGE_CAP = 40
# One news page may be retried this many times inside the fetch budget. 2026-10-02: nine ORB
# robots scan the shared relay at once and a single transport glitch on one page sat a bot out
# for the whole day. Transient failures retry; data defects and client errors still fail closed.
NEWS_PAGE_ATTEMPTS = 3
NEWS_RETRIABLE_HTTP = (429, 500, 502, 503, 504)
_news_sleep = _t.sleep


def _news_retry_after(exc, fallback):
    try:
        value = float((exc.headers or {}).get("Retry-After", ""))
        return min(value, 10.0) if value >= 0.0 else fallback
    except (TypeError, ValueError, AttributeError):
        return fallback


def _relay_page(req, deadline, per_try=10.0, what="news"):
    """One relay page (news, index bars), with bounded retries for transport and relay-busy
    failures. Each try waits at most ``per_try`` seconds and never past ``deadline``.

    Raises NewsDataError carrying ``detail`` (attempts, cause class and text) so the
    caller can record why a wave was sat out; health telemetry never carries raw text.
    """
    last = None
    attempts = 0
    for attempt in range(1, NEWS_PAGE_ATTEMPTS + 1):
        remaining = deadline - _t.monotonic()
        if remaining <= 0:
            break
        try:
            timeout = max(0.1, min(per_try, remaining))
            attempts += 1
            with core.urlopen(req, timeout=timeout) as resp:
                return json.load(resp)
        except urllib.error.HTTPError as exc:
            last = exc
            if exc.code not in NEWS_RETRIABLE_HTTP:
                break
            pause = _news_retry_after(exc, min(0.5 * (2 ** (attempt - 1)), 4.0))
        except Exception as exc:
            last = exc
            pause = min(0.5 * (2 ** (attempt - 1)), 4.0)
        if attempt >= NEWS_PAGE_ATTEMPTS or pause > max(0.0, deadline - _t.monotonic()):
            break
        _news_sleep(pause)
    if last is None:
        err = NewsDataError(f"{what} budget exhausted")
        err.detail = {"attempts": attempts, "cause": "no time left for a request"}
        raise err
    err = NewsDataError(f"{what} provider request failed")
    err.detail = {"attempts": attempts, "cause": f"{type(last).__name__}: {str(last)[:160]}"}
    raise err from last


def fetch_earnings_headlines(symbols, freeze_dt, budget_s=30.0):
    """Fetch complete, timestamped news data or fail closed.

    An empty result is valid only after every batch has reached its terminal page. A
    timeout, malformed response, or pagination cap means dilution is unknowable and
    raises ``NewsDataError`` so the caller can take an explicit cash pass.
    """
    symbols = sorted({str(s).upper() for s in symbols if s})
    if not symbols:
        _news_ok(0)
        return {}
    _record_health("news", "Company news", "waiting", "Checking complete company news coverage.")

    start_iso = (freeze_dt - timedelta(hours=49)).astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    end_iso = freeze_dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    url_base = config.NEWS_URL          # relay proxy; this bot holds no Alpaca credentials
    batches = [symbols[i:i + 40] for i in range(0, len(symbols), 40)]
    deadline = _t.monotonic() + max(0.1, float(budget_s))
    candidates = {}

    try:
        for batch in batches:
            page_token = None
            pages = 0
            while True:
                remaining = deadline - _t.monotonic()
                if remaining <= 0:
                    raise NewsDataError("news budget exhausted")
                if pages >= NEWS_PAGE_CAP:
                    raise NewsDataError("news pagination cap reached")
                q = {"symbols": ",".join(batch), "start": start_iso, "end": end_iso,
                     "limit": 50, "sort": "desc", "include_content": "false"}
                if page_token:
                    q["page_token"] = page_token
                req = urllib.request.Request(url_base + "?" + urllib.parse.urlencode(q),
                                             headers=dict(config.RELAY_HEADERS))
                data = _relay_page(req, deadline)
                if _t.monotonic() > deadline:
                    raise NewsDataError("news budget exhausted")
                if not isinstance(data, dict) or not isinstance(data.get("news"), list):
                    raise NewsDataError("news provider response malformed")
                pages += 1
                for item in data["news"]:
                    if not isinstance(item, dict):
                        raise NewsDataError("invalid news item")
                    headline = item.get("headline", "")
                    cat = classify_catalyst(headline)
                    if cat["grade"] not in ("beat", "miss", "positive", "dilution", "raised", "lowered"):
                        continue
                    syms = item.get("symbols") or []
                    if not isinstance(syms, list) or len(syms) > 3:
                        if not isinstance(syms, list): raise NewsDataError("invalid news symbols")
                        continue
                    raw_created = item.get("created_at")
                    try:
                        parsed = datetime.fromisoformat(str(raw_created).replace("Z", "+00:00"))
                        # A naive created_at has no market-time provenance. Do not let
                        # the host timezone silently turn it into an observation time.
                        if parsed.tzinfo is None or parsed.utcoffset() is None:
                            raise ValueError("missing timezone")
                        ts = parsed.astimezone(ET)
                    except (TypeError, ValueError, OverflowError):
                        raise NewsDataError("relevant news timestamp unavailable")
                    hrs = (freeze_dt - ts).total_seconds() / 3600.0
                    if not (0.0 <= hrs <= 48.0):
                        continue
                    row = {"hours_ago": round(hrs, 1), "result": cat["grade"],
                           "tier": cat["tier"], "catalyst": cat,
                           "report_datetime_ET": ts.strftime("%Y-%m-%d %H:%M"),
                           "headline": str(headline)[:140], "_ts": ts.timestamp()}
                    for symbol in syms:
                        symbol = str(symbol).upper()
                        if symbol in batch:
                            candidates.setdefault(symbol, []).append(row)
                page_token = data.get("next_page_token")
                if not page_token:
                    break
    except NewsDataError:
        _news_error()
        raise
    except Exception:
        _news_error()
        raise NewsDataError("news provider response unavailable")

    # A later offering must veto an earlier earnings beat for the same symbol. The
    # previous first-row-wins behavior made dilution disappear when it was not newest.
    priority = {"T3": 4, "T1": 3, "T2": 2, "T4": 1}
    found = {}
    for symbol, rows in candidates.items():
        chosen = max(rows, key=lambda row: (priority.get(row["tier"], 0), row["_ts"]))
        chosen = dict(chosen)
        chosen.pop("_ts", None)
        found[symbol] = chosen
    _news_ok(len(found))
    return found

# ---- Deal rule (DEAL_RULE_LIVE_PLAN_2026-10-01.md): a company-announced new deal blocks a new SHORT ----
DEAL_WIN = re.compile(r"\b(?:signs|signed|wins|won(?!['’]t)|secures|secured|awarded|lands|landed|selected|"
                      r"inks|inked|receives|received|gets|books|booked)\b", re.I)
DEAL_NOUN = re.compile(r"\b(?:deal|contract|order|agreement|award)\b", re.I)
DEAL_DOUBT = re.compile(r"\b(?:acquired|acquire|acquisition|merger|take private|taken private|to sell|sale of|divest|"
                        r"financing|credit|loan|notes|offering|settlement|lease|lawsuit|ruling|court|dispute|"
                        r"executive order|award for|price target|order book|loss|in talks|nears|considering|"
                        r"reportedly|rumou?r|stop-work|losing|lost|show cause|notice)\b", re.I)
DEAL_REPORT = re.compile(r"(?::\s*report\b|-\s*report\b|\breport:)", re.I)
DEAL_BUDGET_S = 8.0
_DEAL_BLOCKED = {}   # day -> {symbol: {"ts", "headline"}}; a block holds for the rest of the day


def is_deal_headline(headline):
    """True when the headline announces the company signing/winning a new deal, contract or order."""
    h = headline if isinstance(headline, str) else ""
    return bool(h and DEAL_WIN.search(h) and DEAL_NOUN.search(h) and not DEAL_DOUBT.search(h)
                and not NEGATIVE_CONTRACT.search(h) and not DEAL_REPORT.search(h))


def prior_close(freeze_dt):
    """Actual prior-session close from pre-open calendar evidence; no network calls.

    An unknown weekday must not be assumed to be a session: on the morning after
    a holiday that loses the whole weekend's news. Missing evidence uses the
    plan's explicit 96-hour fallback, with a separate deal-window warning.
    """
    from . import session_calendar
    close = session_calendar.prior_session_close(freeze_dt.astimezone(ET).date())
    if close is not None:
        _record_health("deal_window_fallback", "Deal news window", "ok",
                       "Deal news starts at the verified prior-session close.")
        return close
    _record_health("deal_window_fallback", "Deal news window", "warning",
                   "Prior-session close evidence is unavailable; deal news uses the 96-hour fallback.",
                   "Check the pre-open calendar and reference-data preparation.")
    return freeze_dt - timedelta(hours=96)


def fetch_deal_headlines(symbols, freeze_dt, budget_s=DEAL_BUDGET_S):
    """Return ({symbol: {"ts", "headline"}}, complete). Never raises: any failure returns what was
    found with complete=False, so a news glitch never sits the day out (fails open for this rule only)."""
    symbols = sorted({str(s).upper() for s in symbols if s})
    found = {}
    if not symbols:
        return found, True
    try:
        start_dt = prior_close(freeze_dt)
        start_iso = start_dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        end_iso = freeze_dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        deadline = _t.monotonic() + max(0.1, float(budget_s))
        for batch in [symbols[i:i + 40] for i in range(0, len(symbols), 40)]:
            page_token, pages = None, 0
            while True:
                remaining = deadline - _t.monotonic()
                if remaining <= 0 or pages >= NEWS_PAGE_CAP:
                    raise NewsDataError("deal news budget exhausted")
                q = {"symbols": ",".join(batch), "start": start_iso, "end": end_iso,
                     "limit": 50, "sort": "desc", "include_content": "false"}
                if page_token:
                    q["page_token"] = page_token
                req = urllib.request.Request(config.NEWS_URL + "?" + urllib.parse.urlencode(q),
                                             headers=dict(config.RELAY_HEADERS))
                with core.urlopen(req, timeout=max(0.1, min(5.0, remaining))) as resp:
                    data = json.load(resp)
                if not isinstance(data, dict) or not isinstance(data.get("news"), list):
                    raise NewsDataError("deal news response malformed")
                pages += 1
                for item in data["news"]:
                    try:
                        syms = item.get("symbols")
                        if not isinstance(syms, list) or len(syms) != 1:
                            continue
                        sym = str(syms[0]).upper()
                        if sym not in batch or not is_deal_headline(item.get("headline")):
                            continue
                        ts = datetime.fromisoformat(str(item.get("created_at")).replace("Z", "+00:00"))
                        if ts.tzinfo is None or ts.utcoffset() is None:
                            continue
                        ts = ts.astimezone(ET)
                        if not (start_dt <= ts <= freeze_dt):
                            continue
                        if sym not in found or ts > found[sym]["_ts"]:
                            found[sym] = {"ts": ts.strftime("%Y-%m-%d %H:%M"),
                                          "headline": item["headline"][:140], "_ts": ts}
                    except Exception:
                        continue          # one bad item never spoils the rest
                page_token = data.get("next_page_token")
                if not page_token:
                    break
        complete = True
    except Exception:
        complete = False
    for row in found.values():
        row.pop("_ts", None)
    if complete:
        _record_health("deal_news", "Deal news", "ok",
                       "Deal news checked for today's short candidates." if not found else
                       f"Deal news checked; {len(found)} short candidate(s) had a company deal announcement.")
    else:
        _record_health("deal_news", "Deal news", "warning",
                       "Deal news could not be read completely; shorts not already blocked trade as normal.",
                       "Check the relay news proxy.")
    return found, complete


def _sticky_deal_blocks(day):
    """Blocks already made today: this process's set plus today's skip_deal ledger rows (survives a restart)."""
    out = dict(_DEAL_BLOCKED.get(str(day), {}))
    try:
        if str(day) == core.today():
            for row in core._todays("skip_deal"):
                sym = str(row.get("symbol") or "").upper()
                if sym and sym not in out:
                    out[sym] = {"ts": row.get("news_ts", row.get("ts", "")), "headline": row.get("headline", "")}
    except Exception:
        pass
    return out

# =====================================================================
# SECTION 2: Intraday Market Regime & Index Alignment
# =====================================================================

def _freeze_dt(day, when):
    return datetime.fromisoformat(f"{day}T{when}").replace(tzinfo=ET)


def _vwap_slope(bars, start_dt, end_dt):
    """Return a slope only when every expected one-minute bar is present."""
    expected = []
    cursor = start_dt.replace(second=0, microsecond=0)
    while cursor < end_dt:
        expected.append(cursor)
        cursor += timedelta(minutes=1)
    if len(expected) < 2:
        return None
    points = {}
    for bar in bars:
        try:
            raw_ts = str(bar["t"])
            ts = datetime.fromisoformat(raw_ts.replace("Z", "+00:00"))
            if ts.tzinfo is None or ts.utcoffset() is None or ts.second != 0 or ts.microsecond != 0:
                continue
            ts = ts.astimezone(ET)
            price, volume = _num(bar.get("vw")), _num(bar.get("v"))
            if ts not in expected:
                continue
            if price is not None and volume is not None and price > 0 and volume > 0:
                if ts in points and points[ts] != (price, volume): return None
                points[ts] = (price, volume)
        except (KeyError, TypeError, ValueError, AttributeError):
            continue
    if any(ts not in points for ts in expected):
        return None
    times = expected
    total_pv = total_vol = 0.0
    for ts in times:
        price, volume = points[ts]
        total_pv += price * volume
        total_vol += volume
    first = points[times[0]][0]
    minutes = (times[-1] - times[0]).total_seconds() / 60
    return round((total_pv / total_vol - first) / first * 1e4 / minutes, 2)


def evaluate_market_regime(day, freeze_time="09:38", cards=None,
                           spy_slope=None, qqq_slope=None):
    """Verify complete opening index data and a balanced directional board.

    Explicit SPY and QQQ slopes are deterministic research and test injections.
    Production obtains both values from complete one-minute bars.
    Board direction balance is not market-wide advance and decline breadth.
    """
    freeze_dt = _freeze_dt(day, freeze_time)
    regime = {"day": day, "asof": freeze_dt.isoformat(), "classification": "UNKNOWN",
              "action": "SIT_OUT_CASH", "spy_slope": None, "qqq_slope": None,
              "breadth_ratio": None, "short_frac": None, "reasons": []}
    if spy_slope is not None or qqq_slope is not None:
        regime["spy_slope"] = _num(spy_slope)
        regime["qqq_slope"] = _num(qqq_slope)
    else:
        _record_health("indices", "SPY / QQQ", "waiting", "Checking continuous opening minute bars.")
        try:
            open_dt = freeze_dt.replace(hour=9, minute=30, second=0)
            query = urllib.parse.urlencode({"symbols": "SPY,QQQ", "timeframe": "1Min",
                "start": open_dt.astimezone(timezone.utc).isoformat(),
                "end": freeze_dt.astimezone(timezone.utc).isoformat(), "feed": "sip", "limit": 1000})
            req = urllib.request.Request(config.INDEX_BARS_URL + "?" + query,
                                         headers=dict(config.RELAY_HEADERS))
            payload = _relay_page(req, _t.monotonic() + 9.0, per_try=3.0, what="index bars")
            if not isinstance(payload, dict) or not isinstance(payload.get("bars"), dict):
                raise ValueError("malformed index response")
            bars = payload["bars"]
            for sym, key in (("SPY", "spy_slope"), ("QQQ", "qqq_slope")):
                regime[key] = _vwap_slope(bars.get(sym) or [], open_dt, freeze_dt)
            if regime["spy_slope"] is None or regime["qqq_slope"] is None:
                _record_health("indices", "SPY / QQQ", "error",
                               "Continuous SPY and QQQ minute bars were not available; adaptive entries are paused.",
                               "Check the market data connection and retry the decision.")
            else:
                _record_health("indices", "SPY / QQQ", "ok",
                               "Continuous SPY and QQQ minute bars were verified through the decision time.")
        except Exception as exc:
            _record_health("indices", "SPY / QQQ", "error",
                           "SPY and QQQ minute bars could not be verified; adaptive entries are paused.",
                           "Check the market data connection and retry the decision.")
            try:
                core._ledger({"kind": "indices_unavailable", "day": day,
                              "why": str(exc) or type(exc).__name__,
                              "detail": getattr(exc, "detail", None)})
            except Exception:
                pass
    if regime["spy_slope"] is None or regime["qqq_slope"] is None:
        regime["reasons"].append("Opening SPY/QQQ VWAP data unavailable or incomplete")
    cards = cards or []
    # Candle rule: the regime reads the FIRST break of every card (board_direction), exactly the board it
    # read before the rule; a card without it was built with the rule off, where direction is the first break.
    # Flow rules 1/2 set board_direction the same way (the first old-gate break), so the board is unchanged.
    from . import flow
    _bd = (lambda c: c.get("board_direction") or c.get("direction")) \
        if (config.CANDLE_RULE or flow.entry_rules_on()) else (lambda c: c.get("direction"))
    shorts = sum(_bd(c) == "short" for c in cards)
    longs = sum(_bd(c) == "long" for c in cards)
    if not cards or shorts + longs != len(cards):
        regime["reasons"].append("No complete directional board")
    else:
        regime["short_frac"] = round(shorts / len(cards), 3)
        regime["breadth_ratio"] = round(longs / shorts, 2) if shorts else None
    if regime["reasons"]:
        return regime
    if not ADAPTIVE_CONFIG["MIN_BOARD_SHORT_FRAC"] <= shorts / len(cards) <= ADAPTIVE_CONFIG["MAX_BOARD_SHORT_FRAC"]:
        regime["classification"] = "ONE_SIDED"
        limit = ">75% limit" if shorts / len(cards) > 0.75 else "<25% limit"
        regime["reasons"].append(f"Board is {shorts / len(cards):.0%} short ({limit})")
    else:
        regime.update(classification="CALM_TREND", action="TRADE_NORMAL")
    return regime

# =====================================================================
# SECTION 3: Microstructure & Clean Tape Metrics
# =====================================================================

def card_risk_pct(card):
    """The card's stop distance as a percentage of entry price."""
    e, st = _num(card.get("entry")), _num(card.get("stop"))
    if e in (None, 0) or st is None: return None
    return abs(e - st) / e * 100.0

def card_drift_ratio(card):
    """Drift as a fraction of the card's own stop distance."""
    r = card_risk_pct(card)
    d = _num(card.get("drift_pct"))
    if r in (None, 0) or d is None: return None
    return d / r

def evaluate_microstructure(card):
    """Validate required card metrics and calculate a heuristic participation proxy."""
    if not core._valid_card(card):
        return False, "invalid card prices or direction"
    spread = _num(card.get("spread_bps"))
    if spread is None or spread < 0:
        return False, "spread unavailable or invalid"
    if spread > ADAPTIVE_CONFIG["MAX_SPREAD_BPS"]:
        return False, f"spread {spread:.1f} bps > {ADAPTIVE_CONFIG['MAX_SPREAD_BPS']} bps limit"

    rd = card_risk_pct(card)
    if rd is None or rd > ADAPTIVE_CONFIG["MAX_STOP_PCT"]:
        return False, f"stop distance {rd if rd is not None else 'unknown'}% > {ADAPTIVE_CONFIG['MAX_STOP_PCT']}% cap"
    if rd < ADAPTIVE_CONFIG["MIN_STOP_PCT"]:
        return False, f"stop distance {rd:.2f}% < {ADAPTIVE_CONFIG['MIN_STOP_PCT']}% minimum"

    dr = card_drift_ratio(card)
    if dr is None:
        return False, "drift unavailable or invalid"
    if dr > ADAPTIVE_CONFIG["MAX_DRIFT_R"]:
        return False, f"drift spent {dr*100:.0f}% of stop distance (> {ADAPTIVE_CONFIG['MAX_DRIFT_R']*100:.0f}% cap)"

    rvol = _num(card.get("rvol"), 0.0)
    if rvol < ADAPTIVE_CONFIG["MIN_RVOL"]:
        return False, f"RVOL {rvol:.1f}x < {ADAPTIVE_CONFIG['MIN_RVOL']}x threshold"

    atr = _num(card.get("atr_pct"), 0.0)
    if atr < ADAPTIVE_CONFIG["MIN_ATR_PCT"]:
        return False, f"ATR {atr:.1f}% < {ADAPTIVE_CONFIG['MIN_ATR_PCT']}% room threshold"

    raw_sofi = card.get("sofi") if "sofi" in card else card.get("sofi_z")
    sofi_z = _num(raw_sofi)
    if sofi_z is None:
        return False, "SOFI participation z-score unavailable or invalid"
    sofi_z = abs(sofi_z)
    z_tps = round(0.6 * (rvol - 2.0) + 0.4 * (sofi_z - 2.0) + 2.0, 2)

    return True, {
        "z_tps": z_tps,
        "spread_bps": spread,
        "rd_pct": round(rd, 2),
        "drift_r": round(dr if dr is not None else 0.0, 3),
        "rvol": rvol,
        "atr_pct": atr
    }

# =====================================================================
# SECTION 4: Bayesian Confidence & Risk-Adjusted Utility
# =====================================================================

def compute_bayesian_utility(card, micro_data, catalyst_data, regime_data):
    """Computes:
    1. Uncalibrated logistic estimate of hitting target (+0.75R).
    2. Expected Value in R and net dollars ($1,000 risk per trade).
    3. Risk-adjusted utility U penalizing parameter uncertainty and tail risk.
    """
    intercept = 0.15
    cat_score = catalyst_data.get("catalyst", {}).get("score", 0.0) if catalyst_data else 0.0
    z_tps = micro_data.get("z_tps", 2.0)
    rvol = micro_data.get("rvol", 2.5)
    drift_r = micro_data.get("drift_r", 0.0)

    spy_slope = regime_data.get("spy_slope", 0.0)
    is_long = card.get("direction") == "long"
    slope_align = 0.0 if spy_slope == 0 else (0.3 if ((spy_slope > 0) == is_long) else -0.4)

    # Align catalyst score with trade direction:
    # A negative catalyst (earnings miss -2.0) is positively aligned (+2.0) for a short trade!
    if catalyst_data and catalyst_data.get("reprice"):
        aligned_cat = abs(cat_score) * 0.5
    else:
        aligned_cat = cat_score if is_long else -cat_score

    mu_score = (
        intercept +
        0.35 * aligned_cat +
        0.25 * (z_tps - 2.0) +
        0.15 * (rvol - 2.5) -
        0.50 * max(0.0, drift_r) +
        0.20 * slope_align
    )

    sigma_sq = 0.18 + (0.10 if aligned_cat == 0.0 else 0.02) + 0.04

    moderated_z = mu_score / math.sqrt(1.0 + (math.pi / 8.0) * sigma_sq)
    p_win = 1.0 / (1.0 + math.exp(-moderated_z))
    p_win = max(0.40, min(0.85, p_win))

    # Normalization of the assumed payoff matrix (PLAN.md Section 4.3):
    # At p_win = 0.50: clawback=0.12, flat=0.08, loss=0.30
    p_rem = max(0.0, 1.0 - p_win)
    p_claw = 0.24 * p_rem
    p_flat = 0.16 * p_rem
    p_loss = 0.60 * p_rem

    p_ff = 0.85 * p_loss
    p_stop = 0.15 * p_loss

    ev_r = (
        0.75 * p_win +
        0.25 * p_claw +
        0.00 * p_flat -
        0.40 * p_ff -
        1.00 * p_stop -
        0.03
    )

    ev_dollars = round(ev_r * 1000.0, 2)
    std_err = math.sqrt(sigma_sq)
    utility = ev_r - ADAPTIVE_CONFIG["LAMBDA_UNCERTAINTY"] * std_err - ADAPTIVE_CONFIG["LAMBDA_TAIL"] * p_stop

    return {
        "p_win": round(p_win, 3),
        "win_prob": round(p_win, 3),
        "ev_r": round(ev_r, 4),
        "ev_dollars": ev_dollars,
        "utility": round(utility, 4),
        "std_err": round(std_err, 3),
        "p_stop": round(p_stop, 3)
    }

# =====================================================================
# SECTION 5: Selection & Decision Engine
# =====================================================================

def select_adaptive(cards, day=None, freeze_time="09:38", earnings=None,
                    spy_slope=None, qqq_slope=None, earn_reprice_gap=None, deals=None):
    """Executes the complete adaptive decision logic:
    1. Regime Check (sitting 100% in cash if hostile).
    2. Microstructure & Tape Filtration.
    3. Benzinga NLP Catalyst classification.
    4. Bayesian Utility Scoring & Ranking.
    5. Sector Diversification for Trade 2.
    Returns: (picks, audit_rows, regime_info)
    """
    day = day or core.today()
    earnings_injected = earnings is not None
    regime = evaluate_market_regime(
        day, freeze_time, cards=cards, spy_slope=spy_slope, qqq_slope=qqq_slope)
    audit_rows = []
    earn_reprice_gap = _num(
        config.EARN_REPRICE_GAP if earn_reprice_gap is None else earn_reprice_gap)
    if earn_reprice_gap is None or earn_reprice_gap < 0:
        regime["classification"] = "UNKNOWN"
        regime["action"] = "SIT_OUT_CASH"
        regime["reasons"].append("Earnings reprice threshold is unavailable or invalid")

    # If Market Regime forces 100% Cash Sit-Out:
    if regime["action"] == "SIT_OUT_CASH":
        audit_rows.append({
            "symbol": "*",
            "tier": "regime",
            "survives": False,
            "case_against_strength": "specific",
            "why": f"Market Regime Sit-Out: {'; '.join(regime['reasons'])}"
        })
        return [], audit_rows, regime

    # Fetch earnings headlines if not provided. A complete empty result is valid;
    # an unavailable/partial producer response is an explicit cash pass because
    # dilution cannot be ruled out safely.
    deals_injected = deals is not None
    if earnings is None:
        try:
            freeze_dt = _freeze_dt(day, freeze_time)
            earnings = fetch_earnings_headlines([c["symbol"] for c in cards], freeze_dt)
        except Exception as exc:
            regime["classification"] = "UNKNOWN"
            regime["action"] = "SIT_OUT_CASH"
            reason = "Company news unavailable or incomplete; dilution cannot be verified"
            if reason not in regime["reasons"]:
                regime["reasons"].append(reason)
            # The ledger keeps the exact failure for the operator; before 2026-10-02 the
            # cause was dropped here and a sat-out day could not be explained afterwards.
            try:
                core._ledger({"kind": "news_unavailable", "day": day,
                              "why": str(exc) or type(exc).__name__,
                              "detail": getattr(exc, "detail", None)})
            except Exception:
                pass
            _record_health("news", "Company news", "error",
                           "Company news could not be verified completely; adaptive entries are paused.",
                           "Check the market data connection and retry the decision.")
            audit_rows.append({"symbol": "*", "tier": "news", "survives": False,
                               "case_against_strength": "specific", "why": reason})
            return [], audit_rows, regime

    # Deal rule: its own fetch and budget AFTER the earnings fetch; it never sits the day out.
    if not config.DEAL_RULE:
        deals = {}
    elif deals_injected:
        deals = dict(deals)
    elif earnings_injected:
        deals = {}
    else:
        try:
            shorts = [c.get("symbol") for c in cards if c.get("direction") == "short"]
            deals, _complete = fetch_deal_headlines(shorts, _freeze_dt(day, freeze_time))
        except Exception:
            deals, _complete = {}, False
            _record_health("deal_news", "Deal news", "warning",
                           "Deal news could not be read completely; shorts not already blocked trade as normal.",
                           "Check the relay news proxy.")
        regime["deal_news_complete"] = bool(_complete)
        _DEAL_BLOCKED.setdefault(str(day), {}).update(deals)
        for sym, row in _sticky_deal_blocks(day).items():
            deals.setdefault(sym, row)

    candidates = []

    # Flow rule 3 (macro veto): one relay call for the whole board. A pick against SPY or its sector ETF
    # is dropped here, before ranking, so its slot can go to another name; core.execute() re-checks.
    macro_why = {}
    if config.MACRO_RULE and cards:
        from . import flow
        try:
            macro_now = core.now_et() if str(day) == core.today() else _freeze_dt(day, freeze_time)
        except Exception:
            macro_now = core.now_et()
        macro_why = flow.macro_refusals(
            [{"symbol": c.get("symbol", ""), "direction": c.get("direction")} for c in cards], now=macro_now)

    # JhoshuaStraddle: an account that cannot short skips shorts HERE, after the regime check has
    # already read the whole board's short share, so the best long can still be pick 1.
    skip_shorts = core.long_only()
    for c in cards:
        sym = c.get("symbol", "")
        if skip_shorts and c.get("direction") == "short":
            audit_rows.append({"symbol": sym, "tier": "structure", "survives": False,
                "case_against_strength": "specific", "why": "Long-only account (cannot short)"})
            continue
        if config.CANDLE_RULE:
            why = signals.candle_refusal(c)
            if why:
                audit_rows.append({"symbol": sym, "tier": "structure", "survives": False,
                    "case_against_strength": "specific", "why": "Candle rule: " + why})
                continue
        flow_why = __import__(__package__ + ".flow", fromlist=["flow_refusal"]).flow_refusal(c)
        if flow_why:
            audit_rows.append({"symbol": sym, "tier": "structure", "survives": False,
                "case_against_strength": "specific", "why": "Flow rule: " + flow_why})
            continue
        if config.MACRO_RULE and macro_why.get(sym, "no macro verdict"):
            audit_rows.append({"symbol": sym, "tier": "structure", "survives": False,
                "case_against_strength": "specific", "why": "Macro veto: " + macro_why.get(sym, "no macro verdict")})
            continue
        deal = deals.get(str(sym).upper()) if c.get("direction") == "short" else None
        if deal:
            audit_rows.append({"symbol": sym, "tier": "structure", "survives": False,
                "case_against_strength": "specific",
                "why": f"Deal rule: company announced a new deal {str(deal.get('ts', ''))[-5:]} "
                       f"'{str(deal.get('headline', ''))[:80]}'",
                "deal": {"ts": deal.get("ts", ""), "headline": str(deal.get("headline", ""))[:140]}})
            continue
        e_data = earnings.get(sym)
        if e_data:
            age = _num(e_data.get("hours_ago"))
            if age is None or not 0 <= age <= 48:
                e_data = None
        if e_data and e_data.get("catalyst", {}).get("tier") == "T3" and c.get("direction") == "long":
            audit_rows.append({"symbol": sym, "tier": "structure", "survives": False,
                "case_against_strength": "specific", "why": "Dilutive offering vetoes a long entry"})
            continue

        # Microstructure validation
        micro_ok, micro_info = evaluate_microstructure(c)
        if not micro_ok:
            audit_rows.append({
                "symbol": sym,
                "tier": "structure",
                "survives": False,
                "case_against_strength": "specific",
                "why": micro_info
            })
            continue

        cat_tier = "structure"
        cat_summary = ""
        is_earnings = False
        reprice = False

        if e_data:
            cat_grade = e_data.get("result")
            is_long = c.get("direction") == "long"
            if (cat_grade == "beat" and is_long) or (cat_grade == "miss" and not is_long):
                cat_tier = "earnings"
                is_earnings = True
                cat_summary = f"Reported {e_data['hours_ago']}h ago, {cat_grade} agrees with {c['direction']}"
            elif (cat_grade == "beat" and not is_long):
                gap = _num(c.get("gap_pct"), 0.0)
                if gap >= earn_reprice_gap:
                    cat_tier = "earnings"
                    is_earnings = True
                    reprice = True
                    cat_summary = f"Reported {e_data['hours_ago']}h ago, beat but fading gap +{gap:.1f}%"

        # Enforce contract requirement: earnings pick must have drift > -0.5%
        drift = _num(c.get("drift_pct"))
        if is_earnings and drift is not None and drift <= -0.5:
            audit_rows.append({
                "symbol": sym,
                "tier": "earnings",
                "survives": False,
                "case_against_strength": "specific",
                "why": f"drift {drift:.2f}% <= -0.5% floor (contract required)"
            })
            continue

        if not is_earnings:
            # Check if there is a confirmed non-earnings catalyst (T2 contract/FDA, T4 guidance)
            has_valid_cat = False
            if e_data:
                cat_obj = e_data.get("catalyst", {})
                c_grade = cat_obj.get("grade")
                is_l = c.get("direction") == "long"
                if (c_grade == "positive" and is_l) or (c_grade == "raised" and is_l) or (c_grade == "lowered" and not is_l):
                    has_valid_cat = True
                    cat_summary = f"Catalyst [{e_data['tier']}]: {e_data.get('headline', '')[:80]} | RVOL {micro_info['rvol']:.1f}x"

            if not has_valid_cat:
                if micro_info["drift_r"] < 0:
                    audit_rows.append({"symbol": sym, "tier": "structure", "survives": False,
                        "case_against_strength": "specific", "why": "Failed gap no longer holds its trigger"})
                    continue
                gap = _num(c.get("gap_pct"), 0.0)
                against = -gap * (1 if c.get("direction") == "long" else -1)
                if against < ADAPTIVE_CONFIG["MIN_GAP_REAL"]:
                    audit_rows.append({
                        "symbol": sym,
                        "tier": "structure",
                        "survives": False,
                        "case_against_strength": "specific",
                        "why": f"gap {gap:+.1f}% is not a real failed gap"
                    })
                    continue
                if sym in MEGA:
                    audit_rows.append({
                        "symbol": sym,
                        "tier": "structure",
                        "survives": False,
                        "case_against_strength": "specific",
                        "why": "mega-cap trillion-dollar name barred from failed gap"
                    })
                    continue
                cat_summary = f"Failed gap {gap:+.1f}%, RVOL {micro_info['rvol']:.1f}x, ATR {micro_info['atr_pct']:.1f}%, drift {micro_info['drift_r']*100:.0f}%"

        cat_for_utility = dict(e_data) if e_data else {}
        if reprice:
            cat_for_utility["reprice"] = True
        utility_metrics = compute_bayesian_utility(c, micro_info, cat_for_utility, regime)

        candidates.append({
            "card": c,
            "symbol": sym,
            "direction": c.get("direction"),
            "tier": cat_tier,
            "sector": SECTOR_MAP.get(sym, "OTHER"),
            "reason": cat_summary,
            "reprice": reprice,
            "hours_ago": e_data.get("hours_ago") if e_data else None,
            "earnings_found": is_earnings,
            "direction_aligned": is_earnings and not reprice,
            "micro": micro_info,
            "utility": utility_metrics
        })

    candidates.sort(key=lambda x: -x["utility"]["utility"])

    selected_picks = []
    first_hurdle = ADAPTIVE_CONFIG["CASH_HURDLE_EV"]
    candidates = sorted(candidates, key=lambda x: -x["utility"]["utility"])
    eligible = [c for c in candidates if c["utility"]["ev_dollars"] >= first_hurdle
                and c["utility"]["p_win"] >= ADAPTIVE_CONFIG["MIN_WIN_PROB"] and c["utility"]["utility"] > 0]
    # ADT edit: exclude_symbols leave the pick pool here, after the board and the regime were judged, so the
    # next eligible candidate is promoted to pick 1 / pick 2. An empty set is the exact ORBStraddle behaviour.
    excluded_syms = {str(s).upper() for s in (getattr(config, "EXCLUDE_SYMBOLS", ()) or ())}
    if excluded_syms:
        eligible = [c for c in eligible if c["symbol"] not in excluded_syms]
    if (eligible and ADAPTIVE_CONFIG["MAX_DAILY_PICKS"] >= 1 and
        eligible[0]["utility"]["ev_dollars"] >= first_hurdle):
        pick1 = eligible[0]
        selected_picks.append(pick1)

        if (len(eligible) > 1 and
            ADAPTIVE_CONFIG["MAX_DAILY_PICKS"] >= 2):

            p1_sector = pick1["sector"]
            for cand in eligible[1:]:
                # Sector diversification: reject same sector, and reject if both are unclassified "OTHER"
                if cand["sector"] != p1_sector and "OTHER" not in (cand["sector"], p1_sector):
                    if (cand["utility"]["ev_dollars"] >= ADAPTIVE_CONFIG["SECOND_PICK_HURDLE_EV"] and
                        cand["utility"]["utility"] > 0):
                        selected_picks.append(cand)
                        break

    chosen_syms = {p["symbol"] for p in selected_picks}
    final_picks = []

    for cand in candidates:
        sym = cand["symbol"]
        is_chosen = sym in chosen_syms

        row = {
            "symbol": sym,
            "tier": cand["tier"],
            "survives": is_chosen,
            "case_against_strength": "weak" if is_chosen else "specific",
            "why": cand["reason"] if is_chosen else (cand["reason"] + " | Not selected: excluded_symbol" if sym in excluded_syms else cand["reason"] + " | Not selected: EV/probability/utility hurdle, rank, pick cap, or sector constraint"),
            "utility": cand["utility"]["utility"],
            "ev_dollars": cand["utility"]["ev_dollars"],
            "win_prob": cand["utility"]["p_win"],
            "sector": cand["sector"]
        }

        if cand["tier"] == "earnings":
            row["earnings_found"] = cand["earnings_found"]
            row["direction_aligned"] = cand["direction_aligned"]
            row["hours_ago"] = cand["hours_ago"]
            if cand["reprice"]:
                row["reprice"] = True

        audit_rows.append(row)

        if is_chosen:
            p_dict = {
                "symbol": sym,
                "direction": cand["direction"],
                "tier": cand["tier"],
                "catalyst_summary": (
                    f"{cand['reason']} | EV: +${cand['utility']['ev_dollars']:.0f} "
                    f"({cand['utility']['win_prob']*100:.0f}% model estimate; uncalibrated, per $1k risk) | Sector: {cand['sector']}"
                )
            }
            if cand.get("reprice"):
                p_dict["reprice"] = True
            final_picks.append(p_dict)

    return final_picks, audit_rows, regime

# =====================================================================
# SECTION 6: Reply Text Formatter for core.validate & Autopilot
# =====================================================================

def reply_text(cards, day=None, when=None, earnings=None,
               spy_slope=None, qqq_slope=None, earn_reprice_gap=None):
    """Formats the adaptive decision into the exact JSON contract expected by core.validate."""
    day = day or core.today()
    when = when or config.FREEZE_ET

    picks, audit_rows, regime = select_adaptive(
        cards, day=day, freeze_time=when, earnings=earnings,
        spy_slope=spy_slope, qqq_slope=qqq_slope,
        earn_reprice_gap=earn_reprice_gap)

    is_pass = len(picks) == 0
    note = None
    if is_pass:
        note = f"Adaptive Engine PASSED ({regime['classification']}: {'; '.join(regime['reasons']) if regime['reasons'] else 'no candidate cleared EV hurdle'})"

    reply_obj = {
        "date": day,
        "pass": is_pass,
        "picks": picks,
        "audit": audit_rows,
        "regime": regime,
        "estimate_basis": "Uncalibrated heuristic; EV per $1,000 reference risk",
        "engine": ADAPTIVE_VERSION
    }

    return json.dumps(reply_obj, indent=2), note
