# Copied from ORBStraddle flow.py @06ca29f; logic unchanged; edits:
#   1. package-relative import of config
#   2. package-relative lazy import of scanner
#   3. `import core` -> ADT shim (orbs/shim.py: now_et)
#   4. package-relative import of ticks
#   5. package-relative lazy import of adaptive
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
"""Flow rules (docs/FLOW_RULES_PLAN_2026-09-27.md), operator order 2026-09-27, live without a trial.

1. Delta: a break counts only when buyers (long) / sellers (short) have been the aggressors since 09:30.
2. Velocity: a break counts only when trades arrive much faster than normal as it happens.
3. Macro veto: no long while SPY or the sector ETF is falling, no short while either is rising.
4. Absorption exit: once a trade has been +0.5R, exit when the last 30 s of tape turns hard against it.

Rules 1 and 2 run inside both scanner paths (scanner.scan_symbol and orbproc.SymbolReducer) through the
DeltaState / VelocityState below, so the two paths share one implementation. Rules 3 and 4 fetch from the
relay. Top-level imports stay at config only: adaptive imports core, and core imports this module.
"""
import json, math, urllib.parse, urllib.request
from datetime import datetime, time, timedelta, timezone
from zoneinfo import ZoneInfo

from . import config

ET = ZoneInfo("America/New_York")

# Conditions whose price is not a live aggressor print against the current quote. Volume-only prints
# (the scanner's NOT_PRICE, minus odd lots "I", which ARE real aggressive executions) and auction/cross
# prints: "O" opening prints, "Q" official open, "5" reopening, "6" closing, "X" cross.
# The scanner's BAD set ("W","4","B","C","T") is already dropped before a trade reaches this module.
# "L" late reports, "G" bunched sold and "9" corrected consolidated close: real prints, but not a current
# aggressor against the quote in force.
NOT_AGGRESSOR = {"V", "7", "P", "U", "Z", "H", "M", "N", "O", "Q", "5", "6", "X", "L", "G", "9"}


def _finite(v):
    try:
        v = float(v)
    except (TypeError, ValueError):
        return None
    return v if math.isfinite(v) else None


def delta_eligible(conditions):
    return not (set(conditions or []) & NOT_AGGRESSOR)


def classify(price, bid, ask, last_px, last_side):
    """+1 buy, -1 sell, 0 unclassified. Quote rule first (at/above ask buy, at/below bid sell, above/below
    mid), tick rule at the exact mid (up buy, down sell, unchanged repeats the previous side)."""
    if price is None or bid is None or ask is None or not (0 < bid < ask):
        return 0
    if price >= ask:
        return 1
    if price <= bid:
        return -1
    mid = (bid + ask) / 2.0
    if price > mid:
        return 1
    if price < mid:
        return -1
    if last_px is None:
        return 0
    if price > last_px:
        return 1
    if price < last_px:
        return -1
    return last_side or 0


def delta_pass(direction, ratio):
    if ratio is None:
        return False
    if direction == "long":
        return ratio >= config.DELTA_MIN
    if direction == "short":
        return ratio <= -config.DELTA_MIN
    return False


class DeltaState:
    """Cumulative buy/sell aggressor shares since 09:30. O(1) state."""
    __slots__ = ("buy", "sell", "last_px", "last_side")

    def __init__(self):
        self.buy = 0
        self.sell = 0
        self.last_px = None
        self.last_side = 0

    def add(self, price, size, conditions, quote):
        """quote: the prevailing quote dict (bp/ap) or None. Returns the side it booked."""
        if not delta_eligible(conditions):
            return 0
        price, size = _finite(price), _finite(size)
        if price is None or size is None or price <= 0 or size <= 0:
            return 0
        bid = _finite(quote.get("bp")) if quote else None
        ask = _finite(quote.get("ap")) if quote else None
        side = classify(price, bid, ask, self.last_px, self.last_side)
        if side > 0:
            self.buy += int(size)
        elif side < 0:
            self.sell += int(size)
        if side:
            # the tick rule compares against the previous CLASSIFIED trade only
            self.last_px = price
            self.last_side = side
        return side

    def ratio(self):
        vol = self.buy + self.sell
        return (self.buy - self.sell) / vol if vol > 0 else None

    def to_list(self):
        return [self.buy, self.sell, self.last_px, self.last_side]

    @classmethod
    def from_list(cls, payload):
        st = cls()
        st.buy, st.sell, st.last_px, st.last_side = int(payload[0]), int(payload[1]), payload[2], int(payload[3])
        return st


class VelocityState:
    """Trade counts per whole epoch second, the last WINDOW seconds only."""
    __slots__ = ("counts",)
    WINDOW = 2 + 60 + 2      # burst + base + slack

    def __init__(self):
        self.counts = {}

    def add(self, ts):
        sec = int(ts.timestamp() // 1)
        self.counts[sec] = self.counts.get(sec, 0) + 1
        if len(self.counts) > self.WINDOW:
            floor = sec - self.WINDOW
            for k in [k for k in self.counts if k <= floor]:
                del self.counts[k]

    def measure(self, ts):
        """(burst_trades, ratio) at the trade stamped ts, which must already be added. ratio None = no base."""
        sec = int(ts.timestamp() // 1)
        burst = sum(self.counts.get(sec - i, 0) for i in range(config.VELOCITY_BURST_S))
        base_n = sum(self.counts.get(sec - config.VELOCITY_BURST_S - i, 0) for i in range(config.VELOCITY_BASE_S))
        burst_rate = burst / float(config.VELOCITY_BURST_S)
        base_rate = base_n / float(config.VELOCITY_BASE_S)
        ratio = (burst_rate / base_rate) if base_rate > 0 else None
        return burst, ratio

    def to_list(self):
        return sorted([k, v] for k, v in self.counts.items())

    @classmethod
    def from_list(cls, payload):
        st = cls()
        st.counts = {int(k): int(v) for k, v in payload}
        return st


def velocity_pass(burst, ratio):
    if burst < config.VELOCITY_MIN_TRADES:
        return False
    return ratio is None or ratio >= config.VELOCITY_MIN_RATIO


def entry_rules_on():
    """Rules 1/2 add event and card fields only while at least one of them is on, so both off = the exact
    pre-rule card."""
    return bool(config.DELTA_RULE or config.VELOCITY_RULE)


class CrossState:
    """Rule 2 is judged AS PRICE HITS THE FENCE. An excursion starts on the first print past the fence (the
    previous price-eligible print was inside the range or beyond the other side). Velocity is measured on
    every print of the excursion during its first VELOCITY_BURST_S seconds and the verdict latches as passed
    once any of those prints passes; after that window the verdict is frozen, so a burst later in the same
    excursion cannot rescue a slow grind. A print back inside the range ends the excursion. Only past trades
    are ever counted (no lookahead)."""
    __slots__ = ("long", "short")

    def __init__(self):
        self.long = None      # [crossing_epoch_s, burst, ratio, passed]
        self.short = None

    def update(self, direction, velocity_state, ts):
        """Call on every price-eligible print from 09:35 (direction None = inside). Returns the excursion's
        (burst, ratio) or None when inside."""
        if direction is None:
            self.long = self.short = None
            return None
        other = "short" if direction == "long" else "long"
        setattr(self, other, None)
        now_s = ts.timestamp()
        cur = getattr(self, direction)
        if cur is None:
            burst, ratio = velocity_state.measure(ts)
            cur = [now_s, burst, ratio, velocity_pass(burst, ratio)]
            setattr(self, direction, cur)
        elif not cur[3] and now_s - cur[0] < config.VELOCITY_BURST_S:
            burst, ratio = velocity_state.measure(ts)
            cur[1], cur[2], cur[3] = burst, ratio, velocity_pass(burst, ratio)
        return cur[1], cur[2]

    def refresh(self, velocity_state, ts):
        """Call on EVERY kept trade (odd lots and volume-only prints included) after velocity_state.add: an
        open, unpassed excursion inside its first seconds is re-measured, so an odd-lot burst right after the
        crossing counts. Crossings themselves are only ever started by price-eligible prints (update)."""
        now_s = ts.timestamp()
        for cur in (self.long, self.short):
            if cur is not None and not cur[3] and now_s - cur[0] < config.VELOCITY_BURST_S:
                burst, ratio = velocity_state.measure(ts)
                cur[1], cur[2], cur[3] = burst, ratio, velocity_pass(burst, ratio)

    def to_list(self):
        return [self.long, self.short]

    @classmethod
    def from_list(cls, payload):
        st = cls()
        st.long = list(payload[0]) if payload[0] is not None else None
        st.short = list(payload[1]) if payload[1] is not None else None
        return st


def flow_fields(delta_state, crossing, direction):
    """The event fields both scanner paths add, and the combined pass. crossing = CrossState.update(...)."""
    ratio = delta_state.ratio()
    burst, vratio = crossing
    # The card records what was MEASURED, whatever the switches say, so a card built with one rule off can never
    # carry a stale "passed" into a later run with that rule on; flow_refusal re-judges with the current switches.
    d_meas = delta_pass(direction, ratio)
    v_meas = velocity_pass(burst, vratio)
    ok = (d_meas or not config.DELTA_RULE) and (v_meas or not config.VELOCITY_RULE)
    return {
        "delta_ratio": ratio,
        "delta_buy": delta_state.buy,
        "delta_sell": delta_state.sell,
        "delta_pass": d_meas,
        "burst_trades": burst,
        "velocity_ratio": vratio,
        "velocity_pass": v_meas,
    }, ok


FLOW_CARD_KEYS = ("delta_ratio", "delta_buy", "delta_sell", "burst_trades", "velocity_ratio",
                  "delta_pass", "velocity_pass")


def flow_refusal(card, pick=None):
    """Why a card must NOT trade under rules 1/2, or None. Fail-closed: a card built without the flow fields
    (a pre-deploy snapshot, a hand-built board) or one marked flow_blocked refuses while a rule is on."""
    if not entry_rules_on():
        return None
    card = card or {}
    if card.get("direction") not in ("long", "short"):
        return "card direction unknown (flow rules are on)"
    if pick is not None and pick.get("direction") != card["direction"]:
        return "pick direction differs from its flow-confirmed card"
    if "delta_pass" not in card or "velocity_pass" not in card:
        return "card has no delta/velocity reading (flow rules are on)"
    if card.get("flow_blocked"):
        if (card.get("delta_pass") is True or not config.DELTA_RULE) and \
                (card.get("velocity_pass") is True or not config.VELOCITY_RULE):
            return None     # this card's own break passes every flow rule that is on NOW (a switch went off)
        bits = []
        if config.DELTA_RULE and card.get("delta_pass") is not True:
            r = card.get("delta_ratio")
            bits.append("delta " + (f"{r:+.2f}" if isinstance(r, (int, float)) else "unknown")
                        + f" not {'+' if card.get('direction') == 'long' else '-'}{config.DELTA_MIN:.2f} its way")
        if config.VELOCITY_RULE and card.get("velocity_pass") is not True:
            bits.append(f"no trade-speed spike at the fence ({card.get('burst_trades')} trades in "
                        f"{config.VELOCITY_BURST_S}s)")
        return "no break passed the flow rules" + (": " + "; ".join(bits) if bits else "")
    if config.DELTA_RULE and card.get("delta_pass") is not True:
        return "delta did not confirm the break"
    if config.VELOCITY_RULE and card.get("velocity_pass") is not True:
        return "no trade-speed spike at the fence"
    return None


# ---------------------------------------------------------------------------------------------------------
# Relay access (rules 3 and 4)
# ---------------------------------------------------------------------------------------------------------
def _relay_get(path, params, timeout):
    """One relay read with the shared client: 2 attempts inside a hard deadline, and cache=False, because a
    60-second-old fallback page must never feed a veto or an exit."""
    import time as _t
    from . import scanner
    return scanner.get_relay_client().get(path, params=params, is_meta=False, max_retries=2, cache=False,
                                          deadline=_t.monotonic() + timeout)


def _now():
    from . import shim as core
    return core.now_et()


def _parse_ts(raw):
    from .ticks import _ts as parse_market_timestamp
    return parse_market_timestamp(raw)


# ---- rule 3: macro veto ----------------------------------------------------------------------------------
def sector_of(sym):
    from . import adaptive
    return adaptive.SECTOR_MAP.get(sym)


def fetch_macro_moves(etfs, now=None, bars=None):
    """{etf: move_pct or None}. None = unverified (missing 09:30 bar, stale last bar, bad data).
    bars may be injected ({etf: [bar,...]}) by tests and research."""
    now = (now or _now()).astimezone(ET)
    open_dt = now.replace(hour=9, minute=30, second=0, microsecond=0)
    etfs = sorted(set(etfs))
    out = {e: None for e in etfs}
    if bars is None:
        import time as _t
        deadline = _t.monotonic() + config.MACRO_TIMEOUT_S
        bars = {}
        token = None
        seen = set()
        for _ in range(10):
            left = deadline - _t.monotonic()
            if left <= 0:
                raise TimeoutError("macro bars over their read budget")
            params = {"symbols": ",".join(etfs), "timeframe": "1Min",
                      "start": open_dt.astimezone(timezone.utc).isoformat(),
                      "end": now.astimezone(timezone.utc).isoformat(), "feed": "sip", "limit": 10000}
            if token:
                params["page_token"] = token
            page = _relay_get("/v2/stocks/bars", params, left)
            if _t.monotonic() >= deadline:
                raise TimeoutError("macro bars over their read budget")
            if not isinstance(page, dict) or not isinstance(page.get("bars"), (dict, type(None))):
                raise ValueError("malformed bars page")
            for sym, rows in (page.get("bars") or {}).items():
                bars.setdefault(sym, []).extend(rows or [])
            token = page.get("next_page_token")
            if not token:
                break
            if not isinstance(token, str) or token in seen:
                raise ValueError("repeated or invalid macro page token")
            seen.add(token)
        else:
            raise ValueError("bars pagination exceeded")
    for etf in etfs:
        done = []
        for bar in bars.get(etf) or []:
            try:
                t = _parse_ts(bar["t"]).astimezone(ET)
                o, c = _finite(bar.get("o")), _finite(bar.get("c"))
            except (KeyError, TypeError, ValueError):
                continue
            if o is None or c is None or o <= 0 or c <= 0:
                continue
            if t < open_dt or t + timedelta(minutes=1) > now:
                continue                     # before the open, or the minute is still forming
            done.append((t, o, c))
        done.sort()
        if not done or done[0][0] != open_dt:
            continue
        if (now - (done[-1][0] + timedelta(minutes=1))).total_seconds() > config.MACRO_MAX_STALE_S:
            continue
        out[etf] = (done[-1][2] / done[0][1] - 1.0) * 100.0
    return out


def trend(move_pct):
    move_pct = _finite(move_pct)
    if move_pct is None:
        return None
    if move_pct > config.MACRO_DEADBAND_PCT:
        return "up"
    if move_pct < -config.MACRO_DEADBAND_PCT:
        return "down"
    return "flat"


def macro_etfs(sym):
    sector = sector_of(sym)
    return ["SPY"] + ([sector] if sector else [])


def macro_refusal(sym, direction, moves):
    """Why a pick must NOT trade under the macro veto, or None when it may. Fail-closed on missing data."""
    if direction not in ("long", "short"):
        return "pick direction unknown"
    against = "down" if direction == "long" else "up"
    for etf in macro_etfs(sym):
        t = trend((moves or {}).get(etf))
        if t is None:
            return f"{etf} move since 09:30 could not be verified"
        if t == against:
            return f"{etf} is {t} {moves[etf]:+.2f}% since 09:30, against a {direction}"
    return None


def macro_refusals(picks, now=None, bars=None):
    """{symbol: reason or None} for a batch, one relay call. A fetch failure refuses every pick."""
    etfs = set()
    for p in picks:
        etfs.update(macro_etfs(p["symbol"]))
    if not etfs:
        return {}
    try:
        moves = fetch_macro_moves(etfs, now=now, bars=bars)
    except Exception as exc:
        why = f"sector/SPY bars unavailable ({type(exc).__name__})"
        return {p["symbol"]: why for p in picks}
    return {p["symbol"]: macro_refusal(p["symbol"], p.get("direction"), moves) for p in picks}


# ---- rule 4: absorption exit -----------------------------------------------------------------------------
def _window_rows(kind, sym, start, end, deadline):
    """Every page of a tape window inside ONE absolute monotonic deadline."""
    import time as _t
    rows, token, seen = [], None, set()
    for _ in range(config.ABSORPTION_MAX_PAGES):
        left = deadline - _t.monotonic()
        if left <= 0:
            raise TimeoutError(f"{kind} window over its read budget")
        params = {"start": start.astimezone(timezone.utc).isoformat(),
                  "end": end.astimezone(timezone.utc).isoformat(),
                  "limit": 10000, "feed": "sip", "sort": "asc"}
        if token:
            params["page_token"] = token
        page = _relay_get(f"/v2/stocks/{urllib.parse.quote(sym)}/{kind}", params, min(config.ABSORPTION_TIMEOUT_S, left))
        if not isinstance(page, dict) or not isinstance(page.get(kind), (list, type(None))):
            raise ValueError(f"malformed {kind} page")
        rows.extend(page.get(kind) or [])
        token = page.get("next_page_token")
        if not token:
            return rows
        if not isinstance(token, str) or token in seen:
            raise ValueError("repeated page token")
        seen.add(token)
    raise ValueError(f"{kind} window needs more than {config.ABSORPTION_MAX_PAGES} pages")


def window_delta(trades, quotes, start=None, end=None, quote_start=None):
    """(ratio, classified_trades) for a tape window, the same classifier as the entry rule. Only trades stamped
    inside [start, end] with a positive price and size count; quotes must be positive and not crossed, and no
    later than end. Anything the relay returns outside the window is ignored, never classified."""
    BAD = {"W", "4", "B", "C", "T"}
    ev = []
    for q in quotes or []:
        try:
            bp, ap = _finite(q.get("bp")), _finite(q.get("ap"))
            key = _parse_key(q["t"])
            if (end is not None and key[0] > end) or (quote_start is not None and key[0] < quote_start):
                continue
            if bp and ap and 0 < bp < ap:
                ev.append((key, 1, "q", q))
        except (KeyError, TypeError, ValueError, AttributeError):
            continue
    for t in trades or []:
        try:
            if set(t.get("c") or []) & BAD:
                continue
            p, sz = _finite(t.get("p")), _finite(t.get("s"))
            if p is None or sz is None or p <= 0 or sz <= 0:
                continue
            key = _parse_key(t["t"])
            if (start is not None and key[0] < start) or (end is not None and key[0] > end):
                continue
            ev.append((key, 0, "t", t))
        except (KeyError, TypeError, ValueError, AttributeError):
            continue
    ev.sort(key=lambda r: (r[0], r[1]))
    st, quote, n = DeltaState(), None, 0
    for _k, _p, kind, row in ev:
        if kind == "q":
            quote = row
        elif st.add(row.get("p"), row.get("s"), row.get("c"), quote):
            n += 1
    return st.ratio(), n


def _parse_key(raw):
    from .ticks import _ts_key
    return _ts_key(raw)


def absorption_check(sym, direction, now=None, trades=None, quotes=None):
    """{'fire': bool, 'ratio', 'trades', 'error'}. Never raises. trades/quotes may be injected. Both reads
    share one absolute deadline (ABSORPTION_READ_BUDGET_S)."""
    import time as _t
    now = (now or _now()).astimezone(ET)
    start = now - timedelta(seconds=config.ABSORPTION_WINDOW_S)
    deadline = _t.monotonic() + config.ABSORPTION_READ_BUDGET_S
    try:
        if trades is None:
            trades = _window_rows("trades", sym, start, now, deadline)
        quote_start = start - timedelta(seconds=5)   # so the window's first trades have a prevailing quote
        if quotes is None:
            quotes = _window_rows("quotes", sym, quote_start, now, deadline)
        ratio, n = window_delta(trades, quotes, start=start, end=now, quote_start=quote_start)
    except Exception as exc:
        return {"fire": False, "ratio": None, "trades": 0, "error": f"{type(exc).__name__}: {str(exc)[:120]}"}
    fire = False
    if ratio is not None and n >= config.ABSORPTION_MIN_TRADES:
        fire = ratio <= -config.ABSORPTION_DELTA if direction == "long" else ratio >= config.ABSORPTION_DELTA
    return {"fire": bool(fire), "ratio": ratio, "trades": n, "error": None}


_ABS_STATS = {"day": None, "checks": 0, "blind": 0}


def _abs_health(results):
    try:
        day = _now().date().isoformat()
        if _ABS_STATS["day"] != day:
            _ABS_STATS.update(day=day, checks=0, blind=0)
        _ABS_STATS["checks"] += len(results)
        _ABS_STATS["blind"] += sum(1 for r in results.values() if r.get("error"))
        import data_health
        data_health.record("absorption_exit", "Absorption exit", "ok",
                           f"Checked the tape {_ABS_STATS['checks']} times today on trades up +{config.ABSORPTION_ARM_R}R; "
                           f"{_ABS_STATS['blind']} checks could not read the tape in time and were skipped.")
    except Exception:
        pass


def _absorption_worker(sym, direction, now):
    res = absorption_check(sym, direction, now)
    _abs_health({sym: res})
    return res


def fresh_read(res, now):
    """True only for a read whose window ended at most ABSORPTION_MAX_RESULT_AGE_S before now. Checked again
    right before the supervisor acts, because an earlier exit in the same pass can take seconds."""
    asof = (res or {}).get("asof")
    if asof is None:
        return False
    age = (now - asof).total_seconds()
    return 0 <= age <= config.ABSORPTION_MAX_RESULT_AGE_S


class AbsorptionReader:
    """Background tape reads for the absorption exit. The supervisor NEVER waits on the tape: request() only
    schedules a read (one per symbol in flight, a bounded pool of workers) and take_fresh() hands back the
    reads that have already finished, dropping any whose window ended more than ABSORPTION_MAX_RESULT_AGE_S
    ago. A read therefore acts on the pass after it was requested (~5 s)."""

    def __init__(self, max_workers=4):
        import threading
        self._lock = threading.Lock()
        self._pool = None
        self._max = max_workers
        self._inflight = {}
        self._done = {}

    def request(self, sym, direction, now=None):
        from concurrent.futures import ThreadPoolExecutor
        now = (now or _now()).astimezone(ET)
        with self._lock:
            if sym in self._inflight:
                return False
            if self._pool is None:
                self._pool = ThreadPoolExecutor(max_workers=self._max, thread_name_prefix="absorption")
            fut = self._pool.submit(_absorption_worker, sym, direction, now)
            self._inflight[sym] = (fut, now, direction)
        fut.add_done_callback(lambda f, s=sym: self._finish(s, f))
        return True

    def _finish(self, sym, fut):
        with self._lock:
            _f, asof, direction = self._inflight.pop(sym, (None, None, None))
            try:
                res = dict(fut.result())
            except Exception as exc:
                res = {"fire": False, "ratio": None, "trades": 0, "error": type(exc).__name__}
            res.update(asof=asof, direction=direction)
            self._done[sym] = res
        # Only publishes. The health write happened on the worker thread (_absorption_worker): when the
        # future is already done, add_done_callback runs this on the CALLER's (supervisor's) thread.

    def take_fresh(self, now=None):
        now = (now or _now()).astimezone(ET)
        out = {}
        with self._lock:
            for sym in list(self._done):
                res = self._done.pop(sym)
                if fresh_read(res, now):
                    out[sym] = res
        return out


ABSORPTION = AbsorptionReader()


def status_sentence():
    on = [name for name, flag in (("delta", config.DELTA_RULE), ("velocity", config.VELOCITY_RULE),
                                  ("macro veto", config.MACRO_RULE), ("absorption exit", config.ABSORPTION_EXIT))
          if flag]
    return ("Flow rules on: " + ", ".join(on) + ".") if on else "Flow rules are all off."
