# Copied from ORBStraddle market.py @71b001f; logic unchanged; edits:
#   1. package-relative import of config, plus the shim that owns the HTTP transport
#   2. HTTP goes through shim.urlopen (default urllib.request.urlopen; injectable for replay)
#   3. package-relative import of ticks
#   4. ORBS_* tunables come from PARITY_MANIFEST.json (config.getenv), never the process environment
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
"""market.py: Hardened, read-only AlpacaRelay client and Market Cards ingestion.
Guaranteed strictly read-only, resilient backoff, 5s timeout ceiling, bounded TTL
cache fallback, and canonical schema validation with >=90% scan coverage.
"""

from datetime import date, datetime, time, timedelta
from email.utils import parsedate_to_datetime
import http.client
import json
import math
import os
import re
import socket
import threading
import time as _t
from typing import Any, Dict, List, Optional, Tuple, Union
import urllib.error
import urllib.parse
import urllib.request
from zoneinfo import ZoneInfo

from . import config
from . import shim

ET = ZoneInfo("America/New_York")
DEFAULT_TIMEOUT_S = 5.0
MAX_QUOTE_AGE_S = 5.0
MAX_PRICE_AGE_S = 60.0
MIN_DEPTH_NOTIONAL = 25000.0
# The long-lived cache exists ONLY to answer "can a recent successful response be reused
# after an error". It must never grow with the bulk historical pages the scanner downloads:
# 250 symbols x pages x scans retained 10.9M rows in September 2026. The bound is small
# because legitimate entries here are latest-price/quote/bar/meta responses, of which there
# are at most a few hundred per session.
MAX_CACHE_ENTRIES = max(16, int(config.getenv("ORBS_RELAY_CACHE_MAX", "256")))
MAX_CACHE_BYTES = max(1024 * 1024, int(config.getenv("ORBS_RELAY_CACHE_BYTES", str(8 * 1024 * 1024))))
MAX_RESPONSE_BYTES = max(1024 * 1024, int(config.getenv("ORBS_RELAY_MAX_BODY_BYTES", str(16 * 1024 * 1024))))
READ_CHUNK_BYTES = 64 * 1024


class ResponseTooLarge(ValueError):
    pass


class ScanMetrics:
    """Thread-safe per-scan counters. The scanner attaches one to the shared RelayClient
    for the duration of a scan and reads it back into the scan health metadata; every
    request/byte/retry the client makes lands here, from any worker thread."""

    def __init__(self):
        self._lock = threading.Lock()
        self.requests = 0
        self.bytes_read = 0
        self.retries = 0
        self.cache_fallbacks = 0
        self.failures = 0

    def add(self, requests=0, bytes_read=0, retries=0, cache_fallbacks=0, failures=0):
        with self._lock:
            self.requests += requests
            self.bytes_read += bytes_read
            self.retries += retries
            self.cache_fallbacks += cache_fallbacks
            self.failures += failures

    def snapshot(self) -> Dict[str, int]:
        with self._lock:
            return {"requests": self.requests, "bytes": self.bytes_read,
                    "retries": self.retries, "cache_fallbacks": self.cache_fallbacks,
                    "failures": self.failures}


class RelayClient:
    """Hardened, strictly read-only HTTP client for AlpacaRelay proxy."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        meta_url: Optional[str] = None,
        token: Optional[str] = None,
        ua: Optional[str] = None,
        timeout: float = DEFAULT_TIMEOUT_S,
    ):
        self._base_url = base_url
        self._meta_url = meta_url
        self._token = token
        self._ua = ua
        self.timeout = min(float(timeout), DEFAULT_TIMEOUT_S)
        # key -> (timestamp, data). The dict stays directly assignable (tests seed it), but
        # every read/write INSIDE the client goes through the locked helpers below, because
        # _get is called from up to 24 scan worker threads at once.
        self._cache: Dict[Tuple[str, str], Tuple[float, Any]] = {}
        self._cache_lock = threading.Lock()
        # Parallel accounting avoids serializing every retained payload on every insert.
        # Directly seeded legacy tuples are sized lazily when the next write prunes them.
        self._cache_sizes: Dict[Tuple[str, str], int] = {}
        self._cache_expiries: Dict[Tuple[str, str], float] = {}
        self.metrics: Optional[ScanMetrics] = None   # scanner attaches a per-scan sink

    # ---- bounded, expiring, thread-safe cache ----------------------------------------------
    def _ttl(self, is_meta: bool) -> float:
        return 3600.0 * 8 if is_meta else 60.0

    def _cache_lookup(self, key, is_meta: Optional[bool] = None) -> Optional[Tuple[float, Any]]:
        with self._cache_lock:
            ent = self._cache.get(key)
            if ent is None:
                return None
            # A directly seeded (timestamp, payload) tuple has no side metadata; use the
            # request's legacy TTL in that case. Entries written by get() carry their own.
            ttl = self._cache_expiries.get(key)
            if ttl is None and is_meta is not None:
                ttl = self._ttl(is_meta)
            if ttl is not None and _t.time() - ent[0] > ttl:
                self._cache.pop(key, None)
                self._cache_sizes.pop(key, None)
                self._cache_expiries.pop(key, None)
                return None
            return ent

    def _cache_store(self, key, data: Any, is_meta: bool = False) -> None:
        """Store a bounded response with the TTL for its request kind."""
        try:
            payload_bytes = self._payload_bytes(data)
        except Exception:
            payload_bytes = MAX_CACHE_BYTES + 1
        if payload_bytes > MAX_CACHE_BYTES:
            return
        now = _t.time()
        with self._cache_lock:
            self._cache[key] = (now, data)
            self._cache_sizes[key] = payload_bytes
            self._cache_expiries[key] = self._ttl(is_meta)
            total_bytes = 0
            for k, (ts, value) in list(self._cache.items()):
                ttl = self._cache_expiries.get(k, self._ttl(False))
                if now - ts > ttl:
                    del self._cache[k]
                    self._cache_sizes.pop(k, None)
                    self._cache_expiries.pop(k, None)
                    continue
                size = self._cache_sizes.get(k)
                if size is None:
                    size = self._payload_bytes(value)
                    self._cache_sizes[k] = size
                total_bytes += size
            while len(self._cache) > MAX_CACHE_ENTRIES or total_bytes > MAX_CACHE_BYTES:
                oldest = min(self._cache, key=lambda k: self._cache[k][0])
                del self._cache[oldest]
                total_bytes -= self._cache_sizes.pop(oldest, 0)
                self._cache_expiries.pop(oldest, None)

    def _cache_fallback(self, key, is_meta: bool) -> Tuple[bool, Any]:
        """The one permitted reuse: a RECENT successful response, only after fresh attempts
        failed. Stale entries are never served."""
        ent = self._cache_lookup(key, is_meta)
        if ent is None:
            return False, None
        if self.metrics: self.metrics.add(cache_fallbacks=1)
        return True, ent[1]

    @property
    def base_url(self) -> str:
        return (self._base_url or config.getenv("ORBS_RELAY_BASE") or config.RELAY_DATA).rstrip("/")

    @base_url.setter
    def base_url(self, val: str):
        self._base_url = val

    @property
    def meta_url(self) -> str:
        return (self._meta_url or config.RELAY_META).rstrip("/")

    @meta_url.setter
    def meta_url(self, val: str):
        self._meta_url = val

    @property
    def token(self) -> str:
        return self._token or config.getenv("ORBS_RELAY_TOKEN") or config.RELAY_TOKEN

    @token.setter
    def token(self, val: str):
        self._token = val

    @property
    def ua(self) -> str:
        return self._ua or config.RELAY_UA

    @ua.setter
    def ua(self, val: str):
        self._ua = val

    def _headers(self) -> Dict[str, str]:
        return {
            "X-Relay-Token": self.token,
            "User-Agent": self.ua,
            "Accept": "application/json",
        }

    @staticmethod
    def _payload_bytes(data: Any) -> int:
        try:
            return len(json.dumps(data, separators=(",", ":"), ensure_ascii=False).encode("utf-8"))
        except (TypeError, ValueError, OverflowError):
            return len(repr(data).encode("utf-8"))

    def _read_body(self, resp, deadline: float) -> bytes:
        """Read a bounded body in chunks, applying the same monotonic deadline to reads."""
        expected = None
        try:
            headers = getattr(resp, "headers", None)
            raw_length = headers.get("Content-Length") if headers else None
            if raw_length is not None:
                expected = int(raw_length)
                if expected < 0:
                    raise ValueError("negative Content-Length")
                if expected > MAX_RESPONSE_BYTES:
                    raise ResponseTooLarge("Relay response exceeds body byte limit")
        except (TypeError, ValueError):
            if raw_length is not None:
                raise ValueError("invalid Content-Length")
        # urllib's HTTPResponse exposes read1; test doubles and BytesIO commonly expose
        # only read. Restrict read1 to the real response type so an unconfigured mock's
        # truthy read1 attribute cannot create an endless zero-byte loop.
        reader = resp.read1 if isinstance(resp, http.client.HTTPResponse) else resp.read
        chunks = []
        total = 0
        while True:
            remaining = deadline - _t.monotonic()
            if remaining <= 0:
                raise socket.timeout("Relay response body deadline exceeded")
            sock = getattr(getattr(getattr(resp, "fp", None), "raw", None), "_sock", None)
            if sock is not None:
                try: sock.settimeout(min(self.timeout, remaining))
                except (AttributeError, OSError, OverflowError): pass
            amount = min(READ_CHUNK_BYTES, MAX_RESPONSE_BYTES - total + 1)
            # Both HTTPResponse.read1 and HTTPResponse.read accept a byte amount. Do not
            # fall back to an unbounded read: that defeats MAX_RESPONSE_BYTES and the
            # monotonic deadline for a slow or malicious body.
            try:
                chunk = reader(amount)
            except http.client.IncompleteRead as exc:
                if self.metrics:
                    self.metrics.add(bytes_read=len(exc.partial))
                raise
            if not isinstance(chunk, (bytes, bytearray)):
                raise ValueError("Relay response reader returned a non-byte value")
            if isinstance(chunk, bytearray):
                chunk = bytes(chunk)
            if not chunk:
                break
            total += len(chunk)
            if self.metrics:
                self.metrics.add(bytes_read=len(chunk))
            if total > MAX_RESPONSE_BYTES:
                raise ResponseTooLarge("Relay response exceeds body byte limit")
            chunks.append(chunk)
            if expected is not None and total >= expected:
                break
        if expected is not None and total != expected:
            raise http.client.IncompleteRead(b"".join(chunks), expected - total)
        return b"".join(chunks)

    def _cache_put(self, cache_store, key, data, now):
        """Bound a caller-owned fallback dict using the same entry/byte policy."""
        if RelayClient._payload_bytes(data) > MAX_CACHE_BYTES:
            return
        # A bulk scanner opts out entirely. For the retained compatibility API, serialize
        # callers through this client's lock and account sizes once per entry.
        with self._cache_lock:
            sizes = {k: RelayClient._payload_bytes(v[1]) for k, v in cache_store.items()}
            cache_store[key] = (now, data)
            sizes[key] = RelayClient._payload_bytes(data)
            total_bytes = 0
            for k, (ts, _) in list(cache_store.items()):
                if now - ts > self._ttl(False):
                    del cache_store[k]
                    sizes.pop(k, None)
                    continue
                total_bytes += sizes[k]
            while len(cache_store) > MAX_CACHE_ENTRIES or total_bytes > MAX_CACHE_BYTES:
                oldest = min(cache_store, key=lambda k: cache_store[k][0])
                del cache_store[oldest]
                total_bytes -= sizes.pop(oldest, 0)

    def get(
        self,
        path: str,
        params: Optional[Dict[str, Any]] = None,
        is_meta: bool = False,
        max_retries: int = 3,
        cache: bool = True,
        cache_store: Optional[Dict[Tuple[str, str], Tuple[float, Any]]] = None,
        deadline: Optional[float] = None,
    ) -> Any:
        """Execute strictly read-only HTTP GET with retry backoff and caching.

        cache=True (default) stores the response in the client's small bounded fallback
        cache (metadata/latest-price semantics: TTL 60s market data, 8h meta). Historical
        bulk pages opt out with cache=False, or pass a caller-owned cache_store dict to
        scope retry fallback to one scan: the caller drops the dict when the scan ends and
        nothing outlives it. The cache is only a fallback after fresh attempts fail; a
        successful response is never served without hitting the network first."""
        root = self.meta_url if is_meta else self.base_url
        url = root.rstrip("/") + path
        if params:
            url += "?" + urllib.parse.urlencode(params)

        cache_key = ("GET", url)
        req = urllib.request.Request(url, headers=self._headers(), method="GET")

        if deadline is None:
            # Keep ordinary callers finite too. This covers the request timeout for each
            # allowed attempt plus a bounded amount of normal exponential backoff; a
            # server cannot hold the process forever with an enormous Retry-After value.
            normal_backoff = sum(min(0.5 * (2 ** n), 4.0) for n in range(max(0, max_retries - 1)))
            deadline = _t.monotonic() + max(1, max_retries) * self.timeout + min(normal_backoff, 8.0)
        last_err = None
        for attempt in range(max_retries):
            remaining = deadline - _t.monotonic()
            if remaining <= 0:
                last_err = TimeoutError("Relay request deadline exceeded")
                break
            if self.metrics: self.metrics.add(requests=1)
            try:
                with shim.urlopen(req, timeout=min(self.timeout, remaining)) as resp:
                    raw = self._read_body(resp, deadline)
                    if _t.monotonic() > deadline:
                        raise socket.timeout("Relay response deadline exceeded")
                    data = json.loads(raw.decode("utf-8"))
                    if cache:
                        if cache_store is not None:
                            self._cache_put(cache_store, cache_key, data, _t.time())
                        else:
                            self._cache_store(cache_key, data, is_meta=is_meta)
                    return data
            except urllib.error.HTTPError as e:
                last_err = e
                # Non-retriable client errors
                if e.code in (400, 401, 403, 404, 422):
                    raise
                # Retriable rate limits: honor the server's Retry-After when it sends one.
                if e.code == 429:
                    retry_after = self._retry_after(e)
                    sleep_s = retry_after if retry_after is not None else min(1.5 ** attempt, 5.0)
                    if attempt + 1 >= max_retries or sleep_s > max(0.0, deadline - _t.monotonic()):
                        break
                    self._sleep_retry(sleep_s)
                    continue
                # Retriable server glitches
                if e.code in (500, 502, 503, 504):
                    retry_after = self._retry_after(e)
                    sleep_s = retry_after if retry_after is not None else min(0.5 * (2 ** attempt), 4.0)
                    if attempt + 1 >= max_retries or sleep_s > max(0.0, deadline - _t.monotonic()):
                        break
                    self._sleep_retry(sleep_s)
                    continue
                raise
            except (urllib.error.URLError, socket.timeout, TimeoutError, ConnectionResetError,
                    http.client.IncompleteRead, http.client.HTTPException,
                    json.JSONDecodeError, UnicodeDecodeError, ResponseTooLarge, ValueError,
                    TypeError) as e:
                # IncompleteRead/truncated bodies and undecodable payloads are provider
                # glitches, not data: retry within the attempt budget like any transport
                # error. A page that never completes raises below; it is never partial.
                last_err = e
                sleep_s = min(0.5 * (2 ** attempt), 4.0)
                if attempt + 1 >= max_retries or sleep_s > max(0.0, deadline - _t.monotonic()):
                    break
                self._sleep_retry(sleep_s)
                continue

        # Check cache fallback (fresh-enough entries only, per request kind TTL)
        if cache:
            if cache_store is not None:
                with self._cache_lock:
                    ent = cache_store.get(cache_key)
                    if ent is not None and _t.time() - ent[0] > self._ttl(is_meta):
                        cache_store.pop(cache_key, None)
                        ent = None
                if ent is not None:
                    if self.metrics: self.metrics.add(cache_fallbacks=1)
                    return ent[1]
            else:
                ok, data = self._cache_fallback(cache_key, is_meta)
                if ok:
                    return data
        if self.metrics: self.metrics.add(failures=1)

        raise RuntimeError(f"Relay fetch failed after {max_retries} attempts: {path} ({last_err})")

    @staticmethod
    def _retry_after(e: urllib.error.HTTPError) -> Optional[float]:
        try:
            raw = e.headers.get("Retry-After") if e.headers else None
            if raw is None:
                return None
            try:
                wait = float(raw)
            except (TypeError, ValueError):
                stamp = parsedate_to_datetime(str(raw))
                if stamp.tzinfo is None:
                    return None
                wait = stamp.timestamp() - _t.time()
            return max(wait, 0.0) if math.isfinite(wait) else None
        except (TypeError, ValueError, OverflowError):
            return None

    def _sleep_retry(self, seconds: float) -> None:
        if self.metrics: self.metrics.add(retries=1)
        _t.sleep(seconds)

    # Strictly prohibit mutating HTTP methods
    def post(self, *args, **kwargs):
        raise PermissionError("AlpacaRelay connection is strictly read-only; mutating requests prohibited")

    def put(self, *args, **kwargs):
        raise PermissionError("AlpacaRelay connection is strictly read-only; mutating requests prohibited")

    def delete(self, *args, **kwargs):
        raise PermissionError("AlpacaRelay connection is strictly read-only; mutating requests prohibited")

    def patch(self, *args, **kwargs):
        raise PermissionError("AlpacaRelay connection is strictly read-only; mutating requests prohibited")

    def get_latest_trade(self, symbol: str) -> Dict[str, Any]:
        """Fetch latest trade print for symbol, validating freshness."""
        path = f"/v2/stocks/{urllib.parse.quote(symbol)}/trades/latest"
        data = self.get(path, params={"feed": "sip"})
        tr = data.get("trade") or {}
        px = float(tr.get("p") or 0.0)
        if not math.isfinite(px) or px <= 0:
            raise RuntimeError(f"no usable price for {symbol}")
        from .ticks import _ts as parse_market_timestamp
        stamp = parse_market_timestamp(tr.get("t") or "")
        now = datetime.now(ET)
        age = (now - stamp.astimezone(ET)).total_seconds()
        if not -5.0 <= age <= MAX_PRICE_AGE_S:
            raise RuntimeError(f"trade print age {age:.1f}s is stale or in the future")
        return {"price": px, "timestamp": stamp, "age_s": age, "size": tr.get("s", 0)}

    def get_latest_quote(self, symbol: str) -> Dict[str, Any]:
        """Fetch latest NBBO quote for symbol, validating depth and freshness."""
        path = f"/v2/stocks/{urllib.parse.quote(symbol)}/quotes/latest"
        data = self.get(path, params={"feed": "sip"})
        url = self.base_url.rstrip("/") + path + "?feed=sip"
        cache_key = ("GET", url)
        ent = self._cache_lookup(cache_key, is_meta=False)
        if ent is not None:
            cache_ts, _ = ent
            cache_age = _t.time() - cache_ts
            if cache_age > MAX_QUOTE_AGE_S:
                raise TimeoutError(f"cached quote age {cache_age:.2f}s exceeds maximum {MAX_QUOTE_AGE_S}s ceiling")
        q = data.get("quote") or {}
        bp, ap = float(q.get("bp") or 0.0), float(q.get("ap") or 0.0)
        bs, as_ = float(q.get("bs") or 0.0), float(q.get("as") or 0.0)
        from .ticks import _ts as parse_market_timestamp
        quote_t = q.get("t")
        if quote_t:
            try:
                stamp = parse_market_timestamp(str(quote_t))
                now = datetime.now(ET)
                age = (now - stamp.astimezone(ET)).total_seconds()
                if 0.0 <= age and age > MAX_QUOTE_AGE_S:
                    raise TimeoutError(f"quote age {age:.2f}s exceeds {MAX_QUOTE_AGE_S}s ceiling")
            except (ValueError, TypeError):
                pass
        return {
            "bid": bp,
            "ask": ap,
            "bid_size": bs,
            "ask_size": as_,
            "depth_bid": bp * bs,
            "depth_ask": ap * as_,
            "quote_at": quote_t,
        }

    def get_bars(
        self,
        symbols: Union[str, List[str]],
        timeframe: str = "1Day",
        start: Optional[str] = None,
        end: Optional[str] = None,
        limit: int = 10000,
    ) -> Dict[str, List[Dict[str, Any]]]:
        """Fetch multi-symbol bars from AlpacaRelay."""
        sym_str = symbols if isinstance(symbols, str) else ",".join(symbols)
        params: Dict[str, Any] = {
            "symbols": sym_str,
            "timeframe": timeframe,
            "limit": limit,
            "feed": "sip",
            "adjustment": "raw",
        }
        if start: params["start"] = start
        if end: params["end"] = end
        data = self.get("/v2/stocks/bars", params=params)
        return data.get("bars") or {}


class MarketCardValidator:
    """Validates and normalizes Market Cards and enforces >=90% scan coverage."""

    TICKER_RE = re.compile(r"^[A-Z][A-Z0-9.]{0,6}$")

    @classmethod
    def validate_card(cls, card: Dict[str, Any]) -> Tuple[bool, str]:
        """Validate single card against canonical 13-field schema and quantitative bounds."""
        try:
            if not isinstance(card, dict):
                return False, "card must be a dictionary"
            sym = str(card.get("symbol", "")).strip().upper()
            if not cls.TICKER_RE.fullmatch(sym):
                return False, f"invalid symbol: {sym}"

            mode = str(card.get("mode", "")).strip().upper()
            if mode not in ("EQUITY", "OPTIONS"):
                return False, f"invalid mode: {mode}"

            # Range geometry
            h_orb = float(card["H_ORB"])
            l_orb = float(card["L_ORB"])
            m_orb = float(card["M_ORB"])
            if not (math.isfinite(h_orb) and math.isfinite(l_orb) and math.isfinite(m_orb)):
                return False, "non-finite range geometry"
            if h_orb <= 0 or l_orb <= 0 or h_orb <= l_orb:
                return False, "inconsistent opening range bounds"
            if abs(m_orb - (h_orb + l_orb) / 2.0) > 0.05:
                return False, "midpoint M_ORB does not match (H+L)/2"

            # ATR
            atr = float(card["ATR"])
            if not math.isfinite(atr) or atr <= 0:
                return False, "invalid ATR"

            # Statistical signals
            rvol = float(card["RVOL"])
            wbr = float(card["WBR"])
            gap = float(card["gap_pct"])
            sofi_z = float(card["sofi_z"])
            if not all(math.isfinite(x) for x in (rvol, wbr, gap, sofi_z)):
                return False, "non-finite signal parameters"
            if rvol < 0.0 or wbr < 0.0:
                return False, "negative RVOL or WBR"

            # Indecision Wick Trap check
            if wbr > 3.5:
                return False, f"indecision wick trap: WBR {wbr:.2f} > 3.5"

            # RVOL floor: >= 1.20 for ETFs, >= 1.40 for single stocks
            is_etf = sym in ("SPY", "QQQ") or mode == "OPTIONS"
            rvol_min = 1.20 if is_etf else 1.40
            if rvol < rvol_min:
                return False, f"RVOL {rvol:.2f} below threshold {rvol_min:.2f}"

            # Pre-market Gap bounds: 0.10% <= |Gap| <= 1.80% for ETFs, 0.20% <= |Gap| <= 4.50% for stocks
            gap_min = 0.10 if is_etf else 0.20
            gap_max = 1.80 if is_etf else 4.50
            if not (gap_min <= abs(gap) <= gap_max):
                return False, f"gap {gap:.2f}% out of bounds [{gap_min:.2f}%, {gap_max:.2f}%]"

            # Depth
            depth_bid = float(card["depth_bid"])
            depth_ask = float(card["depth_ask"])
            if not (math.isfinite(depth_bid) and math.isfinite(depth_ask) and depth_bid >= 0 and depth_ask >= 0):
                return False, "invalid depth notional"
            if depth_bid < MIN_DEPTH_NOTIONAL or depth_ask < MIN_DEPTH_NOTIONAL:
                return False, f"insufficient displayed depth: bid ${depth_bid:.2f}, ask ${depth_ask:.2f} < ${MIN_DEPTH_NOTIONAL:.2f}"

            # Quote freshness
            quote_age_ms = float(card["quote_age_ms"])
            if not math.isfinite(quote_age_ms) or quote_age_ms < 0 or quote_age_ms > 5000.0:
                return False, f"stale or invalid quote age: {quote_age_ms} ms"

            return True, "valid"
        except (KeyError, ValueError, TypeError) as e:
            return False, f"validation error: {e}"

    @classmethod
    def validate_coverage(
        cls,
        meta: Dict[str, Any],
        min_coverage: float = config.MIN_SCAN_COVERAGE,
    ) -> Tuple[bool, float, str]:
        """Assert scan metadata satisfies coverage floor and provenance."""
        if not isinstance(meta, dict):
            return False, 0.0, "scan metadata is not a dictionary"
        today_iso = datetime.now(ET).strftime("%Y-%m-%d")
        if meta.get("day") != today_iso:
            return False, 0.0, f"scan metadata day {meta.get('day')} is not today ({today_iso})"
        if meta.get("end") != config.FREEZE_ET:
            return False, 0.0, f"scan metadata freeze {meta.get('end')} != {config.FREEZE_ET}"
        if meta.get("source") != config.CARD_SOURCE:
            return False, 0.0, f"scan metadata source {meta.get('source')} != {config.CARD_SOURCE}"

        att = meta.get("attempted")
        okc = meta.get("ok")
        failed = meta.get("failed")
        if any(type(x) is not int for x in (att, okc, failed)) or att <= 0 or okc < 0 or failed < 0 or att != okc + failed:
            return False, 0.0, "scan counts are invalid or inconsistent"

        cov = okc / att
        if cov < min_coverage:
            return False, cov, f"scan coverage {cov:.1%} below required {min_coverage:.0%} floor"
        return True, cov, "coverage floor satisfied"


def normalize_card(raw: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize legacy or modern card dictionary into canonical 13-field schema."""
    snap = raw.get("signal_snapshot") or {}
    sym = str(raw.get("symbol") or "").strip().upper()

    # Mode: broad index ETFs default to OPTIONS, stocks to EQUITY
    mode = str(raw.get("mode") or "").strip().upper()
    if not mode:
        mode = "OPTIONS" if sym in ("SPY", "QQQ", "IWM") else "EQUITY"

    # Extract ORB geometry
    h_orb = raw.get("H_ORB") or raw.get("h_orb") or snap.get("orb_high") or raw.get("orb_high")
    l_orb = raw.get("L_ORB") or raw.get("l_orb") or snap.get("orb_low") or raw.get("orb_low")
    m_orb = raw.get("M_ORB") or raw.get("m_orb")
    if h_orb is not None and l_orb is not None and m_orb is None:
        m_orb = round((float(h_orb) + float(l_orb)) / 2.0, 4)

    # Extract ATR
    atr = raw.get("ATR") or raw.get("atr")
    if atr is None:
        if raw.get("atr_pct") and raw.get("entry"):
            atr = float(raw["entry"]) * (float(raw["atr_pct"]) / 100.0)
        elif snap.get("atr_pct") and raw.get("entry"):
            atr = float(raw["entry"]) * (float(snap["atr_pct"]) / 100.0)
        elif raw.get("entry") and raw.get("stop"):
            atr = abs(float(raw["entry"]) - float(raw["stop"])) / 0.25

    # Extract RVOL, Gap, SOFI
    rvol = raw.get("RVOL") if raw.get("RVOL") is not None else raw.get("rvol")
    if rvol is None:
        rvol = snap.get("rvol")

    gap = raw.get("gap_pct") if raw.get("gap_pct") is not None else snap.get("gap_pct")
    sofi = raw.get("sofi_z") if raw.get("sofi_z") is not None else (raw.get("sofi") if raw.get("sofi") is not None else snap.get("sofi"))

    # Extract Depth
    depth_bid = raw.get("depth_bid")
    depth_ask = raw.get("depth_ask")
    if depth_bid is None and snap.get("bid") is not None and snap.get("bid_size") is not None:
        depth_bid = float(snap["bid"]) * float(snap["bid_size"])
    if depth_ask is None and snap.get("ask") is not None and snap.get("ask_size") is not None:
        depth_ask = float(snap["ask"]) * float(snap["ask_size"])

    # Extract Quote Age
    quote_age_ms = raw.get("quote_age_ms")
    if quote_age_ms is None:
        quote_age_ms = snap.get("quote_age_ms")

    # Extract WBR
    wbr = raw.get("WBR") or raw.get("wbr") or snap.get("wbr")
    if wbr is None and h_orb is not None and l_orb is not None:
        c_open = snap.get("open") or snap.get("opening_price") or snap.get("open_0930")
        c_close = snap.get("close") or snap.get("close_0934") or snap.get("freeze_price")
        if c_open and c_close:
            body = max(abs(float(c_close) - float(c_open)), 0.0005 * float(c_open))
            wbr = (float(h_orb) - float(l_orb)) / max(body, 1e-6)
        else:
            wbr = 1.0  # nominal pass if historical snapshot lacks bar boundaries

    canonical = {
        # 13 Canonical Fields
        "symbol": sym,
        "mode": mode,
        "H_ORB": float(h_orb) if h_orb is not None else None,
        "L_ORB": float(l_orb) if l_orb is not None else None,
        "M_ORB": float(m_orb) if m_orb is not None else None,
        "ATR": float(atr) if atr is not None else None,
        "RVOL": float(rvol) if rvol is not None else None,
        "WBR": float(wbr) if wbr is not None else None,
        "gap_pct": float(gap) if gap is not None else None,
        "sofi_z": float(sofi) if sofi is not None else None,
        "depth_bid": float(depth_bid) if depth_bid is not None else 0.0,
        "depth_ask": float(depth_ask) if depth_ask is not None else 0.0,
        "quote_age_ms": float(quote_age_ms) if quote_age_ms is not None else 0.0,
        # Execution & Legacy Fields
        "direction": raw.get("direction", "long"),
        "entry": raw.get("entry"),
        "stop": raw.get("stop"),
        "trig": raw.get("trig", "09:35:05"),
        "spread_bps": raw.get("spread_bps"),
        "drift_pct": raw.get("drift_pct"),
        "atr_pct": raw.get("atr_pct"),
        "spread_asof": raw.get("spread_asof"),
        "price_asof": raw.get("price_asof"),
        "signal_snapshot": snap,
    }
    return canonical
