# Copied from ORBStraddle orbproc.py @05d370d; logic unchanged; edits:
#   1. package-relative imports (config, flow, signals, ticks)
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
"""Bounded ORB calculations with explicit REST correction reconciliation.

SymbolReducer preserves scanner.scan_symbol mathematics and exact event order. Session
replays a recent 120-second interval from bounded minute anchors and performs full
reconciliation every 300 seconds of scan cutoff advancement. Replacing intervals
preserves equal-timestamp multiplicity and detects amendments/deletions in that range.
Older revisions wait until the next full reconciliation. Restarts rebuild from 09:30;
disk receipts are diagnostic only and never supply trading state. Failed interval
fetches never commit partial state or masquerade as successful same-cutoff refreshes.
"""
import copy
import hashlib
import heapq
import json
import math
import os
import threading
import time as _t
from collections import deque
from concurrent.futures import ThreadPoolExecutor
from datetime import date, datetime, time, timedelta

from . import config
from . import flow
from . import signals
from .ticks import _ts as parse_market_timestamp, _ts_parts

ET = signals.ET
# --- constants mirrored from scanner.py (audit baseline 9ce7834); parity tests assert ---
# --- the two modules agree, so they must move together if the strategy ever changes. ---
BAD = {"W", "4", "B", "C", "T"}
NOT_PRICE = {"I", "V", "7", "P", "U", "Z", "H", "M", "N"}
DEPTH = 25000.0
WIN = 100
Z = 2.0
REST_MAX_STALE_S = 120
REST_MIN_TRADES = 5
REST_MIN_QUOTES = 20
QUOTE_SIZE_SHARES_START = date(2025, 11, 3)
ORB_END = time(9, 35)
DELAY_AFTER = time(9, 35, 5)
SESSION_VERSION = 1


class ScanInputError(ValueError):
    """Raised when a page/interval fetch fails or arrives out of order. The symbol's
    state is left untouched and the wave reports the symbol as failed - never as a
    silently partial input."""


def _finite_positive(value):
    try:
        value = float(value)
        return value if math.isfinite(value) and value > 0 else None
    except (TypeError, ValueError):
        return None


def _push_sofi(state, value):
    window = state["window"]
    if len(window) == window.maxlen:
        old = window.popleft()
        state["sum"] -= old
        state["sum_sq"] -= old * old
    window.append(value)
    state["sum"] += value
    state["sum_sq"] += value * value
    state["last"] = value


def _sofi_snapshot(state):
    count = len(state["window"])
    if count < 10:
        return count, None
    mean = state["sum"] / count
    variance = state["sum_sq"] / count - mean * mean
    if variance <= 0:
        return count, None
    return count, (state["last"] - mean) / math.sqrt(variance)


def _sofi_pass(direction, value):
    if value is None:
        return False
    return value >= Z if direction == "long" else value <= -Z


def _fresh_quote_age(age_ms):
    return age_ms is not None and 0.0 <= age_ms <= 5000.0


def _elapsed_ms(later_key, earlier_key):
    return (
        (later_key[0] - earlier_key[0]).total_seconds() * 1000.0
        + (later_key[1] - earlier_key[1]) / 1e6
    )


def _order_flow_delta(prev, bp, ap, bs, asz):
    """scanner.order_flow_delta transcribed (Cont/Kukanov/Stoikov 2014, eq 2.1)."""
    db = bs if bp > prev["bp"] else (bs - prev["bs"] if bp == prev["bp"] else -prev["bs"])
    da = asz if ap < prev["ap"] else (asz - prev["as"] if ap == prev["ap"] else -prev["as"])
    return db - da


def _new_sofi_state():
    return {"window": deque(maxlen=WIN), "sum": 0.0, "sum_sq": 0.0, "last": 0.0}


def _mask_passes(mask, direction, gates, deep_sofi, all_sofi):
    if mask & 1 and not gates["delay"]:
        return False
    if mask & 2 and not gates["freshness"]:
        return False
    if mask & 4 and not gates["depth"]:
        return False
    if mask & 8:
        value = deep_sofi if mask & 4 else all_sofi
        if not _sofi_pass(direction, value):
            return False
    return True


TRACE_GATES = {"delay": 1, "freshness": 2, "depth": 4, "sofi": 8}
TRACE_MASKS = tuple(range(16))


def merged_events(trade_rows, quote_rows):
    """Merge two already-filtered, already-sorted row iterators into the exact event order
    scanner.scan_symbol builds: exact nanosecond key, trades BEFORE quotes on ties, and
    within-kind ties keep their input order (heapq.merge is stable and trades sort first
    by priority)."""
    trades = ((_ts_key_of(t), 0, parse_market_timestamp(t["t"]), "t", t) for t in trade_rows)
    quotes = ((_ts_key_of(q), 1, parse_market_timestamp(q["t"]), "q", q) for q in quote_rows)
    for key, prio, ts, kind, obj in heapq.merge(trades, quotes, key=lambda row: (row[0], row[1])):
        yield kind, obj, key, ts


def _ts_key_of(row):
    return _ts_parts(row["t"])


class SymbolReducer:
    """Incremental twin of scanner.scan_symbol. Feed raw trade/quote rows (any granularity,
    half-open interval bounds are enforced per copy); read wave results per entry window.

    State retained per symbol is O(1): opening OHLC scalars, two 100-deep SOFI windows,
    first triggers, latest observations, counters. Nothing else - no per-symbol tape.
    """

    def __init__(self, sym, d, session_date=None, trace=False, secondary_start=None):
        self.sym = sym
        self.d = d
        # session_date: the trading session the quote-size era is judged by. Defaults to d.
        self.session = session_date or d
        self.trace = trace
        # The secondary window's first qualifying trigger is tracked independently of the
        # primary one (phase-3 requirement): triggers before this timestamp never fill the
        # secondary slot. The distant default makes the slot behave like the primary one.
        self.secondary_start = secondary_start or datetime(2000, 1, 1, tzinfo=ET)
        self.lo_bound = None          # half-open feed interval, set per wave copy
        self.hi_bound = None
        self.reset()

    def reset(self):
        self.trades_count = 0
        self.quotes_count = 0
        self.vol5 = 0                 # share volume of kept trades before 09:35 (odd lots count)
        self.dv5 = 0.0                # dollar volume of kept trades before 09:35
        self.orb_open = None          # first price-eligible print of the opening range
        self.orb_close = None         # last price-eligible print before 09:35
        self.hi = None
        self.lo = None
        self.newest_px = None         # latest price-eligible trade row (card: freeze price)
        self.newest_q = None          # latest kept quote row
        self.prev = None              # latest quote with all-positive fields (even when shallow)
        self.spread_bps = None
        self.deep_state = _new_sofi_state()
        self.all_state = _new_sofi_state()
        self.trig_primary = None
        self.trig_secondary = None
        # Candle rule: first passing break in the direction the opening candle allows (tracked always,
        # used only when config.CANDLE_RULE is on and not in trace mode).
        self.trig_primary_candle = None
        self.trig_secondary_candle = None
        self.trace_events = []
        self.seen_masks = {"long": set(), "short": set()}
        self.fed = 0
        # Flow rules 1 and 2 (flow.py): aggressor delta since 09:30, per-second trade counts, the velocity
        # verdict of the current excursion past the fence, and the flow trade latches. trig_primary /
        # trig_secondary stay on the old gates: they are the BOARD the regime reads, which must not move.
        self.delta = flow.DeltaState()
        self.velocity = flow.VelocityState()
        self.cross = flow.CrossState()
        self.trig_primary_flow = None
        self.trig_secondary_flow = None

    # ---- feeding -----------------------------------------------------------
    def in_bounds(self, ts):
        if self.lo_bound is not None and ts < self.lo_bound:
            return False
        if self.hi_bound is not None and ts >= self.hi_bound:
            return False
        return True

    def feed_rows(self, trade_rows, quote_rows):
        """Convenience path (tests, offline research): filter+sort both lists exactly like
        scanner.scan_symbol does, merge them in exact event order, and feed."""
        for kind, row, key, ts in merged_events(
                sorted(trade_rows, key=_ts_key_of),
                sorted(quote_rows, key=_ts_key_of)):
            self.feed_event(kind, row, key, ts)

    def feed_event(self, kind, row, key, ts):
        """One event in exact session order. kind is 't' or 'q'; key is the exact
        (datetime, nanoseconds) tuple. Raises on unparseable payloads only via the
        caller's parse; invalid numeric rows are dropped as in scanner.scan_symbol.
        Malformed structures raise so the caller can refuse the symbol."""
        if not self.in_bounds(ts):
            return
        if kind == "t":
            self._trade_row(row, key, ts)
        else:
            self._quote_row(row, key, ts)

    def _trade_row(self, row, event_key, ts):
        size = _finite_positive(row.get("s"))
        price = _finite_positive(row.get("p"))
        if size is None or price is None:
            return
        if set(row.get("c") or []) & BAD:
            return
        self.trades_count += 1
        self.fed += 1
        # Flow state sees every kept trade (odd lots included) BEFORE the trigger check below.
        self.velocity.add(ts)
        self.cross.refresh(self.velocity, ts)
        self.delta.add(row.get("p"), row.get("s"), row.get("c"), self.prev)
        in_orb = ts.time() < ORB_END
        if in_orb:
            self.vol5 += int(row["s"])
            self.dv5 += float(row["p"]) * int(row["s"])
        if set(row.get("c") or []) & NOT_PRICE:
            return                    # real execution, volume-only: never a price decision
        if in_orb:
            if self.orb_open is None:
                self.orb_open = float(row["p"])
            self.orb_close = float(row["p"])
            self.hi = float(row["p"]) if self.hi is None else max(self.hi, float(row["p"]))
            self.lo = float(row["p"]) if self.lo is None else min(self.lo, float(row["p"]))
        self.newest_px = row
        self._trade_event(row, event_key, ts)

    def _quote_row(self, row, event_key, ts):
        bp, ap = _finite_positive(row.get("bp")), _finite_positive(row.get("ap"))
        bs, az = _finite_positive(row.get("bs")), _finite_positive(row.get("as"))
        if None in (bp, ap, bs, az) or not bp < ap:
            return
        if self.session < QUOTE_SIZE_SHARES_START:
            row = dict(row)
            row["bs"] = int(row.get("bs") or 0) * 100
            row["as"] = int(row.get("as") or 0) * 100
        self.quotes_count += 1
        self.fed += 1
        self.newest_q = row
        self._quote_event(row, event_key, ts)

    def _quote_event(self, obj, event_key, ts):
        bp, ap = float(obj.get("bp") or 0), float(obj.get("ap") or 0)
        bs, asz = int(obj.get("bs") or 0), int(obj.get("as") or 0)
        if bp <= 0 or ap <= 0 or bs <= 0 or asz <= 0:
            return
        if bp < ap:
            self.spread_bps = (ap - bp) / ((ap + bp) / 2) * 1e4
        if self.prev is not None:
            avg = (bs + asz) / 2.0
            val = _order_flow_delta(self.prev, bp, ap, bs, asz) / avg if avg else 0.0
            _push_sofi(self.all_state, val)
            if bp * bs >= DEPTH and ap * asz >= DEPTH:
                _push_sofi(self.deep_state, val)
        self.prev = {"bp": bp, "ap": ap, "bs": bs, "as": asz,
                     "ts": ts, "key": event_key, "raw_t": obj["t"]}

    def _trade_event(self, obj, event_key, ts):
        if ts.time() < ORB_END:
            return
        p = float(obj["p"])
        direction = "long" if p > self.hi else "short" if p < self.lo else None
        crossing = self.cross.update(direction, self.velocity, ts)
        if direction is None:
            return
        quote_age_ms = _elapsed_ms(event_key, self.prev["key"]) if self.prev is not None else None
        delay_pass = ts.time() >= DELAY_AFTER
        freshness_pass = _fresh_quote_age(quote_age_ms)
        depth_pass = (
            self.prev is not None
            and self.prev["bp"] * self.prev["bs"] >= DEPTH
            and self.prev["ap"] * self.prev["as"] >= DEPTH
        )
        deep_count, deep_z = _sofi_snapshot(self.deep_state)
        all_count, all_z = _sofi_snapshot(self.all_state)
        gates = {"delay": delay_pass, "freshness": freshness_pass, "depth": depth_pass}
        first_for_masks = []
        if self.trace:
            for mask in TRACE_MASKS:
                if mask in self.seen_masks[direction]:
                    continue
                if _mask_passes(mask, direction, gates, deep_z, all_z):
                    self.seen_masks[direction].add(mask)
                    first_for_masks.append(mask)
        event = {
            "_ts": ts,
            "_key": event_key,
            "trigger_at": str(obj["t"]),
            "direction": direction,
            "entry": p,
            "trigger_spread_bps": self.spread_bps,
            "quote_at": str(self.prev["raw_t"]) if self.prev is not None else None,
            "quote_age_ms": quote_age_ms,
            "bid": self.prev["bp"] if self.prev is not None else None,
            "ask": self.prev["ap"] if self.prev is not None else None,
            "bid_size": self.prev["bs"] if self.prev is not None else None,
            "ask_size": self.prev["as"] if self.prev is not None else None,
            "delay_pass": delay_pass,
            "freshness_pass": freshness_pass,
            "depth_pass": depth_pass,
            "sofi_deep_count": deep_count,
            "sofi_deep_z": deep_z,
            "sofi_deep_pass": _sofi_pass(direction, deep_z),
            "sofi_all_count": all_count,
            "sofi_all_z": all_z,
            "sofi_all_pass": _sofi_pass(direction, all_z),
            "first_for_masks": first_for_masks,
        }
        if first_for_masks:
            self.trace_events.append(event)
        current_pass = (
            delay_pass
            and freshness_pass
            and depth_pass
            and _sofi_pass(direction, deep_z)
        )
        flow_ok = True
        if not self.trace and flow.entry_rules_on():
            # Flow rules 1 and 2 (production only; research trace output stays byte-identical).
            fields, flow_ok = flow.flow_fields(self.delta, crossing, direction)
            event.update(fields)
        if current_pass:
            if self.trig_primary is None:
                self.trig_primary = event
            if self.trig_secondary is None and ts >= self.secondary_start:
                self.trig_secondary = event
            # Independent latch (not nested under the first-trigger latch): the opening range is complete
            # here because every trade event is at or after 09:35 and events arrive in time order.
            if direction == signals.candle_direction(self.orb_open, self.orb_close):
                if self.trig_primary_candle is None:
                    self.trig_primary_candle = event
                if self.trig_secondary_candle is None and ts >= self.secondary_start:
                    self.trig_secondary_candle = event
            # Flow trade latch: old gates + flow rules (+ the candle direction while that rule is on).
            if flow_ok and (not config.CANDLE_RULE
                            or direction == signals.candle_direction(self.orb_open, self.orb_close)):
                if self.trig_primary_flow is None:
                    self.trig_primary_flow = event
                if self.trig_secondary_flow is None and ts >= self.secondary_start:
                    self.trig_secondary_flow = event

    # ---- wave results ------------------------------------------------------
    def wave_result(self, end_dt, adv, prev_close, atr_by_sym, window="primary"):
        """Recompute scan_symbol's output for the state as of end_dt. adv/prev_close/atr
        are the session reference maps; window selects the trigger slot ('primary' is the
        legacy trigger_start=None behaviour, 'secondary' is trigger_start=secondary_start)."""
        trace = self.trace
        if self.newest_px is None:
            return "ERROR"
        adv_v = _finite_positive(adv.get(self.sym) if isinstance(adv, dict) else None)
        prev_c = _finite_positive(prev_close.get(self.sym) if isinstance(prev_close, dict) else None)
        if adv_v is None or prev_c is None:
            return "ERROR"
        newest_trade = parse_market_timestamp(self.newest_px["t"])
        newest_quote = parse_market_timestamp(self.newest_q["t"]) if self.newest_q else None
        minimum_rows_pass = (
            self.trades_count >= REST_MIN_TRADES
            and self.quotes_count >= REST_MIN_QUOTES
        )
        trade_freshness_pass = (end_dt - newest_trade).total_seconds() <= REST_MAX_STALE_S
        quote_freshness_pass = (
            newest_quote is not None
            and (end_dt - newest_quote).total_seconds() <= REST_MAX_STALE_S
        )
        freeze_quality_pass = minimum_rows_pass and trade_freshness_pass and quote_freshness_pass
        quality = {
            "trade_count": self.trades_count,
            "quote_count": self.quotes_count,
            "minimum_rows_pass": minimum_rows_pass,
            "newest_trade_at": str(self.newest_px["t"]),
            "newest_quote_at": str(self.newest_q["t"]) if self.newest_q else None,
            "trade_freshness_pass": trade_freshness_pass,
            "quote_freshness_pass": quote_freshness_pass,
            "freeze_quality_pass": freeze_quality_pass,
        }
        if not trace and not freeze_quality_pass:
            return "ERROR"
        if self.orb_open is None:
            return "ERROR"
        hi, lo, o_orb, c_orb = self.hi, self.lo, self.orb_open, self.orb_close
        geom = signals.analyze_candle_geometry(hi, lo, o_orb, c_orb, o_orb)
        wbr = geom.wbr

        is_etf = self.sym in signals.INDEX_ETFS
        if geom.is_wick_trap:
            if is_etf:
                signals.SESSION_LOCKOUT.trigger_lockout(
                    self.sym, wbr, f"Indecision Wick Trap on {self.sym} (WBR={wbr:.2f} > 3.5)"
                )
            if not trace:
                return None
        if signals.SESSION_LOCKOUT.is_locked() and not trace:
            return None
        trig = self.trig_primary if window == "primary" else self.trig_secondary
        if not trig and not trace:
            return None
        # Candle rule (production only; trace/research output stays byte-identical). `first` is the
        # first break the bot sees (the board direction the regime counts); `trig` becomes the break the
        # bot may trade. No agreeing break -> the card is kept on the board but marked blocked.
        first = trig
        candle_rule = config.CANDLE_RULE and not trace and trig is not None
        candle_blocked = False
        if candle_rule:
            agreeing = self.trig_primary_candle if window == "primary" else self.trig_secondary_candle
            if agreeing is not None:
                trig = agreeing
            else:
                candle_blocked = True
        # Flow rules 1/2: trade the first break that also passed them. None -> card kept on the board (the
        # regime still counts it) but flow_blocked, and the pick step / execute() refuse it.
        flow_rule = flow.entry_rules_on() and not trace and trig is not None
        flow_blocked = False
        if flow_rule:
            passing = self.trig_primary_flow if window == "primary" else self.trig_secondary_flow
            if passing is not None:
                trig = passing
                candle_blocked = False      # the flow latch already required the candle's direction
            else:
                flow_blocked = True
        if trace and not self.trace_events:
            quality["atr_valid"] = bool(_finite_positive(atr_by_sym.get(self.sym)))
            quality["production_result_valid"] = freeze_quality_pass
            quality["research_result_valid"] = freeze_quality_pass
            return {"card": None, "breakouts": [], "quality": quality}
        lastpx = float(self.newest_px["p"])
        rvol = self.dv5 / (adv_v * 5 / 390)
        atr_abs = _finite_positive(atr_by_sym.get(self.sym))
        atr_valid = atr_abs is not None
        quality["atr_valid"] = atr_valid
        quality["production_result_valid"] = freeze_quality_pass and (trig is None or atr_valid)
        quality["research_result_valid"] = (
            freeze_quality_pass and (not self.trace_events or atr_valid)
        )
        if not trace and not atr_valid:
            return "ERROR"
        gap = (o_orb / prev_c - 1) * 100
        buf = 0.25 * atr_abs if atr_valid else None

        def enrich(event):
            direction = event["direction"]
            entry = event["entry"]
            stop = (
                (min(lo - buf, entry * 0.995) if direction == "long"
                 else max(hi + buf, entry * 1.005))
                if buf is not None
                else None
            )
            drift = ((lastpx - entry) / entry * 100 * (1 if direction == "long" else -1))
            return {
                key: value
                for key, value in {
                    **event,
                    "stop": stop,
                    "freeze_price": lastpx,
                    "drift_pct": drift,
                    "gap_pct": gap,
                    "rvol": rvol,
                    "atr_pct": atr_abs / entry * 100 if atr_valid else None,
                    "freeze_spread_bps": self.spread_bps,
                    "orb_high": hi,
                    "orb_low": lo,
                    "orb_width_pct": (hi - lo) / entry * 100.0,
                    "opening_volume": self.vol5,
                    "opening_dollar_volume": self.dv5,
                    "freeze_price_at": str(self.newest_px["t"]),
                }.items()
                if not key.startswith("_")
            }

        card = None
        if trig and quality["production_result_valid"] and not geom.is_wick_trap \
                and not signals.SESSION_LOCKOUT.is_locked():
            exact = enrich(trig)
            dr = exact["direction"]
            entry = exact["entry"]
            stop = exact["stop"]
            drift = exact["drift_pct"]
            z = exact["sofi_deep_z"]
            ts = trig["_ts"]
            trigger_raw_time = exact["trigger_at"]
            mode = "OPTIONS" if is_etf else "EQUITY"
            h_orb = round(hi, 2)
            l_orb = round(lo, 2)
            m_orb = round((hi + lo) / 2.0, 2)
            atr_val = round(atr_abs, 2) if atr_abs is not None else round(entry * (exact["atr_pct"] / 100.0), 2)
            wbr_val = round(wbr, 3)
            sofi_val = round(z, 2) if z is not None else 0.0
            bid_notional = float(exact["bid"] or 0.0) * float(exact["bid_size"] or 0.0)
            ask_notional = float(exact["ask"] or 0.0) * float(exact["ask_size"] or 0.0)
            depth_bid = round(bid_notional, 2)
            depth_ask = round(ask_notional, 2)
            quote_age_ms = round(exact["quote_age_ms"], 1) if exact.get("quote_age_ms") is not None else 0.0
            signal_snapshot = {
                "trigger_at": trigger_raw_time, "entry": entry, "stop": stop,
                "freeze_price": lastpx, "drift_pct": drift, "gap_pct": gap,
                "rvol": rvol, "atr_pct": exact["atr_pct"], "sofi": z,
                "spread_bps": exact["trigger_spread_bps"],
                "bid": exact["bid"], "ask": exact["ask"],
                "bid_size": exact["bid_size"], "ask_size": exact["ask_size"],
                "quote_at": exact["quote_at"],
                "quote_age_ms": exact["quote_age_ms"],
                "orb_high": hi, "orb_low": lo,
                "orb_width_pct": exact["orb_width_pct"],
                "opening_volume": self.vol5, "opening_dollar_volume": self.dv5,
                "freeze_price_at": exact["freeze_price_at"],
                "wbr": wbr_val,
                "midpoint": m_orb,
                "bid_depth": depth_bid,
                "ask_depth": depth_ask,
                "is_wick_trap": geom.is_wick_trap,
            }
            card = {
                "symbol": self.sym,
                "mode": mode,
                "H_ORB": h_orb,
                "L_ORB": l_orb,
                "M_ORB": m_orb,
                "ATR": atr_val,
                "RVOL": rvol,
                "WBR": wbr_val,
                "gap_pct": gap,
                "sofi_z": sofi_val,
                "depth_bid": depth_bid,
                "depth_ask": depth_ask,
                "quote_age_ms": quote_age_ms,
                "h_orb": h_orb,
                "l_orb": l_orb,
                "m_orb": m_orb,
                "wbr": wbr_val,
                "is_wick_trap": geom.is_wick_trap,
                "is_indecision_trap": geom.is_wick_trap,
                "direction": dr,
                "entry": round(entry, 2),
                "stop": round(stop, 2),
                # Decision inputs retain precision; rounding here can cross a refusal threshold.
                "drift_pct": drift,
                "rvol": rvol,
                "atr_pct": exact["atr_pct"],
                "spread_bps": self.spread_bps,
                "sofi": z,
                "trig": ts.strftime("%H:%M:%S"),
                "spread_asof": newest_quote.isoformat(),
                "price_asof": newest_trade.isoformat(),
                "signal_snapshot": signal_snapshot,
            }
            if candle_rule:
                card.update(_candle_fields(o_orb, c_orb, first, candle_blocked))
            if flow_rule:
                card.update(flow_card_fields(exact, first, flow_blocked))
                signal_snapshot.update(flow_card_fields(exact, first, flow_blocked))
        if trace:
            return {"card": card, "breakouts": [enrich(e) for e in self.trace_events],
                    "quality": quality}
        return card

    # ---- copies and checkpoints --------------------------------------------
    def to_dict(self):
        return {
            "trades_count": self.trades_count,
            "quotes_count": self.quotes_count,
            "vol5": self.vol5,
            "dv5": self.dv5,
            "orb_open": self.orb_open,
            "orb_close": self.orb_close,
            "hi": self.hi,
            "lo": self.lo,
            "newest_px": self.newest_px,
            "newest_q": self.newest_q,
            "prev": _prev_to_dict(self.prev),
            "spread_bps": self.spread_bps,
            "deep": [list(self.deep_state["window"]), self.deep_state["sum"], self.deep_state["sum_sq"], self.deep_state["last"]],
            "all": [list(self.all_state["window"]), self.all_state["sum"], self.all_state["sum_sq"], self.all_state["last"]],
            "trig_primary": _event_to_dict(self.trig_primary),
            "trig_secondary": _event_to_dict(self.trig_secondary),
            "trig_primary_candle": _event_to_dict(self.trig_primary_candle),
            "trig_secondary_candle": _event_to_dict(self.trig_secondary_candle),
            "seen_masks": {k: sorted(v) for k, v in self.seen_masks.items()},
            "trace_events": [_event_to_dict(e) for e in self.trace_events],
            "flow": {"delta": self.delta.to_list(), "velocity": self.velocity.to_list(),
                     "cross": self.cross.to_list(),
                     "trig_primary": _event_to_dict(self.trig_primary_flow),
                     "trig_secondary": _event_to_dict(self.trig_secondary_flow)},
        }

    @classmethod
    def from_dict(cls, sym, d, payload, session_date=None, trace=False, secondary_start=None):
        st = cls(sym, d, session_date=session_date, trace=trace, secondary_start=secondary_start)
        st.trades_count = payload.get("trades_count", 0)
        st.quotes_count = payload.get("quotes_count", 0)
        st.vol5 = payload.get("vol5", 0)
        st.dv5 = payload.get("dv5", 0.0)
        st.orb_open = payload.get("orb_open")
        st.orb_close = payload.get("orb_close")
        st.hi = payload.get("hi")
        st.lo = payload.get("lo")
        st.newest_px = payload.get("newest_px")
        st.newest_q = payload.get("newest_q")
        st.prev = _prev_from_dict(payload.get("prev"))
        st.spread_bps = payload.get("spread_bps")
        deep = payload.get("deep") or [[], 0.0, 0.0, 0.0]
        st.deep_state = {"window": deque(deep[0], maxlen=WIN), "sum": deep[1], "sum_sq": deep[2], "last": deep[3]}
        all_ = payload.get("all") or [[], 0.0, 0.0, 0.0]
        st.all_state = {"window": deque(all_[0], maxlen=WIN), "sum": all_[1], "sum_sq": all_[2], "last": all_[3]}
        st.trig_primary = _event_from_dict(payload.get("trig_primary"))
        st.trig_secondary = _event_from_dict(payload.get("trig_secondary"))
        if "trig_primary_candle" not in payload or "trig_secondary_candle" not in payload:
            # A pre-candle-rule payload cannot say which agreeing break was already consumed: refuse it.
            raise ValueError("reducer payload predates the candle rule; rebuild from 09:30")
        st.trig_primary_candle = _event_from_dict(payload.get("trig_primary_candle"))
        st.trig_secondary_candle = _event_from_dict(payload.get("trig_secondary_candle"))
        if "flow" not in payload:
            # A pre-flow-rules payload has no delta/velocity history: refuse it, rebuild from 09:30.
            raise ValueError("reducer payload predates the flow rules; rebuild from 09:30")
        st.delta = flow.DeltaState.from_list(payload["flow"]["delta"])
        st.velocity = flow.VelocityState.from_list(payload["flow"]["velocity"])
        st.cross = flow.CrossState.from_list(payload["flow"]["cross"])
        st.trig_primary_flow = _event_from_dict(payload["flow"].get("trig_primary"))
        st.trig_secondary_flow = _event_from_dict(payload["flow"].get("trig_secondary"))
        st.seen_masks = {k: set(v) for k, v in (payload.get("seen_masks") or {}).items()}
        st.trace_events = [_event_from_dict(e) for e in (payload.get("trace_events") or [])]
        return st

    def copy(self):
        clone = SymbolReducer.from_dict(
            self.sym, self.d, json.loads(json.dumps(self.to_dict())),
            session_date=self.session, trace=self.trace,
            secondary_start=self.secondary_start)
        return clone


def _candle_fields(o_orb, c_orb, first, blocked):
    """Card fields the candle rule adds (shared with scanner.scan_symbol so both paths match)."""
    return {
        "candle": signals.candle_colour(o_orb, c_orb),
        "candle_open": o_orb,
        "candle_close": c_orb,
        "candle_blocked": bool(blocked),
        "board_direction": first["direction"],
        "first_break": {"direction": first["direction"], "entry": first["entry"],
                        "trigger_at": str(first["trigger_at"])},
    }


def flow_card_fields(exact, first, blocked):
    """Card fields the flow rules add (shared with scanner.scan_symbol so both paths match). board_direction
    is the FIRST old-gate break, the direction the regime counts, exactly as the candle rule sets it."""
    out = {k: exact.get(k) for k in flow.FLOW_CARD_KEYS}
    out.update(flow_blocked=bool(blocked), board_direction=first["direction"],
               first_break={"direction": first["direction"], "entry": first["entry"],
                            "trigger_at": str(first["trigger_at"])})
    return out


def _event_to_dict(event):
    if event is None:
        return None
    out = {}
    for k, v in event.items():
        if k == "_ts":
            out["_ts"] = v.isoformat()
        elif k == "_key":
            out["_key"] = [v[0].isoformat(), v[1]]
        else:
            out[k] = v
    return out


def _event_from_dict(payload):
    if not payload:
        return None
    out = dict(payload)
    if out.get("_ts"):
        out["_ts"] = datetime.fromisoformat(out["_ts"])
    if out.get("_key"):
        out["_key"] = (datetime.fromisoformat(out["_key"][0]), int(out["_key"][1]))
    return out


def _prev_to_dict(prev):
    if prev is None:
        return None
    out = dict(prev)
    out["ts"] = prev["ts"].isoformat()
    out["key"] = [prev["key"][0].isoformat(), prev["key"][1]]
    return out


def _prev_from_dict(prev):
    if not prev:
        return None
    out = dict(prev)
    out["ts"] = datetime.fromisoformat(out["ts"])
    out["key"] = (datetime.fromisoformat(out["key"][0]), int(out["key"][1]))
    return out


def fingerprint_for(day, wl, prev_dv, adv_close, atr, primary_start, secondary_start):
    blob = {
        "version": SESSION_VERSION,
        "day": day.isoformat(),
        "universe": sorted(wl),
        "prev_dv": prev_dv,
        "adv_close": adv_close,
        "atr": atr,
        "primary_start": primary_start.strftime("%H:%M:%S"),
        "secondary_start": secondary_start.strftime("%H:%M:%S"),
        "source": "rest",
    }
    return hashlib.sha256(json.dumps(blob, sort_keys=True, default=str).encode()).hexdigest()


class Session:
    POLICY_VERSION = 'rest-reconcile-v2'

    def __init__(self, day, wl, prev_dv, adv_close, atr, primary_start,
                 secondary_start, fetcher, state_dir, correction_horizon_s=900.0,
                 concurrency=24, now_fn=None, clock=None, repair_window_s=120.0,
                 reconcile_interval_s=300.0, source_id='rest:sip'):
        self.day, self.wl = day, list(wl)
        self.prev_dv, self.adv_close, self.atr = map(dict, (prev_dv, adv_close, atr))
        self.primary_start, self.secondary_start = primary_start, secondary_start
        self.fetcher, self.state_dir, self.source_id = fetcher, state_dir, source_id
        values = (correction_horizon_s, repair_window_s, reconcile_interval_s)
        if any(not math.isfinite(float(v)) or float(v) <= 0 for v in values):
            raise ValueError('repair/reconciliation intervals must be finite and positive')
        if not 60 <= float(repair_window_s) <= 900:
            raise ValueError('repair window must be between 60 and 900 seconds')
        self.correction_horizon = timedelta(seconds=float(correction_horizon_s))
        self.repair_window = timedelta(seconds=float(repair_window_s))
        self.reconcile_interval = timedelta(seconds=float(reconcile_interval_s))
        self.concurrency = max(1, min(24, int(concurrency)))
        self._now = now_fn or (lambda: datetime.now(ET))
        self.clock = clock or _t.monotonic
        self.lock = threading.RLock()
        self.reducers, self.watermark, self.anchors, self.full_at = {}, {}, {}, {}
        self.last_end = None
        self.last_failed, self.last_errors, self.last_repairs = set(), {}, {}
        self.last_retried = []
        self.bootstrap_count = 0
        self.checkpoint_error = None
        self.observation_started = self.observation_finished = None
        self._initial_fingerprint = self.fingerprint()

    def fingerprint(self):
        data = dict(policy=self.POLICY_VERSION, day=self.day.isoformat(),
                    universe=self.wl, prev_dv=self.prev_dv, adv_close=self.adv_close,
                    atr=self.atr, primary_start=self.primary_start.isoformat(),
                    secondary_start=self.secondary_start.isoformat(), source=self.source_id,
                    repair_seconds=self.repair_window.total_seconds(),
                    reconcile_seconds=self.reconcile_interval.total_seconds())
        return hashlib.sha256(json.dumps(data, sort_keys=True, default=str).encode()).hexdigest()

    def _reset(self):
        self.reducers.clear()
        self.watermark.clear()
        self.anchors.clear()
        self.full_at.clear()
        self.last_failed.clear()
        self.last_end = None

    def _process_symbol(self, sym, end):
        opened = datetime.combine(self.day, time(9, 30), tzinfo=ET)
        mark, last_full = self.watermark.get(sym), self.full_at.get(sym)
        full = (mark is None or last_full is None or end < mark
                or end - mark > self.correction_horizon
                or end - last_full >= self.reconcile_interval)
        repair_target = max(opened, end - self.repair_window)
        choices = [(stamp, state) for stamp, state in self.anchors.get(sym, [])
                   if stamp <= repair_target]
        if full or not choices:
            start = opened
            state = SymbolReducer(sym, self.day, secondary_start=self.secondary_start)
            full = True
        else:
            start, anchor = max(choices, key=lambda pair: pair[0])
            state = copy.deepcopy(anchor)
        state.secondary_start = self.secondary_start
        state.lo_bound, state.hi_bound = start, end

        # Save only recent minute anchors. Snapshot BEFORE boundary events, so each
        # state describes the exclusive prefix and replay preserves multiplicity.
        boundary = max(start, repair_target.replace(second=0, microsecond=0))
        boundaries = []
        while boundary <= end:
            boundaries.append(boundary)
            boundary += timedelta(minutes=1)
        if not boundaries or boundaries[-1] != end:
            boundaries.append(end)
        fresh_anchors, next_boundary = [], 0
        counts = {'trades': 0, 'quotes': 0}

        def rows(kind):
            previous = None
            for row in self.fetcher(kind, sym, start, end):
                key = _ts_key_of(row)
                if previous is not None and key < previous:
                    raise ScanInputError('%s %s returned unordered rows' % (sym, kind))
                previous = key
                counts[kind] += 1
                yield row

        for kind, row, key, stamp in merged_events(rows('trades'), rows('quotes')):
            while next_boundary < len(boundaries) and boundaries[next_boundary] <= stamp:
                fresh_anchors.append((boundaries[next_boundary], copy.deepcopy(state)))
                next_boundary += 1
            state.feed_event(kind, row, key, stamp)
        while next_boundary < len(boundaries):
            fresh_anchors.append((boundaries[next_boundary], copy.deepcopy(state)))
            next_boundary += 1
        # No shared state is mutated until both iterators have completed.
        return state, fresh_anchors, full, dict(start=start.isoformat(), end=end.isoformat(),
                                               full_reconciliation=full, **counts)

    def advance(self, end_dt, symbols=None):
        with self.lock:
            if end_dt.tzinfo is None or end_dt.astimezone(ET).date() != self.day:
                raise ValueError('scan cutoff must belong to the session and have a timezone')
            end_dt = end_dt.astimezone(ET)
            if end_dt < datetime.combine(self.day, time(9, 30), tzinfo=ET):
                raise ValueError('scan cutoff is before the session open')
            fingerprint = self.fingerprint()
            if fingerprint != self._initial_fingerprint or (self.last_end and end_dt < self.last_end):
                self._reset()
                self._initial_fingerprint = fingerprint
            self.observation_started = self._now().isoformat()
            self.last_failed, self.last_errors, self.last_repairs = set(), {}, {}
            self.last_retried = []
            did_full = False
            selected = set(self.wl if symbols is None else symbols)
            work = [sym for sym in self.wl if sym in selected]
            with ThreadPoolExecutor(self.concurrency) as pool:
                futures = {sym: pool.submit(self._process_symbol, sym, end_dt) for sym in work}
                for sym, future in futures.items():
                    try:
                        state, anchors, full, metrics = future.result()
                    except Exception as exc:
                        self.last_failed.add(sym)
                        self.last_errors[sym] = '%s: %s' % (type(exc).__name__, str(exc)[:160])
                        continue
                    self.reducers[sym], self.anchors[sym] = state, anchors
                    self.watermark[sym] = end_dt
                    self.last_repairs[sym] = metrics
                    if full:
                        self.full_at[sym] = end_dt
                        did_full = True
            self.bootstrap_count += int(did_full)
            self.last_end = end_dt
            self.observation_finished = self._now().isoformat()
            try:
                self.save_checkpoint()
                self.checkpoint_error = None
            except Exception as exc:
                self.checkpoint_error = '%s: %s' % (type(exc).__name__, str(exc)[:160])
            return set(self.last_failed)

    def retry_symbols(self, symbols, end_dt):
        """One lower-concurrency retry requested after the caller evaluates quality.
        Retry only refused symbols; healthy symbols retain their committed state."""
        with self.lock:
            if end_dt != self.last_end:
                raise ValueError('retry cutoff differs from current scan')
            wanted = set(symbols)
            retry = [sym for sym in self.wl if sym in wanted]
            self.last_retried = retry
            with ThreadPoolExecutor(min(4, self.concurrency)) as pool:
                futures = {sym: pool.submit(self._process_symbol, sym, end_dt) for sym in retry}
                for sym, future in futures.items():
                    try:
                        state, anchors, full, metrics = future.result()
                    except Exception as exc:
                        self.last_failed.add(sym)
                        self.last_errors[sym] = '%s: %s' % (type(exc).__name__, str(exc)[:160])
                        continue
                    self.reducers[sym], self.anchors[sym] = state, anchors
                    self.watermark[sym] = end_dt
                    self.last_repairs[sym] = metrics
                    self.last_failed.discard(sym)
                    self.last_errors.pop(sym, None)
                    if full:
                        self.full_at[sym] = end_dt
            self.observation_finished = self._now().isoformat()
            try:
                self.save_checkpoint()
                self.checkpoint_error = None
            except Exception as exc:
                self.checkpoint_error = '%s: %s' % (type(exc).__name__, str(exc)[:160])
            return set(self.last_failed)

    def wave(self, end_dt, window='primary', exclude=None):
        with self.lock:
            if window not in ('primary', 'secondary'):
                raise ValueError('unknown entry window')
            excluded = set(exclude or ())
            cards, outcomes = [], {}
            for sym in self.wl:
                if sym in excluded:
                    continue
                if sym in self.last_failed or self.watermark.get(sym) != end_dt:
                    outcomes[sym] = 'ERROR'
                    continue
                try:
                    result = self.reducers[sym].wave_result(
                        end_dt, self.prev_dv, self.adv_close, self.atr, window=window)
                except Exception as exc:
                    result = 'ERROR'
                    self.last_errors[sym] = '%s: %s' % (type(exc).__name__, str(exc)[:160])
                outcomes[sym] = result
                if isinstance(result, dict):
                    cards.append(result)
            return sorted(cards, key=lambda card: card['trig']), outcomes

    def metadata(self):
        return dict(policy_version=self.POLICY_VERSION, fingerprint=self.fingerprint(),
                    restart_policy='full_rest_bootstrap',
                    repair_window_s=self.repair_window.total_seconds(),
                    reconciliation_interval_s=self.reconcile_interval.total_seconds(),
                    observation_started_at=self.observation_started,
                    observation_finished_at=self.observation_finished,
                    last_full_cutoff={s: t.isoformat() for s, t in self.full_at.items()},
                    repairs=self.last_repairs, failures=self.last_errors,
                    retained_symbols=len(self.reducers),
                    retained_anchors=sum(len(items) for items in self.anchors.values()),
                    retried_symbols=self.last_retried,
                    checkpoint_error=self.checkpoint_error,
                    correction_limit='Older revisions can remain unseen until the next full reconciliation; observations after the final scan are not included.')

    def _checkpoint_path(self):
        return os.path.join(self.state_dir, 'session_scan_%s.json' % self.day.isoformat())

    def save_checkpoint(self):
        """Compact diagnostic receipt only. A restart ALWAYS repairs from 09:30;
        a valid-looking stale/corrupt checkpoint can never supply trading state."""
        os.makedirs(self.state_dir, exist_ok=True)
        payload = dict(day=self.day.isoformat(), last_end=self.last_end.isoformat(),
                       diagnostic_only=True, **self.metadata())
        encoded = json.dumps(payload, allow_nan=False).encode()
        if len(encoded) > 2 * 1024 * 1024:
            raise ValueError('scan receipt exceeded its byte budget')
        path = self._checkpoint_path()
        temp = '%s.%d.%d.tmp' % (path, os.getpid(), threading.get_ident())
        try:
            with open(temp, 'wb') as handle:
                handle.write(encoded)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temp, path)
            # These files contain only our diagnostic receipts, never execution claims.
            from pathlib import Path
            receipts = sorted(Path(self.state_dir).glob('session_scan_????-??-??.json'))
            for old in receipts[:-7]:
                old.unlink(missing_ok=True)
        finally:
            if os.path.exists(temp):
                os.unlink(temp)
