# Copied from ORBStraddle scanner.py @05d370d; logic unchanged; edits:
#   1. package-relative imports (config, flow, market, orbproc, signals, ticks)
#   2. ORBS_* tunables come from PARITY_MANIFEST.json (config.getenv), never the process environment
#   3. `import core` -> ADT shim (status_heartbeat, _ledger, today, _superv_open, _todays)
#   4. package-relative lazy import of session_calendar (deal rule prior-close evidence)
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
"""Full ORB board scanner. Production REST pages feed bounded per-symbol reducers.

Default scans reuse compact session state, replace the recent correction window and
periodically reconcile from 09:30. ORBS_INCREMENTAL=off uses bounded full replay. Bulk
pages never enter a fallback cache. Explicit stream/research sources keep the legacy
scan_symbol path as the independent comparison oracle. See docs/COST_REDUCTION.md.
"""
import json, os, re, sys, math, statistics, time as _t, argparse, urllib.request, urllib.parse
import functools, hashlib, threading
from collections import deque
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, date, time, timedelta
from zoneinfo import ZoneInfo
from . import config
from . import flow
from . import market
from . import orbproc
from . import signals
from .ticks import RestSource, _ts as parse_market_timestamp, _ts_key as parse_market_timestamp_key
ET = ZoneInfo("America/New_York")
RELAY = config.RELAY_DATA
RELAY_TOKEN = config.getenv("ORBS_RELAY_TOKEN", "")
BAD = {"W", "4", "B", "C", "T"}; DEPTH = 25000.0; WIN = 100; Z = 2.0
# CTA/UTP sale conditions that are tape-eligible for VOLUME ONLY: the plans bar them from updating
# consolidated high/low/last. "I" is the odd lot (on 2026-09-03 it was ~60-80% of every symbol's
# morning prints and set the opening-range edge on 4 of 5 spot-checked names, incl. a ONE-SHARE PLTR
# print at 177.4216). They are real executions but not the market's price, so they stay in `trades`
# (volume/rvol must still count them) and are dropped from every PRICE decision below.
NOT_PRICE = {"I", "V", "7", "P", "U", "Z", "H", "M", "N"}
STATE = os.path.join(config.ROOT, "state")

# Match the stream freshness gate; test fixtures must supply recent observations.
REST_MAX_STALE_S = 120
REST_MIN_TRADES = 5
REST_MIN_QUOTES = 20
QUOTE_SIZE_SHARES_START = date(2025, 11, 3)
# 2026-09-15 cost audit: page size is bounded, every page is fetched inside one overall scan
# deadline, and a page that arrives incomplete/invalid fails its symbol loudly. The deadline
# covers the whole scan (all symbols), not a single request.
PAGE_LIMIT = max(100, min(10000, int(config.getenv("ORBS_PAGE_LIMIT", "10000"))))
PAGE_ATTEMPTS = max(1, int(config.getenv("ORBS_PAGE_ATTEMPTS", "3")))
SCAN_DEADLINE_S = float(config.getenv("ORBS_SCAN_DEADLINE_S", "240"))
ORBS_INCREMENTAL = config.getenv("ORBS_INCREMENTAL", "on").strip().lower() == "on"
CORRECTION_HORIZON_S = float(config.getenv("ORBS_CORRECTION_HORIZON_S", "900"))
REPAIR_WINDOW_S = float(config.getenv("ORBS_REPAIR_WINDOW_S", "120"))
RECONCILE_INTERVAL_S = float(config.getenv("ORBS_RECONCILE_INTERVAL_S", "300"))
# Scanner threads per robot. 2026-10-02: nine robots x 24 threads against one relay that admits
# 96 requests at a time produced 13,147 "relay busy" rejections in 50 minutes. 9 x 8 fits.
SCAN_CONCURRENCY = 8


class ScanTimeoutError(RuntimeError):
    """The overall scan deadline was exceeded; the symbol fails rather than running on."""


class ScanStats:
    """Thread-safe page counters; heartbeat advances only on actual scan progress."""
    def __init__(self):
        self.rows = self.pages = 0
        self._lock = threading.Lock()
        self._reported = 0.0

    def add(self, rows=0, pages=0):
        with self._lock:
            self.rows += rows
            self.pages += pages
            now = _t.monotonic()
            report = now - self._reported >= 5.0
            if report:
                self._reported = now
                detail = f"{self.pages} pages, {self.rows} rows received"
        if report:
            try:
                from . import shim as core
                core.status_heartbeat()
                _health("scan_progress", "Scanner download", "ok", detail)
            except Exception:
                pass


_ACTIVE = {"deadline": None, "stats": None}


def _current_rss_mb():
    try:
        with open("/proc/self/status") as handle:
            for line in handle:
                if line.startswith("VmRSS:"):
                    return round(int(line.split()[1]) / 1024.0, 1)
    except OSError:
        pass
    return None


def _rss_mb():
    """Peak resident set of this process, megabytes. getrusage units differ by platform
    (Linux KB, macOS bytes); the audit metrics only need a consistent, honest number."""
    try:
        import resource
        peak = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        kb = peak / 1024.0 if sys.platform == "darwin" else float(peak)
        return round(kb / 1024.0, 1)
    except Exception:
        return None


def _file_sha256(path):
    import hashlib
    try:
        with open(path, "rb") as f:
            return hashlib.sha256(f.read()).hexdigest()
    except Exception:
        return None
TRACE_GATES = {
    "delay": 1,
    "freshness": 2,
    "depth": 4,
    "sofi": 8,
}
TRACE_MASKS = tuple(range(16))


def _health(id_, label, state, detail, action=""):
    """Best-effort scanner telemetry; health reporting must never change scan behavior."""
    try:
        import data_health
        data_health.record(id_, label, state, str(detail)[:200], action=action)
    except Exception:
        pass


def _finite_positive(value):
    try:
        value = float(value)
        return value if math.isfinite(value) and value > 0 else None
    except (TypeError, ValueError):
        return None


def _normalize_quote_sizes(quotes, session):
    """Convert the provider's historical round lots to shares.

    Quote sizes are round lots before 2025-11-03 and shares from that session
    onward. The rule must not inspect later quotes because that would let data
    after a trigger change whether the earlier trigger passed its depth gate.
    """
    if session >= QUOTE_SIZE_SHARES_START:
        return
    for quote in quotes:
        quote["bs"] = int(quote.get("bs") or 0) * 100
        quote["as"] = int(quote.get("as") or 0) * 100


def _push_sofi(state, value):
    window = state["window"]
    if len(window) == window.maxlen:
        old = window.popleft()
        state["sum"] -= old
        state["sum_sq"] -= old * old
    window.append(value)
    state["sum"] += value
    state["sum_sq"] += value * value
    state["last"] = value


def _sofi_snapshot(state):
    count = len(state["window"])
    if count < 10:
        return count, None
    mean = state["sum"] / count
    variance = state["sum_sq"] / count - mean * mean
    if variance <= 0:
        return count, None
    return count, (state["last"] - mean) / math.sqrt(variance)


def _sofi_pass(direction, value):
    if value is None:
        return False
    return value >= Z if direction == "long" else value <= -Z


def _elapsed_ms(later_key, earlier_key):
    return (
        (later_key[0] - earlier_key[0]).total_seconds() * 1000.0
        + (later_key[1] - earlier_key[1]) / 1e6
    )


def _fresh_quote_age(age_ms):
    return age_ms is not None and 0.0 <= age_ms <= 5000.0


def _mask_passes(mask, direction, gates, deep_sofi, all_sofi):
    if mask & TRACE_GATES["delay"] and not gates["delay"]:
        return False
    if mask & TRACE_GATES["freshness"] and not gates["freshness"]:
        return False
    if mask & TRACE_GATES["depth"] and not gates["depth"]:
        return False
    if mask & TRACE_GATES["sofi"]:
        value = deep_sofi if mask & TRACE_GATES["depth"] else all_sofi
        if not _sofi_pass(direction, value):
            return False
    return True


def _daily_reference(
    bars,
    day,
    expected_session=None,
    expected_sessions=None,
):
    """Return valid, sorted pre-session daily bars or an empty list."""
    # watchlist records Alpaca's calendar date as ISO text; compare like types.
    if isinstance(expected_session, str):
        try:
            expected_session = date.fromisoformat(expected_session)
        except ValueError:
            return []
    normalized_sessions = None
    if expected_sessions is not None:
        normalized_sessions = []
        try:
            for session in expected_sessions:
                normalized_sessions.append(
                    date.fromisoformat(session)
                    if isinstance(session, str)
                    else session
                )
        except (TypeError, ValueError):
            return []
        if (
            not normalized_sessions
            or len(normalized_sessions) != len(set(normalized_sessions))
            or normalized_sessions != sorted(normalized_sessions)
            or any(
                not isinstance(session, date) or session >= day
                for session in normalized_sessions
            )
        ):
            return []
    good = []
    seen_dates = set()
    for b in bars or []:
        try:
            stamp = parse_market_timestamp(str(b["t"]))
            close = _finite_positive(b["c"])
            volume = _finite_positive(b["v"])
            high, low, opening = (_finite_positive(b[k]) for k in ("h", "l", "o"))
            if stamp.tzinfo is None or stamp.date() >= day or None in (close, volume, high, low, opening):
                continue
            if not low <= min(opening, close) <= max(opening, close) <= high:
                continue
            if stamp.date() in seen_dates:
                return []
            seen_dates.add(stamp.date())
            good.append((stamp.date(), close, volume, b))
        except (KeyError, TypeError, ValueError, AttributeError):
            continue
    good.sort(key=lambda row: row[0])
    if normalized_sessions is not None:
        by_day = {row[0]: row for row in good}
        if any(session not in by_day for session in normalized_sessions):
            return []
        good = [by_day[session] for session in normalized_sessions]
    if not good:
        return []
    latest = good[-1][0]
    if expected_session is not None and latest != expected_session:
        return []
    return [b for _, _, _, b in good]


def _bars_page(path, params):
    """Fetch every page of a multi-symbol daily-bars response."""
    merged = {}
    token = None
    for _ in range(100):
        q = dict(params)
        if token:
            q["page_token"] = token
        page = _get(path, q)
        for sym, rows in (page.get("bars") or {}).items():
            merged.setdefault(sym, []).extend(rows or [])
        token = page.get("next_page_token")
        if not token:
            return {"bars": merged}
    raise RuntimeError("daily bars pagination exceeded limit")


_RELAY_CLIENT = None

def get_relay_client():
    global _RELAY_CLIENT
    if _RELAY_CLIENT is None:
        _RELAY_CLIENT = market.RelayClient()
    return _RELAY_CLIENT

def _get(path, params, cache_store=None, cache=True, deadline=None, max_retries=3):
    return get_relay_client().get(path, params=params, is_meta=False,
        cache_store=cache_store, cache=cache, deadline=deadline, max_retries=max_retries)


def _meta_get(path, params=None):
    return get_relay_client().get(path, params=params, is_meta=True)


def _fetch_page_with_retry(kind, sym, params, deadline=None, scan_cache=None):
    """One bounded client retry budget, never nested attempts or raw-page fallback."""
    if deadline is not None and _t.monotonic() >= deadline:
        raise ScanTimeoutError(f"{sym} {kind}: scan deadline exceeded")
    return _get(f"/v2/stocks/{sym}/{kind}", params, cache=False,
                deadline=deadline, max_retries=PAGE_ATTEMPTS)


def _validate_page(kind, sym, j):
    if not isinstance(j, dict) or kind not in j or not isinstance(j[kind], (list, type(None))):
        raise ValueError(f"{sym} {kind}: malformed page")
    return j[kind] or []


def _paged(kind, sym, s_iso, e_iso, deadline=None, scan_cache=None):
    """Compatibility list loader for explicit research callers.
    Production REST scans use _iter_pages and never materialize this full list.
    Completed historical pages do not enter any fallback cache."""
    out, tok = [], None
    seen = set()
    for _ in range(1000):
        p = {"start": s_iso, "end": e_iso, "limit": PAGE_LIMIT, "feed": "sip", "sort": "asc"}
        if tok: p["page_token"] = tok
        j = _fetch_page_with_retry(kind, sym, p, deadline=deadline, scan_cache=scan_cache)
        rows = _validate_page(kind, sym, j)
        if _ACTIVE["stats"] is not None:
            _ACTIVE["stats"].add(rows=len(rows), pages=1)
        out += rows; tok = j.get("next_page_token")
        if not tok: return out
        if not isinstance(tok, str) or tok in seen:
            raise ValueError(f"{sym} {kind}: invalid or repeated page token")
        seen.add(tok)
    raise ValueError(f"{sym} {kind}: pagination limit exceeded")


def _iter_pages(kind, sym, start_dt, end_dt, deadline=None, scan_cache=None, stats=None):
    """Page iterator for the bounded processor: retains one page at a time in provider
    order and never caches completed pages. Same validation and retry contract as _paged; an incomplete
    or invalid page raises before any of its rows are consumed."""
    tok, seen = None, set()
    s_iso, e_iso = start_dt.isoformat(), end_dt.isoformat()
    for _ in range(1000):
        p = {"start": s_iso, "end": e_iso, "limit": PAGE_LIMIT, "feed": "sip", "sort": "asc"}
        if tok: p["page_token"] = tok
        j = _fetch_page_with_retry(kind, sym, p, deadline=deadline, scan_cache=scan_cache)
        rows = _validate_page(kind, sym, j)
        if stats is not None:
            stats.add(rows=len(rows), pages=1)
        for i, row in enumerate(rows):
            if i % 1024 == 0 and deadline is not None and _t.monotonic() >= deadline:
                raise ScanTimeoutError(f"{sym} {kind}: scan deadline exceeded while processing page")
            yield row
        tok = j.get("next_page_token")
        del rows, j
        if not tok: return
        if not isinstance(tok, str) or tok in seen:
            raise ValueError(f"{sym} {kind}: invalid or repeated page token")
        seen.add(tok)
    raise ValueError(f"{sym} {kind}: pagination limit exceeded")
def _ts(x):
    return parse_market_timestamp(x["t"])
def _ts_key(x):
    return parse_market_timestamp_key(x["t"])
def watchlist(d):
    """Top 250 by prior-session close*volume; assets and calendar via the relay, bars via the relay."""
    calendar_start = d - timedelta(days=35)
    calendar = _meta_get("/calendar", {"start": calendar_start.isoformat(), "end": (d-timedelta(days=1)).isoformat()})
    if not isinstance(calendar, list) or not calendar:
        raise RuntimeError("Prior trading session calendar unavailable")
    sessions = [date.fromisoformat(row["date"]) for row in calendar]
    if (
        len(sessions) != len(set(sessions))
        or any(not calendar_start <= session < d for session in sessions)
    ):
        raise RuntimeError("Invalid prior session calendar")
    sessions.sort()
    if len(sessions) < 15:
        raise RuntimeError("Insufficient prior trading sessions for ATR")
    expected_session = sessions[-1].isoformat()
    # Keep the actual prior-session close for the deal rule's local-only 09:38 lookup.
    # Unlike the daily status cache, this evidence is keyed to the scan day and covers holidays.
    from . import session_calendar
    session_calendar.remember_prior_close(d, calendar)
    assets = _meta_get("/assets", {"status": "active", "asset_class": "us_equity"})
    FUNDY = re.compile(r"\bETF\b|\bETN\b|\bFund\b|\bTrust\b|\bIndex\b|iShares|SPDR|Vanguard|ProShares|Direxion|Invesco (QQQ|S&P)|WisdomTree|Global X|VanEck|Grayscale|Bitwise|Select Sector", re.I)
    syms = [a["symbol"] for a in assets if a.get("tradable") and re.fullmatch(r"[A-Z]{1,5}", a["symbol"])
            and a.get("exchange") in ("NYSE", "NASDAQ", "AMEX", "ARCA", "BATS")
            and not FUNDY.search(a.get("name") or "")]
    start = (d - timedelta(days=10)).isoformat(); end = d.isoformat()
    scored = {}; reference_rows = {}
    def batch(bs):
        j = _bars_page("/v2/stocks/bars", {"symbols": ",".join(bs), "timeframe": "1Day", "start": start, "end": end, "limit": 10000, "feed": "sip", "adjustment": "raw"})
        for sym, bars in (j.get("bars") or {}).items():
            past = _daily_reference(bars, d)
            if past:
                reference_rows[sym] = past
    with ThreadPoolExecutor(8) as ex: list(ex.map(batch, [syms[i:i+200] for i in range(0, len(syms), 200)]))
    global REFERENCE_SESSION_DATE, REFERENCE_SESSION_DATES
    dates = [rows[-1]["t"][:10] for rows in reference_rows.values()]
    REFERENCE_SESSION_DATE = expected_session
    REFERENCE_SESSION_DATES = [
        session.isoformat() for session in sessions[-15:]
    ]
    if not dates or max(dates) != expected_session:
        _health("reference_data", "Prior close / ATR / volume", "error",
                "No recent common prior session was available.", "Refresh market reference data.")
        return [], {}
    for sym, past in reference_rows.items():
        if past[-1]["t"][:10] == REFERENCE_SESSION_DATE:
            scored[sym] = float(past[-1]["c"]) * float(past[-1]["v"])
    return [s for s, _ in sorted(scored.items(), key=lambda kv: -kv[1])[:250]], scored
def order_flow_delta(prev, bp, ap, bs, asz):
    """Signed bid demand minus ask supply (Cont/Kukanov/Stoikov, equation 2.1).

    An ask-price decrease contributes NEW ask supply; an increase removes OLD
    supply. At unchanged prices only the displayed-size difference contributes.
    """
    db = bs if bp > prev["bp"] else (bs - prev["bs"] if bp == prev["bp"] else -prev["bs"])
    da = asz if ap < prev["ap"] else (asz - prev["as"] if ap == prev["ap"] else -prev["as"])
    return db - da


def scan_symbol(sym, d, end_dt, prev_dv, src=None, trace=False, trigger_start=None):
    """src supplies the raw trade/quote rows. REST (today's behaviour) and the live stream hand over the
    SAME Alpaca field names, so everything below this line is identical for both and must stay that way.

    Research trace mode also returns the first price breakout for every
    deterministic scanner gate mask and direction. Production callers retain
    the original card, None, or ERROR contract.
    """
    try:
        src = src or RestSource(_paged)
        start_dt = datetime.combine(d, time(9, 30), tzinfo=ET)
        raw_trades = src.rows("trades", sym, start_dt, end_dt)
        raw_quotes = src.rows("quotes", sym, start_dt, end_dt)
        trades, quotes = [], []
        for t in raw_trades or []:
            ts = _ts(t)
            size = _finite_positive(t.get("s")); price = _finite_positive(t.get("p"))
            if not start_dt <= ts < end_dt or size is None or price is None: continue
            if not (set(t.get("c") or []) & BAD): trades.append(dict(t))
        for q in raw_quotes or []:
            ts = _ts(q)
            bp, ap = _finite_positive(q.get("bp")), _finite_positive(q.get("ap"))
            bs, az = _finite_positive(q.get("bs")), _finite_positive(q.get("as"))
            if not start_dt <= ts < end_dt or None in (bp, ap, bs, az) or not bp < ap: continue
            quotes.append(dict(q))
        trades.sort(key=_ts_key); quotes.sort(key=_ts_key)
        px_trades = [t for t in trades if not (set(t.get("c") or []) & NOT_PRICE)]
        if not px_trades: return "ERROR"
        adv = _finite_positive(prev_dv.get(sym) if isinstance(prev_dv, dict) else None)
        prev_close = _finite_positive(adv_close.get(sym) if isinstance(adv_close, dict) else None)
        if adv is None or prev_close is None: return "ERROR"
        newest_trade = _ts(px_trades[-1])
        newest_quote = _ts(quotes[-1]) if quotes else None
        minimum_rows_pass = (
            len(trades) >= REST_MIN_TRADES
            and len(quotes) >= REST_MIN_QUOTES
        )
        trade_freshness_pass = (
            (end_dt - newest_trade).total_seconds()
            <= REST_MAX_STALE_S
        )
        quote_freshness_pass = (
            newest_quote is not None
            and (end_dt - newest_quote).total_seconds()
            <= REST_MAX_STALE_S
        )
        freeze_quality_pass = (
            minimum_rows_pass
            and trade_freshness_pass
            and quote_freshness_pass
        )
        quality = {
            "trade_count": len(trades),
            "quote_count": len(quotes),
            "minimum_rows_pass": minimum_rows_pass,
            "newest_trade_at": str(px_trades[-1]["t"]),
            "newest_quote_at": (
                str(quotes[-1]["t"]) if quotes else None
            ),
            "trade_freshness_pass": trade_freshness_pass,
            "quote_freshness_pass": quote_freshness_pass,
            "freeze_quality_pass": freeze_quality_pass,
        }
        if not trace and not freeze_quality_pass:
            return "ERROR"
        _normalize_quote_sizes(quotes, d)
        orb = [(float(t["p"]), _ts(t)) for t in px_trades if time(9, 30) <= _ts(t).time() < time(9, 35)]
        if not orb: return "ERROR"
        hi = max(p for p, _ in orb); lo = min(p for p, _ in orb)
        o_orb = orb[0][0]
        c_orb = orb[-1][0]
        s_930 = o_orb
        geom = signals.analyze_candle_geometry(hi, lo, o_orb, c_orb, s_930)
        wbr = geom.wbr

        is_etf = sym in signals.INDEX_ETFS
        if geom.is_wick_trap:
            if is_etf:
                signals.SESSION_LOCKOUT.trigger_lockout(
                    sym, wbr, f"Indecision Wick Trap on {sym} (WBR={wbr:.2f} > 3.5)"
                )
            if not trace:
                return None
        if signals.SESSION_LOCKOUT.is_locked() and not trace:
            return None
        # Every kept trade enters the event stream (flow rules 1 and 2 count odd lots and volume-only
        # prints); only price-eligible trades reach the break logic below. `trades` is sorted and px_trades
        # is its filtered subsequence, so the price-eligible order is unchanged.
        events = sorted(
            [(_ts_key(q), 1, _ts(q), "q", q) for q in quotes]
            + [(_ts_key(t), 0, _ts(t), "t", t) for t in trades],
            key=lambda row: (row[0], row[1]),
        )
        delta_state = flow.DeltaState(); velocity_state = flow.VelocityState(); cross_state = flow.CrossState()
        trig_flow = None
        prev = None; trig = None; spread_bps = None
        trig_candle = None; candle_dir = signals.candle_direction(o_orb, c_orb)
        deep_state = {"window": deque(maxlen=WIN), "sum": 0.0, "sum_sq": 0.0, "last": 0.0}
        all_state = {"window": deque(maxlen=WIN), "sum": 0.0, "sum_sq": 0.0, "last": 0.0}
        trace_events = []
        seen_masks = {"long": set(), "short": set()}
        vol5 = sum(int(t["s"]) for t in trades if _ts(t).time() < time(9, 35))
        dv5 = sum(float(t["p"]) * int(t["s"]) for t in trades if _ts(t).time() < time(9, 35))
        for event_key, _priority, ts, kind, obj in events:
            if kind == "q":
                bp, ap = float(obj.get("bp") or 0), float(obj.get("ap") or 0); bs, asz = int(obj.get("bs") or 0), int(obj.get("as") or 0)
                if bp <= 0 or ap <= 0 or bs <= 0 or asz <= 0: continue
                if bp < ap: spread_bps = (ap - bp) / ((ap + bp) / 2) * 1e4
                if prev is not None:
                    avg = (bs + asz) / 2.0
                    val = order_flow_delta(prev, bp, ap, bs, asz) / avg if avg else 0.0
                    _push_sofi(all_state, val)
                    if bp * bs >= DEPTH and ap * asz >= DEPTH:
                        _push_sofi(deep_state, val)
                prev = {"bp": bp, "ap": ap, "bs": bs, "as": asz,
                        "ts": ts, "key": event_key, "raw_t": obj["t"]}
            else:
                velocity_state.add(ts)
                cross_state.refresh(velocity_state, ts)
                delta_state.add(obj.get("p"), obj.get("s"), obj.get("c"), prev)
                if set(obj.get("c") or []) & NOT_PRICE:
                    continue
                if ts.time() < time(9, 35):
                    continue
                p = float(obj["p"])
                direction = "long" if p > hi else "short" if p < lo else None
                crossing = cross_state.update(direction, velocity_state, ts)
                if direction is None:
                    continue
                quote_age_ms = _elapsed_ms(event_key, prev["key"]) if prev is not None else None
                delay_pass = ts.time() >= time(9, 35, 5)
                freshness_pass = _fresh_quote_age(quote_age_ms)
                depth_pass = (
                    prev is not None
                    and prev["bp"] * prev["bs"] >= DEPTH
                    and prev["ap"] * prev["as"] >= DEPTH
                )
                deep_count, deep_z = _sofi_snapshot(deep_state)
                all_count, all_z = _sofi_snapshot(all_state)
                gates = {
                    "delay": delay_pass,
                    "freshness": freshness_pass,
                    "depth": depth_pass,
                }
                first_for_masks = []
                if trace:
                    for mask in TRACE_MASKS:
                        if mask in seen_masks[direction]:
                            continue
                        if _mask_passes(
                            mask, direction, gates, deep_z, all_z
                        ):
                            seen_masks[direction].add(mask)
                            first_for_masks.append(mask)
                event = {
                    "_ts": ts,
                    "_key": event_key,
                    "trigger_at": str(obj["t"]),
                    "direction": direction,
                    "entry": p,
                    "trigger_spread_bps": spread_bps,
                    "quote_at": str(prev["raw_t"]) if prev is not None else None,
                    "quote_age_ms": quote_age_ms,
                    "bid": prev["bp"] if prev is not None else None,
                    "ask": prev["ap"] if prev is not None else None,
                    "bid_size": prev["bs"] if prev is not None else None,
                    "ask_size": prev["as"] if prev is not None else None,
                    "delay_pass": delay_pass,
                    "freshness_pass": freshness_pass,
                    "depth_pass": depth_pass,
                    "sofi_deep_count": deep_count,
                    "sofi_deep_z": deep_z,
                    "sofi_deep_pass": _sofi_pass(direction, deep_z),
                    "sofi_all_count": all_count,
                    "sofi_all_z": all_z,
                    "sofi_all_pass": _sofi_pass(direction, all_z),
                    "first_for_masks": first_for_masks,
                }
                if first_for_masks:
                    trace_events.append(event)
                current_pass = (
                    delay_pass
                    and freshness_pass
                    and depth_pass
                    and _sofi_pass(direction, deep_z)
                )
                flow_ok = True
                if not trace and flow.entry_rules_on():
                    # Flow rules 1 and 2 (production only; research trace output stays byte-identical).
                    fields, flow_ok = flow.flow_fields(delta_state, crossing, direction)
                    event.update(fields)
                if trig is None and current_pass and (trigger_start is None or ts >= trigger_start):
                    trig = event
                # Candle rule: independent latch for the first passing break the opening candle allows.
                if (trig_candle is None and current_pass and direction == candle_dir
                        and (trigger_start is None or ts >= trigger_start)):
                    trig_candle = event
                # Flow trade latch, identical to orbproc.SymbolReducer (old gates + flow + candle direction).
                if (trig_flow is None and current_pass and flow_ok
                        and (not config.CANDLE_RULE or direction == candle_dir)
                        and (trigger_start is None or ts >= trigger_start)):
                    trig_flow = event
        if not trig and not trace:
            return None
        # Candle rule, identical to orbproc.SymbolReducer.wave_result (production only).
        first = trig
        candle_rule = config.CANDLE_RULE and not trace and trig is not None
        candle_blocked = False
        if candle_rule:
            if trig_candle is not None:
                trig = trig_candle
            else:
                candle_blocked = True
        # Flow rules 1/2, identical to orbproc.SymbolReducer.wave_result.
        flow_rule = flow.entry_rules_on() and not trace and trig is not None
        flow_blocked = False
        if flow_rule:
            if trig_flow is not None:
                trig = trig_flow
                candle_blocked = False
            else:
                flow_blocked = True
        if trace and not trace_events:
            quality["atr_valid"] = bool(
                _finite_positive(_prep["atr"].get(sym))
            )
            quality["production_result_valid"] = freeze_quality_pass
            quality["research_result_valid"] = freeze_quality_pass
            return {
                "card": None,
                "breakouts": [],
                "quality": quality,
            }
        lastpx = float(px_trades[-1]["p"])
        rvol = dv5 / (adv * 5 / 390)
        atr_abs = _finite_positive(_prep["atr"].get(sym))
        atr_valid = atr_abs is not None
        quality["atr_valid"] = atr_valid
        quality["production_result_valid"] = (
            freeze_quality_pass and (trig is None or atr_valid)
        )
        quality["research_result_valid"] = (
            freeze_quality_pass and (not trace_events or atr_valid)
        )
        if not trace and not atr_valid:
            return "ERROR"
        gap = (orb[0][0] / prev_close - 1) * 100
        buf = 0.25 * atr_abs if atr_valid else None

        def enrich(event):
            direction = event["direction"]
            entry = event["entry"]
            stop = (
                (
                    min(lo - buf, entry * 0.995)
                    if direction == "long"
                    else max(hi + buf, entry * 1.005)
                )
                if buf is not None
                else None
            )
            drift = (
                (lastpx - entry)
                / entry
                * 100
                * (1 if direction == "long" else -1)
            )
            return {
                key: value
                for key, value in {
                    **event,
                    "stop": stop,
                    "freeze_price": lastpx,
                    "drift_pct": drift,
                    "gap_pct": gap,
                    "rvol": rvol,
                    "atr_pct": (
                        atr_abs / entry * 100
                        if atr_valid
                        else None
                    ),
                    "freeze_spread_bps": spread_bps,
                    "orb_high": hi,
                    "orb_low": lo,
                    "orb_width_pct": (hi - lo) / entry * 100.0,
                    "opening_volume": vol5,
                    "opening_dollar_volume": dv5,
                    "freeze_price_at": str(px_trades[-1]["t"]),
                }.items()
                if not key.startswith("_")
            }

        card = None
        if trig and quality["production_result_valid"] and not geom.is_wick_trap and not signals.SESSION_LOCKOUT.is_locked():
            exact = enrich(trig)
            dr = exact["direction"]
            entry = exact["entry"]
            stop = exact["stop"]
            drift = exact["drift_pct"]
            z = exact["sofi_deep_z"]
            ts = trig["_ts"]
            trigger_raw_time = exact["trigger_at"]
            is_etf = sym in signals.INDEX_ETFS
            mode = "OPTIONS" if is_etf else "EQUITY"
            h_orb = round(hi, 2)
            l_orb = round(lo, 2)
            m_orb = round((hi + lo) / 2.0, 2)
            atr_val = round(atr_abs, 2) if atr_abs is not None else round(entry * (exact["atr_pct"] / 100.0), 2)
            wbr_val = round(wbr, 3)
            sofi_val = round(z, 2) if z is not None else 0.0
            bid_notional = float(exact["bid"] or 0.0) * float(exact["bid_size"] or 0.0)
            ask_notional = float(exact["ask"] or 0.0) * float(exact["ask_size"] or 0.0)
            depth_bid = round(bid_notional, 2)
            depth_ask = round(ask_notional, 2)
            quote_age_ms = round(exact["quote_age_ms"], 1) if exact.get("quote_age_ms") is not None else 0.0

            signal_snapshot = {
                    "trigger_at": trigger_raw_time, "entry": entry, "stop": stop,
                    "freeze_price": lastpx, "drift_pct": drift, "gap_pct": gap,
                    "rvol": rvol, "atr_pct": exact["atr_pct"], "sofi": z,
                    "spread_bps": exact["trigger_spread_bps"],
                    "bid": exact["bid"], "ask": exact["ask"],
                    "bid_size": exact["bid_size"], "ask_size": exact["ask_size"],
                    "quote_at": exact["quote_at"],
                    "quote_age_ms": exact["quote_age_ms"],
                    "orb_high": hi, "orb_low": lo,
                    "orb_width_pct": exact["orb_width_pct"],
                    "opening_volume": vol5, "opening_dollar_volume": dv5,
                    "freeze_price_at": exact["freeze_price_at"],
                    "wbr": wbr_val,
                    "midpoint": m_orb,
                    "bid_depth": depth_bid,
                    "ask_depth": depth_ask,
                    "is_wick_trap": geom.is_wick_trap}
            card = {
                "symbol": sym,
                "mode": mode,
                "H_ORB": h_orb,
                "L_ORB": l_orb,
                "M_ORB": m_orb,
                "ATR": atr_val,
                "RVOL": rvol,
                "WBR": wbr_val,
                "gap_pct": gap,
                "sofi_z": sofi_val,
                "depth_bid": depth_bid,
                "depth_ask": depth_ask,
                "quote_age_ms": quote_age_ms,
                "h_orb": h_orb,
                "l_orb": l_orb,
                "m_orb": m_orb,
                "wbr": wbr_val,
                "is_wick_trap": geom.is_wick_trap,
                "is_indecision_trap": geom.is_wick_trap,
                "direction": dr,
                "entry": round(entry, 2),
                "stop": round(stop, 2),
                # Decision inputs retain precision; rounding here can cross a refusal threshold.
                "drift_pct": drift,
                "rvol": rvol,
                "atr_pct": exact["atr_pct"],
                "spread_bps": spread_bps,
                "sofi": z,
                "trig": ts.strftime("%H:%M:%S"),
                "spread_asof": newest_quote.isoformat(),
                "price_asof": newest_trade.isoformat(),
                "signal_snapshot": signal_snapshot}
            if candle_rule:
                card.update(orbproc._candle_fields(o_orb, c_orb, first, candle_blocked))
            if flow_rule:
                card.update(orbproc.flow_card_fields(exact, first, flow_blocked))
                signal_snapshot.update(orbproc.flow_card_fields(exact, first, flow_blocked))
        if trace:
            return {
                "card": card,
                "breakouts": [enrich(event) for event in trace_events],
                "quality": quality,
            }
        return card
    except Exception as exc:
        print(f"{sym} scan failed: {type(exc).__name__}: {str(exc)[:160]}", flush=True)
        return "ERROR"          # P1-9: a failure is NOT the same as "no breakout"; run() counts these
adv_close = {}
_prep = {"day": None, "wl": None, "prev_dv": None, "atr": {}}
REFERENCE_SESSION_DATE = None
REFERENCE_SESSION_DATES = None
def prep(d):
    if _prep["day"] == d and _prep["wl"]: return
    _health("reference_data", "Prior close / ATR / volume", "waiting", "Loading prior-session reference data.")
    try: return _prepare(d)
    except Exception:
        _health("reference_data", "Prior close / ATR / volume", "error",
                "Prior-session calendar, prices, or volumes could not be verified.",
                "Check the calendar and market data connection; incomplete references are not used.")
        raise


def _prepare(d):
    """Heavy pre-work, independent of the open: watchlist, prior closes, ATR. Reused by run()."""
    global adv_close
    if _prep["day"] == d and _prep["wl"]: return
    adv_close = {}
    _prep.update(day=None, wl=None, prev_dv=None, atr={})
    wl, prev_dv = watchlist(d)
    next_close, next_atr = {}, {}
    def cbatch(bs):
        r = _bars_page("/v2/stocks/bars", {"symbols": ",".join(bs), "timeframe": "1Day", "start": (d - timedelta(days=25)).isoformat(), "end": d.isoformat(), "limit": 10000, "feed": "sip", "adjustment": "raw"})
        got_close, got_atr = {}, {}
        for sym, bars in (r.get("bars") or {}).items():
            past = _daily_reference(
                bars,
                d,
                REFERENCE_SESSION_DATE,
                REFERENCE_SESSION_DATES,
            )
            if past:
                got_close[sym] = float(past[-1]["c"])
                if len(past) >= 5:
                    pb = past[-15:]
                    trs = [max(b["h"] - b["l"], abs(b["h"] - a["c"]), abs(b["l"] - a["c"])) for a, b in zip(pb[:-1], pb[1:])]
                    if trs and all(math.isfinite(float(x)) and x > 0 for x in trs): got_atr[sym] = statistics.mean(trs)
        return got_close, got_atr
    with ThreadPoolExecutor(8) as ex:
        for closes, atrs in ex.map(cbatch, [wl[i:i+200] for i in range(0, len(wl), 200)]):
            next_close.update(closes); next_atr.update(atrs)
    adv_close.update(next_close)
    _prep.update(day=d, wl=wl, prev_dv=prev_dv, atr=next_atr)
    ref_state = "error" if not wl or not next_close or not next_atr else (
        "ok" if len(next_close) == len(wl) and len(next_atr) == len(wl) else "warning")
    _health("reference_data", "Prior close / ATR / volume", ref_state,
            f"{len(next_close)} closes, {len(next_atr)} ATR references for {len(wl)} symbols",
            "missing symbols are refused")
    print(f"{d} prep done: watchlist {len(wl)}, closes {len(adv_close)}, atr {len(_prep['atr'])}", flush=True)


def _scan_pool(symbols, scan, source):
    """Retry failed REST symbols once at lower concurrency against the same frozen window."""
    with ThreadPoolExecutor(24) as ex:
        rows = dict(zip(symbols, ex.map(scan, symbols)))
    retry = [sym for sym, row in rows.items() if row == "ERROR"] if getattr(source, "name", None) == "rest" else []
    if retry:
        with ThreadPoolExecutor(4) as ex:
            rows.update(zip(retry, ex.map(scan, retry)))
    return rows, retry


# ---------------- bounded REST sessions and scan publication ----------------

_SCAN_LOCK = threading.RLock()


def _serialized_scan(fn):
    @functools.wraps(fn)
    def wrapped(*args, **kwargs):
        with _SCAN_LOCK:
            return fn(*args, **kwargs)
    return wrapped


class _scan_context:
    """One serialized scan budget. Historical response pages are never cached."""
    def __enter__(self):
        self.client = get_relay_client()
        self.prev_metrics = self.client.metrics
        self.stats = ScanStats()
        self.metrics = market.ScanMetrics()
        self.started = _t.monotonic()
        _ACTIVE.update(deadline=self.started + SCAN_DEADLINE_S, stats=self.stats)
        self.client.metrics = self.metrics
        return self

    def __exit__(self, *exc):
        self.finished = _t.monotonic()
        _ACTIVE.update(deadline=None, stats=None)
        self.client.metrics = self.prev_metrics
        return False

    def health_metrics(self, out_path, end_hhmm):
        snap = self.metrics.snapshot()
        snap.update(rows_fetched=self.stats.rows, pages_fetched=self.stats.pages,
                    scan_cache_entries=0, cutoffs={"start": "09:30", "end": end_hhmm},
                    peak_rss_mb=_rss_mb(), current_rss_mb=_current_rss_mb(),
                    elapsed_s=round(self.finished - self.started, 3),
                    output_sha256=_file_sha256(out_path))
        return snap


def _session_fetcher(kind, sym, start_dt, end_dt):
    return _iter_pages(kind, sym, start_dt, end_dt, deadline=_ACTIVE["deadline"],
                       stats=_ACTIVE["stats"])


def _secondary_start_dt(d, min_trigger_time=None):
    return datetime.combine(d, time.fromisoformat(
        min_trigger_time or config.SECONDARY_WAVE_START), tzinfo=ET)


_SESSION = None
_SESSION_KEY = None


def _get_session(d, secondary_start=None):
    """Reference/source/window changes or bounded-full-replay mode create fresh state."""
    global _SESSION, _SESSION_KEY
    wl, prev_dv = _prep["wl"], _prep["prev_dv"]
    sec = secondary_start or _secondary_start_dt(d)
    pri = datetime.combine(d, time(9, 35, 5), tzinfo=ET)
    source_id = "rest:sip:" + hashlib.sha256(get_relay_client().base_url.encode()).hexdigest()
    candidate = orbproc.Session(d, wl, prev_dv, adv_close, _prep["atr"], pri, sec,
        fetcher=_session_fetcher, state_dir=STATE, source_id=source_id,
        correction_horizon_s=CORRECTION_HORIZON_S, concurrency=SCAN_CONCURRENCY,
        repair_window_s=REPAIR_WINDOW_S, reconcile_interval_s=RECONCILE_INTERVAL_S)
    key = candidate.fingerprint()
    if ORBS_INCREMENTAL and _SESSION is not None and _SESSION_KEY == key:
        return _SESSION
    _SESSION, _SESSION_KEY = candidate, key
    return candidate


def _write_cards_atomic(out_path, cards):
    os.makedirs(STATE, exist_ok=True)
    tmp = out_path + ".%d.%d.tmp" % (os.getpid(), threading.get_ident())
    with open(tmp, "w") as f:
        for c in cards:
            f.write(json.dumps(c) + "\n")
    os.replace(tmp, out_path)


def _write_meta_atomic(health, path=None):
    path = path or os.path.join(STATE, "cards_today.meta.json")
    tmp = path + ".%d.%d.tmp" % (os.getpid(), threading.get_ident())
    with open(tmp, "w") as f:
        json.dump(health, f)
    os.replace(tmp, path)


def _bounded_wave(d, end_dt, window, occupied, secondary_start=None):
    sess = _get_session(d, secondary_start)
    sess.advance(end_dt, symbols=[sym for sym in sess.wl if sym not in occupied])
    cards, outcomes = sess.wave(end_dt, window, exclude=occupied)
    refused = [sym for sym, outcome in outcomes.items() if outcome == "ERROR"]
    if refused:
        sess.retry_symbols(refused, end_dt)
        _, repaired = sess.wave(end_dt, window, exclude=set(sess.wl) - set(refused))
        outcomes.update(repaired)
        cards = sorted((result for result in outcomes.values() if isinstance(result, dict)),
                       key=lambda card: card["trig"])
    return cards, outcomes, list(sess.last_retried), sess


def _scan_board(d, end_hhmm, src, window="primary", occupied=None, trigger_start=None):
    wl, prev_dv = _prep["wl"], _prep["prev_dv"]
    occupied = set(occupied or ())
    candidates = [sym for sym in wl if sym not in occupied]
    end_dt = datetime.combine(d, time.fromisoformat(end_hhmm), tzinfo=ET)
    secondary = window == "secondary"
    filename = "cards_secondary_%s.jsonl" % end_hhmm.replace(":", "") if secondary else "cards_today.jsonl"
    out_path = os.path.join(STATE, filename)
    session = None
    with _scan_context() as ctx:
        if src is None:
            cards, outcomes, retried, session = _bounded_wave(
                d, end_dt, window, occupied, trigger_start)
        else:
            # Explicit sources retain the legacy stream/research oracle path.
            outcomes, retried = _scan_pool(candidates, lambda sym: scan_symbol(
                sym, d, end_dt, prev_dv, src, trigger_start=trigger_start), src)
            cards = [c for c in outcomes.values() if isinstance(c, dict)]
            if secondary:
                cards = [c for c in cards if c.get("trig") and str(c["trig"]) >= trigger_start.strftime("%H:%M:%S")]
            cards.sort(key=lambda c: c["trig"])
    failed = [sym for sym in candidates if outcomes.get(sym, "ERROR") == "ERROR"]
    attempted, ok = len(candidates), len(candidates) - len(failed)
    coverage = ok / attempted if attempted else 0.0
    _write_cards_atomic(out_path, cards)
    health = dict(day=d.isoformat(), source="secondary" if secondary else "file",
                  feed=getattr(src, "name", "rest"), end=end_hhmm,
                  attempted=attempted, ok=ok, failed=len(failed), failed_symbols=failed,
                  cards=len(cards), retried_symbols=retried,
                  recovered_symbols=[sym for sym in retried if sym not in failed],
                  coverage=coverage if secondary else round(coverage, 4),
                  built_at=datetime.now(ET).isoformat(),
                  metrics=ctx.health_metrics(out_path, end_hhmm))
    if session is not None:
        health.update(incremental=ORBS_INCREMENTAL,
                      scan_mode="incremental_rest" if ORBS_INCREMENTAL else "bounded_full_rest",
                      session=dict(last_end=session.last_end.isoformat(),
                                   bootstraps=session.bootstrap_count, **session.metadata()))
    _write_meta_atomic(health, os.path.splitext(out_path)[0] + ".meta.json")
    _archive_board(out_path, d, window, end_hhmm, cards, health)
    scan_state = "ok" if secondary and not attempted else (
        "error" if not attempted or coverage < config.MIN_SCAN_COVERAGE else ("warning" if failed else "ok"))
    _health("scanner_secondary" if secondary else "scanner",
            "Secondary trades / quotes" if secondary else "Opening trades / quotes", scan_state,
            f"{ok} of {attempted} symbols verified; {len(failed)} failed",
            "Review failed symbols before relying on today's board." if failed else "")
    _candle_health(cards, window)
    _flow_health(cards, window)
    print(f"{d} {window} scan to {end_hhmm}: watchlist {attempted}, ok {ok}, "
          f"failed {len(failed)}, cards {len(cards)} -> {out_path}")
    return cards, health


def _archive_board(out_path, d, window, end_hhmm, cards, health):
    """Per-day copy of every board (docs/CARD_LOGGING_PLAN_2026-09-25.md): the live files above are
    overwritten each scan and each day, this copy is not. Beside the live file's folder, so a test
    that redirects the live file redirects this too. Measurement only; a failure is printed, never
    raised into the scan."""
    try:
        if d != datetime.now(ET).date():
            return          # a --replay of a past day must never overwrite that day's real boards
        folder = os.path.join(os.path.dirname(out_path), "boards", d.isoformat())
        os.makedirs(folder, exist_ok=True)
        stem = os.path.join(folder, "%s_%s" % (window, end_hhmm.replace(":", "")))
        _write_cards_atomic(stem + ".jsonl", cards)
        _write_meta_atomic(health, stem + ".meta.json")
    except Exception as exc:
        print(f"board archive write failed (ignored): {type(exc).__name__}: {exc}", flush=True)


def _flow_health(cards, window):
    """Dashboard row for the flow rules. Informational, never red."""
    try:
        _health("flow_rules", "Flow rules", "ok",
                f"{flow.status_sentence()} {window.capitalize()} board: {len(cards)} breakouts, "
                f"{sum(1 for c in cards if c.get('flow_blocked'))} held back by delta or speed.")
    except Exception:
        pass


def _candle_health(cards, window):
    """Dashboard row for the candle rule. Informational, never red."""
    if not config.CANDLE_RULE:
        _health("candle_rule", "Candle rule", "ok",
                "Off (ORBS_CANDLE_RULE=off): the first break trades whichever way it goes.")
        return
    blocked = sum(1 for c in cards if c.get("candle_blocked"))
    waited = sum(1 for c in cards if not c.get("candle_blocked")
                 and c.get("board_direction") and c.get("board_direction") != c.get("direction"))
    _health("candle_rule", "Candle rule", "ok",
            f"On: a green first 5 minutes may only buy, red only short. {window.capitalize()} board: "
            f"{len(cards)} breakouts, {waited} took a later break the candle allowed, {blocked} skipped.")
    # Permanent record for the 30-day review (cards_today.jsonl is overwritten each day): every card the
    # rule changed, with both breaks. Best-effort; logging must never change scan behaviour.
    changed = [c for c in cards if c.get("candle_blocked") or
               (c.get("board_direction") and c.get("board_direction") != c.get("direction"))]
    if changed:
        try:
            from . import shim as core
            core._ledger({"kind": "candle_rule", "day": core.today(), "window": window, "cards": [
                {"symbol": c.get("symbol"), "candle": c.get("candle"), "blocked": bool(c.get("candle_blocked")),
                 "first_break": c.get("first_break"), "direction": c.get("direction"), "entry": c.get("entry"),
                 "stop": c.get("stop"), "trig": c.get("trig"),
                 "candle_open": c.get("candle_open"), "candle_close": c.get("candle_close")} for c in changed]})
        except Exception:
            pass


def _locked_result(d, end_hhmm, secondary=False):
    return [], dict(day=d.isoformat(), source="secondary" if secondary else "file",
                    feed="none", end=end_hhmm, attempted=0, ok=0, failed=0,
                    failed_symbols=[], cards=0, coverage=0.0,
                    built_at=datetime.now(ET).isoformat(), locked_out=True)


@_serialized_scan
def run(d, end_hhmm, src=None):
    """Build the full board; count transport and data-quality failures before publication.

    Default REST uses bounded reducers and correction-aware incremental state. Setting
    ORBS_INCREMENTAL=off rebuilds with the same bounded processor at every cutoff.
    Explicit sources retain legacy stream/research behavior.
    """
    if signals.SESSION_LOCKOUT.is_locked():
        return _locked_result(d, end_hhmm)
    prep(d)
    return _scan_board(d, end_hhmm, src)


@_serialized_scan
def run_secondary(d, end_hhmm, src=None, min_trigger_time=None):
    """Preserve occupied/already-traded exclusions and the complete eligible board."""
    if signals.SESSION_LOCKOUT.is_locked():
        return _locked_result(d, end_hhmm, secondary=True)
    prep(d)
    occupied = set()
    try:
        from . import shim as core
        occupied.update(core._superv_open().keys())
        for record in core._todays("execution"):
            for pick in record.get("picks") or []:
                if pick.get("symbol"):
                    occupied.add(pick["symbol"])
    except Exception as exc:
        raise RuntimeError("cannot verify previously traded symbols for secondary scan") from exc
    return _scan_board(d, end_hhmm, src, "secondary", occupied,
                       _secondary_start_dt(d, min_trigger_time))


# ---------------- live-stream shadow ----------------
def build_from(src, d, end_hhmm):
    """Build the card list from an arbitrary source WITHOUT touching state/. Used for the shadow board:
    it must never write the file the live board is read from."""
    prep(d)
    wl, prev_dv = _prep["wl"], _prep["prev_dv"]
    end_dt = datetime.combine(d, time(*map(int, end_hhmm.split(":"))), tzinfo=ET)
    out, failed = [], 0
    with ThreadPoolExecutor(24) as ex:
        for c in ex.map(lambda sym: scan_symbol(sym, d, end_dt, prev_dv, src), wl):
            if c == "ERROR": failed += 1
            elif c: out.append(c)
    return sorted(out, key=lambda c: c["trig"]), failed


def shadow_diff(rest_cards, stream_cards, tol_price=0.01, tol_sofi=0.05):
    """What 'the same board' means, defined UP FRONT so the cutover bar cannot be quietly relaxed later
    (glm-5.3 finding 14). Byte equality is the wrong bar: REST at 09:38:52 is a post-hoc consolidated
    read that includes late-reported and corrected prints, while the stream is what crossed the wire by
    09:38:00. Those legitimately differ. What must NOT differ is the decision: same symbols, same
    direction, entry/stop within a cent, sofi within 0.05."""
    r = {c["symbol"]: c for c in rest_cards}; t = {c["symbol"]: c for c in stream_cards}
    only_rest = sorted(set(r) - set(t)); only_stream = sorted(set(t) - set(r))
    moved = []
    for sym in sorted(set(r) & set(t)):
        a, b = r[sym], t[sym]
        if a["direction"] != b["direction"]: moved.append(f"{sym}: direction {a['direction']}->{b['direction']}")
        elif abs(a["entry"] - b["entry"]) > tol_price: moved.append(f"{sym}: entry {a['entry']}->{b['entry']}")
        elif abs(a["stop"] - b["stop"]) > tol_price: moved.append(f"{sym}: stop {a['stop']}->{b['stop']}")
        elif abs((a.get("sofi") or 0) - (b.get("sofi") or 0)) > tol_sofi: moved.append(f"{sym}: sofi {a.get('sofi')}->{b.get('sofi')}")
    return {"agree": not (only_rest or only_stream or moved), "n_rest": len(rest_cards),
            "n_stream": len(stream_cards), "only_rest": only_rest, "only_stream": only_stream,
            "moved": moved[:20]}


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--replay"); ap.add_argument("--end", default="09:38"); a = ap.parse_args()
    d = date.fromisoformat(a.replay) if a.replay else datetime.now(ET).date()
    run(d, a.end)
