# Copied from ORBStraddle session_calendar.py @05d370d; logic unchanged; edits:
#   1. package-relative import of config, plus the shim that owns the HTTP transport
#   2. HTTP goes through shim.urlopen (default urllib.request.urlopen; injectable for replay)
#   3. calendar and prior-close files live in config.STATE (ADT's facade sets the state dir; ORBStraddle derives ROOT/state)
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
"""Small, read-only trading-session calendar cache.

The calendar is consulted only by callers that need to validate a requested
market day.  ``status`` is deliberately a local-only read, so a dashboard or
health poll cannot turn into a broker request.
"""
import json
import os
import tempfile
import threading
import time
import urllib.parse
import urllib.request
from datetime import date, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

from . import config
from . import shim

ET = ZoneInfo("America/New_York")
REQUEST_TIMEOUT_S = 3.0
RETRY_AFTER_S = 60.0

_lock = threading.RLock()
_fetch_lock = threading.Lock()
_memory = {}
_last_attempt = {}


def _path():
    suffix = "_demo" if config.CARD_SOURCE == "demo" else ""
    return Path(config.STATE) / ("session_calendar" + suffix + ".json")


def _now():
    return datetime.now(ET)


def _day_text(day):
    if isinstance(day, datetime):
        raise ValueError("calendar day must be a date")
    if isinstance(day, date):
        return day.isoformat()
    if isinstance(day, str):
        parsed = date.fromisoformat(day)
        return parsed.isoformat()
    raise ValueError("calendar day is invalid")


def _record(state, detail, action=""):
    try:
        import data_health
        data_health.record("market_calendar", "Trading calendar", state, detail, action=action)
    except Exception:
        pass


def _read_cache(day):
    def valid(row):
        if not isinstance(row, dict) or row.get("day") != day or type(row.get("is_open")) is not bool:
            return False
        try:
            stamp = datetime.fromisoformat(row["checked_at"])
            return stamp.tzinfo is not None and -5 <= (_now()-stamp).total_seconds() <= 86400
        except (KeyError, ValueError, TypeError): return False
    with _lock:
        row = _memory.get(day)
        if valid(row):
            return dict(row)
        try:
            raw = json.loads(_path().read_text())
        except (FileNotFoundError, OSError, ValueError, TypeError, AttributeError):
            return None
        if not isinstance(raw, dict):
            return None
        row = raw.get(day)
        if not valid(row):
            return None
        _memory[day] = dict(row)
        return dict(row)


def _write_cache(row):
    day = row["day"]
    _memory[day] = dict(row)
    try:
        path = _path()
        path.parent.mkdir(parents=True, exist_ok=True)
        try:
            raw = json.loads(path.read_text())
            cache = raw if isinstance(raw, dict) else {}
        except (FileNotFoundError, OSError, ValueError, TypeError, AttributeError):
            cache = {}
        cache[day] = dict(row)
        fd, tmp = tempfile.mkstemp(prefix="session-calendar-", suffix=".tmp", dir=path.parent)
        try:
            with os.fdopen(fd, "w") as f:
                json.dump(cache, f, allow_nan=False)
                f.flush()
                os.fsync(f.fileno())
            os.replace(tmp, path)
        finally:
            if os.path.exists(tmp):
                try:
                    os.unlink(tmp)
                except OSError:
                    pass
    except OSError:
        # A verified response remains usable in this process; the next process
        # will simply revalidate it rather than trusting a partial cache file.
        pass


def _fetch(day):
    # Via the relay, which holds the Alpaca credentials. This bot has no Alpaca account, and an
    # unverifiable calendar blocks the whole morning pipeline, so this must not need one.
    query = urllib.parse.urlencode({"start": day, "end": day})
    url = config.RELAY_META + "/calendar?" + query
    request = urllib.request.Request(url, headers=dict(config.RELAY_HEADERS))
    with shim.urlopen(request, timeout=REQUEST_TIMEOUT_S) as response:
        payload = json.loads(response.read())
    if not isinstance(payload, list):
        raise ValueError("calendar response is not a list")
    if any(not isinstance(row, dict) or row.get("date") != day for row in payload):
        raise ValueError("calendar response contains an unexpected date")
    return bool(payload)


def is_session(day):
    """Return whether *day* is open, or ``None`` when it cannot be verified."""
    try:
        day = _day_text(day)
    except (TypeError, ValueError):
        return None
    cached = _read_cache(day)
    if cached is not None:
        return cached["is_open"]
    with _fetch_lock:
        cached = _read_cache(day)
        if cached is not None:
            return cached["is_open"]
        now_mono = time.monotonic()
        previous = _last_attempt.get(day)
        if previous is not None and now_mono - previous < RETRY_AFTER_S:
            return None
        _last_attempt[day] = now_mono
        try:
            is_open = _fetch(day)
        except Exception:
            _record("error", "Trading calendar could not be verified for the requested session.",
                    "Check the trading API connection and retry after the calendar retry interval.")
            return None
        row = {"day": day, "is_open": is_open, "checked_at": _now().isoformat()}
        _write_cache(row)
        _record("ok", "Trading calendar was verified for the requested session." if is_open else
                "The requested date is a confirmed closed market session.")
        return is_open


def status(day):
    """Return the locally cached result for *day* without making a network call."""
    try:
        day = _day_text(day)
    except (TypeError, ValueError):
        return None
    return _read_cache(day)


def _prior_close_path():
    suffix = "_demo" if config.CARD_SOURCE == "demo" else ""
    return Path(config.STATE) / ("prior_session_close" + suffix + ".json")


def remember_prior_close(day, sessions):
    """Keep the scanner's verified calendar bound for this day, including early closes.

    The scanner already fetched the preceding 35 days. This adds no network call.
    Failure only leaves the deal rule using its explicit fallback window.
    """
    tmp = None
    try:
        day = _day_text(day)
        current = date.fromisoformat(day)
        dates = [date.fromisoformat(row["date"]) for row in sessions]
        if (not dates or len(dates) != len(set(dates)) or
                any(not current - timedelta(days=35) <= d < current for d in dates)):
            return False
        last = max(sessions, key=lambda row: row["date"])
        close = datetime.fromisoformat(last["date"] + "T" + last["close"]).replace(tzinfo=ET)
        if close.time().isoformat() not in ("13:00:00", "16:00:00"):
            return False
        row = {"day": day, "close": close.isoformat(), "checked_at": _now().isoformat()}
        path = _prior_close_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp = tempfile.mkstemp(prefix="prior-close-", suffix=".tmp", dir=path.parent)
        with os.fdopen(fd, "w") as out:
            json.dump(row, out, allow_nan=False)
            out.flush()
            os.fsync(out.fileno())
        os.replace(tmp, path)
        return True
    except (OSError, ValueError, TypeError, KeyError, AttributeError):
        return False
    finally:
        if tmp and os.path.exists(tmp):
            try:
                os.unlink(tmp)
            except OSError:
                pass


def prior_session_close(day):
    """Local-only calendar evidence for the requested scan day; survives restarts."""
    try:
        day = _day_text(day)
        row = json.loads(_prior_close_path().read_text())
        close = datetime.fromisoformat(row["close"])
        if row.get("day") != day or close.tzinfo is None or close.utcoffset() is None:
            return None
        close = close.astimezone(ET)
        current = date.fromisoformat(day)
        if (not current - timedelta(days=35) <= close.date() < current or
                close.time().isoformat() not in ("13:00:00", "16:00:00")):
            return None
        return close
    except (OSError, ValueError, TypeError, KeyError, AttributeError):
        return None
