# Copied from ORBStraddle signals.py @05d370d; logic unchanged; edits:
#   1. package-relative import of config
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
# @steered SNARE-1 2026-09-12
"""ORBStraddle Empirical Quantitative Signals Module.

Implements institutional quantitative filters from SIGNALS.md, PLAN.md, and empirical_spec.md:
- RVOL (Relative Volume >= 1.20 Index ETF, >= 1.40 Stocks)
- WBR (Wick-to-Body Ratio <= 3.50, Indecision Wick Trap Lockout)
- Pre-Market Gap Conditioning (0.10%-1.80% ETFs, 0.20%-4.50% Stocks)
- SOFI (Signed Order Flow Imbalance |z| >= 2.0, Cont-Kukanov-Stoikov 2014)
- Quote Freshness (<= 5,000 ms) and Displayed Depth (>= $25k both sides)
"""

from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import math
import os
import sys
import threading
import time as _t
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union
from zoneinfo import ZoneInfo

ET = ZoneInfo("America/New_York")

try:
    from . import config
except ImportError:
    config = None

# ---------------------------------------------------------------------------
# Quantitative Threshold Constants
# ---------------------------------------------------------------------------
RVOL_ETF_MIN: float = 1.20
RVOL_STOCK_MIN: float = 1.40

WBR_MAX: float = 3.50
WBR_MIN: float = 0.0

GAP_ETF_MIN: float = 0.10
GAP_ETF_MAX: float = 1.80
GAP_STOCK_MIN: float = 0.20
GAP_STOCK_MAX: float = 4.50

FAILED_GAP_MIN: float = 0.80
EARN_REPRICE_GAP_MIN: float = 3.00

SOFI_WINDOW_SIZE: int = 100
SOFI_MIN_QUOTES: int = 10
SOFI_Z_THRESHOLD: float = 2.0

QUOTE_MAX_AGE_MS: float = 5000.0
QUOTE_MIN_AGE_MS: float = 0.0

DISPLAYED_DEPTH_MIN: float = 25000.0

PRICE_MIN_AGE_S: float = -5.0
PRICE_MAX_AGE_S: float = 60.0

INDEX_ETFS = frozenset({"SPY", "QQQ"})


# ---------------------------------------------------------------------------
# Data Models & Result Containers
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class CandleGeometry:
    high: float
    low: float
    open: float
    close: float
    spot_930: float
    delta: float
    body: float
    midpoint: float
    wbr: float
    is_wick_trap: bool

    @property
    def is_indecision_trap(self) -> bool:
        return self.is_wick_trap


@dataclass(frozen=True)
class GapResult:
    open_930: float
    close_prev: float
    gap_pct: float
    abs_gap_pct: float
    lower_bound: float
    upper_bound: float
    is_dormant: bool
    is_exhaustion: bool
    passes: bool
    reason: str


@dataclass(frozen=True)
class RVOLResult:
    v_orb: float
    v_baseline: float
    rvol: float
    threshold: float
    passes: bool
    is_etf: bool


@dataclass(frozen=True)
class SOFIResult:
    count: int
    z_score: Optional[float]
    passes_long: bool
    passes_short: bool


@dataclass(frozen=True)
class QuoteFilterResult:
    quote_age_ms: Optional[float]
    freshness_pass: bool
    bid_notional: float
    ask_notional: float
    depth_pass: bool
    all_pass: bool


# ---------------------------------------------------------------------------
# Core Mathematical Signal Functions
# ---------------------------------------------------------------------------
def calc_wbr(*args, **kwargs) -> float:
    """Calculate Wick-to-Body Ratio (WBR): Delta_ORB / max(|C - O|, 0.0005 * S_09:30).

    Supports flexible calling conventions:
    - calc_wbr(high, low, open_px, close_px, spot_930)
    - calc_wbr(high, low, open_px, close_px)
    - calc_wbr(open_p, high_p, low_p, close_p)
    - Keyword arguments: high/high_p, low/low_p, open/open_p/open_px, close/close_p/close_px, spot_930.
    """
    h, l, o, c_px, s = None, None, None, None, None

    # Check keyword arguments first
    if "high" in kwargs: h = kwargs["high"]
    elif "high_p" in kwargs: h = kwargs["high_p"]

    if "low" in kwargs: l = kwargs["low"]
    elif "low_p" in kwargs: l = kwargs["low_p"]

    if "open_px" in kwargs: o = kwargs["open_px"]
    elif "open_p" in kwargs: o = kwargs["open_p"]
    elif "open" in kwargs: o = kwargs["open"]

    if "close_px" in kwargs: c_px = kwargs["close_px"]
    elif "close_p" in kwargs: c_px = kwargs["close_p"]
    elif "close" in kwargs: c_px = kwargs["close"]

    if "spot_930" in kwargs: s = kwargs["spot_930"]
    elif "spot" in kwargs: s = kwargs["spot"]

    # Positional args if not resolved
    if len(args) == 5:
        h, l, o, c_px, s = args
    elif len(args) == 4:
        a, b, c, d = args
        # Distinguish between (high, low, open, close) and (open, high, low, close)
        if a > b:
            # First is higher than second: (high, low, open, close)
            h, l, o, c_px = a, b, c, d
        else:
            # First is <= second: (open, high, low, close)
            o, h, l, c_px = a, b, c, d
    elif len(args) == 1 and isinstance(args[0], dict):
        d = args[0]
        h = d.get("high") or d.get("h") or d.get("high_p")
        l = d.get("low") or d.get("l") or d.get("low_p")
        o = d.get("open") or d.get("o") or d.get("open_p") or d.get("open_px")
        c_px = d.get("close") or d.get("c") or d.get("close_p") or d.get("close_px")
        s = d.get("spot_930") or d.get("spot")

    if h is None or l is None or o is None or c_px is None:
        raise ValueError(f"calc_wbr missing required candle parameters (got args={args}, kwargs={kwargs})")

    delta_orb = float(h) - float(l)
    if delta_orb <= 0.0:
        return 0.0

    body = abs(float(c_px) - float(o))
    spot_val = float(s if s is not None else o)
    floor = 0.0005 * max(spot_val, 0.01)
    denom = max(body, floor, 1e-6)
    return delta_orb / denom


def analyze_candle_geometry(
    high: float,
    low: float,
    open_px: float,
    close_px: float,
    spot_930: Optional[float] = None,
) -> CandleGeometry:
    """Extract complete 5-min ORB geometry, midpoint, and WBR indecision trap flag."""
    s = spot_930 if spot_930 is not None else open_px
    delta = high - low
    body = abs(close_px - open_px)
    midpoint = (high + low) / 2.0
    wbr = calc_wbr(high=high, low=low, open_px=open_px, close_px=close_px, spot_930=s)
    is_trap = wbr > WBR_MAX
    return CandleGeometry(
        high=high,
        low=low,
        open=open_px,
        close=close_px,
        spot_930=s,
        delta=delta,
        body=body,
        midpoint=midpoint,
        wbr=wbr,
        is_wick_trap=is_trap,
    )


def calc_gap_pct(open_930: float, close_prev: float) -> float:
    """Pre-market gap %: ((O_09:30 - C_prev) / C_prev) * 100.0."""
    if close_prev <= 0.0:
        return 0.0
    return ((open_930 - close_prev) / close_prev) * 100.0


def validate_gap_bounds(gap_pct: float, is_etf: bool = False) -> GapResult:
    """Validate gap percentage against conditioned dormancy and exhaustion bounds."""
    lower = GAP_ETF_MIN if is_etf else GAP_STOCK_MIN
    upper = GAP_ETF_MAX if is_etf else GAP_STOCK_MAX
    abs_gap = abs(gap_pct)
    is_dormant = abs_gap < lower
    is_exhaustion = abs_gap > upper
    passes = lower <= abs_gap <= upper

    reason = "ok"
    if is_dormant:
        reason = f"Dormant gap |{gap_pct:.2f}%| < {lower:.2f}%"
    elif is_exhaustion:
        reason = f"Exhaustion gap |{gap_pct:.2f}%| > {upper:.2f}%"

    return GapResult(
        open_930=0.0,
        close_prev=0.0,
        gap_pct=gap_pct,
        abs_gap_pct=abs_gap,
        lower_bound=lower,
        upper_bound=upper,
        is_dormant=is_dormant,
        is_exhaustion=is_exhaustion,
        passes=passes,
        reason=reason,
    )


def check_gap(prev_close: float, open_p: float, is_etf: bool = False) -> Tuple[bool, float, str]:
    """Check gap bounds returning (passes, gap_pct, reason)."""
    gap = calc_gap_pct(open_p, prev_close)
    res = validate_gap_bounds(gap, is_etf=is_etf)
    return res.passes, gap, res.reason


def calc_rvol(v_orb: float, adv_20: float) -> float:
    """Relative Volume (RVOL) from pure volume: V_ORB / adv_20."""
    if adv_20 <= 0.0:
        return 0.0
    return v_orb / adv_20


def calc_rvol_dollar_volume(dv5: float, adv_20d: float) -> float:
    """Relative Volume from 5-min opening dollar volume against 20-day ADV.
    RVOL = DV5 / (ADV_20d * (5 / 390)).
    """
    if adv_20d <= 0.0:
        return 0.0
    expected_5m = adv_20d * (5.0 / 390.0)
    if expected_5m <= 0.0:
        return 0.0
    return dv5 / expected_5m


def validate_rvol(rvol: float, is_etf: bool = False) -> RVOLResult:
    """Validate RVOL against asset-class thresholds (>=1.20 ETF, >=1.40 Stock)."""
    threshold = RVOL_ETF_MIN if is_etf else RVOL_STOCK_MIN
    passes = rvol >= threshold
    return RVOLResult(
        v_orb=0.0,
        v_baseline=0.0,
        rvol=rvol,
        threshold=threshold,
        passes=passes,
        is_etf=is_etf,
    )


def calc_order_flow_delta(prev_quote: dict, curr_quote: dict) -> float:
    """Cont-Kukanov-Stoikov (2014) Level 1 order flow delta: db - da."""
    bp_prev = float(prev_quote.get("bp") or 0.0)
    bs_prev = float(prev_quote.get("bs") or 0.0)
    ap_prev = float(prev_quote.get("ap") or 0.0)
    as_prev = float(prev_quote.get("as") or 0.0)

    bp_curr = float(curr_quote.get("bp") or 0.0)
    bs_curr = float(curr_quote.get("bs") or 0.0)
    ap_curr = float(curr_quote.get("ap") or 0.0)
    as_curr = float(curr_quote.get("as") or 0.0)

    if bp_curr > bp_prev:
        db = bs_curr
    elif bp_curr == bp_prev:
        db = bs_curr - bs_prev
    else:
        db = -bs_prev

    if ap_curr < ap_prev:
        da = as_curr
    elif ap_curr == ap_prev:
        da = as_curr - as_prev
    else:
        da = -as_prev

    return db - da


class SOFIRollingTracker:
    """Thread-safe rolling window tracker for SOFI quote flow z-score (WIN=100)."""

    def __init__(self, window_size: int = SOFI_WINDOW_SIZE):
        self.window = deque(maxlen=window_size)
        self.sum = 0.0
        self.sum_sq = 0.0
        self.last = 0.0

    def push(self, val: float) -> None:
        if len(self.window) == self.window.maxlen:
            old = self.window.popleft()
            self.sum -= old
            self.sum_sq -= old * old
        self.window.append(val)
        self.sum += val
        self.sum_sq += val * val
        self.last = val

    def snapshot(self) -> Tuple[int, Optional[float]]:
        count = len(self.window)
        if count < SOFI_MIN_QUOTES:
            return count, None
        mean = self.sum / count
        variance = self.sum_sq / count - mean * mean
        if variance <= 0.0:
            return count, None
        return count, (self.last - mean) / math.sqrt(variance)


def calc_sofi_z(quotes_window: Sequence[Any]) -> Optional[float]:
    """Calculate SOFI z-score over a window of quotes or delta values."""
    if not quotes_window or len(quotes_window) < SOFI_MIN_QUOTES:
        return None

    # Check if quotes_window is list of quote dicts
    if isinstance(quotes_window[0], dict):
        deltas = []
        for k in range(1, len(quotes_window)):
            prev = quotes_window[k - 1]
            curr = quotes_window[k]
            delta = calc_order_flow_delta(prev, curr)
            bs = float(curr.get("bs") or 0.0)
            asz = float(curr.get("as") or 0.0)
            avg = (bs + asz) / 2.0
            if avg > 0:
                deltas.append(delta / avg)
        if len(deltas) < SOFI_MIN_QUOTES:
            return None
        tracker = SOFIRollingTracker(window_size=len(deltas))
        for d in deltas:
            tracker.push(d)
        _, z = tracker.snapshot()
        return z
    else:
        # Numeric values
        tracker = SOFIRollingTracker(window_size=len(quotes_window))
        for d in quotes_window:
            tracker.push(float(d))
        _, z = tracker.snapshot()
        return z


def validate_sofi(
    direction: str,
    z: Optional[float],
    threshold: float = SOFI_Z_THRESHOLD,
) -> bool:
    """Directional SOFI gate: z >= +2.0 for Long, z <= -2.0 for Short."""
    if z is None:
        return False
    d = direction.lower()
    if d == "long":
        return z >= threshold
    elif d == "short":
        return z <= -threshold
    return False


def calc_quote_age_ms(
    trade_key: Union[Tuple[datetime, int], datetime, float],
    quote_key: Union[Tuple[datetime, int], datetime, float],
) -> float:
    """Elapsed milliseconds between quote event and trade event (trade - quote)."""
    if isinstance(trade_key, tuple) and isinstance(quote_key, tuple):
        return (
            (trade_key[0] - quote_key[0]).total_seconds() * 1000.0
            + (trade_key[1] - quote_key[1]) / 1e6
        )
    elif isinstance(trade_key, datetime) and isinstance(quote_key, datetime):
        return (trade_key - quote_key).total_seconds() * 1000.0
    else:
        return (float(trade_key) - float(quote_key)) * 1000.0


def validate_quote_freshness(
    quote_age_ms: Optional[float],
    max_age_ms: float = QUOTE_MAX_AGE_MS,
    min_age_ms: float = QUOTE_MIN_AGE_MS,
) -> bool:
    """Validate quote age is within [0.0 ms, 5000.0 ms]."""
    return quote_age_ms is not None and min_age_ms <= quote_age_ms <= max_age_ms


def check_quote_freshness(quote_time_utc: Any, now_utc: Any = None) -> bool:
    """Check quote freshness <= 5,000 ms. Accepts datetime objects or timestamp floats."""
    if now_utc is None:
        now_utc = datetime.now(timezone.utc)
    if isinstance(now_utc, datetime) and now_utc.tzinfo is None:
        now_utc = now_utc.replace(tzinfo=timezone.utc)

    if isinstance(quote_time_utc, datetime):
        if quote_time_utc.tzinfo is None:
            # Normalize naive datetimes: support both naive UTC and naive local datetimes
            q_as_utc = quote_time_utc.replace(tzinfo=timezone.utc)
            if isinstance(now_utc, datetime):
                age1 = (now_utc - q_as_utc).total_seconds() * 1000.0
                if validate_quote_freshness(age1):
                    quote_time_utc = q_as_utc
                else:
                    quote_time_utc = quote_time_utc.astimezone(timezone.utc)
            else:
                quote_time_utc = q_as_utc

        if isinstance(now_utc, datetime):
            age_ms = (now_utc - quote_time_utc).total_seconds() * 1000.0
        else:
            return False
    elif isinstance(quote_time_utc, (int, float)) and isinstance(now_utc, (int, float)):
        age_ms = (float(now_utc) - float(quote_time_utc)) * 1000.0
    else:
        try:
            age_ms = float(quote_time_utc)
        except (TypeError, ValueError):
            return False
    return validate_quote_freshness(age_ms)


def validate_displayed_depth(
    bp: float,
    bs: float,
    ap: float,
    as_size: float,
    min_depth: float = DISPLAYED_DEPTH_MIN,
) -> Tuple[bool, float, float]:
    """Validate top-of-book depth is >= $25,000 on BOTH bid and ask sides."""
    bid_notional = float(bp) * float(bs)
    ask_notional = float(ap) * float(as_size)
    passes = bid_notional >= min_depth and ask_notional >= min_depth
    return passes, bid_notional, ask_notional


def check_displayed_depth(
    bid_size: float,
    bid_price: float,
    ask_size: float,
    ask_price: float,
    min_depth: float = DISPLAYED_DEPTH_MIN,
) -> bool:
    """Check displayed depth >= $25,000 on both sides."""
    passes, _, _ = validate_displayed_depth(bid_price, bid_size, ask_price, ask_size, min_depth)
    return passes


def validate_execution_price_age(
    trade_dt: datetime,
    now_dt: datetime,
    min_s: float = PRICE_MIN_AGE_S,
    max_s: float = PRICE_MAX_AGE_S,
) -> bool:
    """Execution price staleness guard: print age must be in [-5.0s, 60.0s]."""
    age_s = (now_dt - trade_dt).total_seconds()
    return min_s <= age_s <= max_s


# ---------------------------------------------------------------------------
# Global / Session Lockout Engine
# ---------------------------------------------------------------------------
def get_lockout_filepath() -> str:
    """Resolve state/session_lockout.json path dynamically."""
    if "ORBS_STATE_DIR" in os.environ:
        return os.path.join(os.environ["ORBS_STATE_DIR"], "session_lockout.json")
    if "core" in sys.modules and hasattr(sys.modules["core"], "STATE"):
        return os.path.join(sys.modules["core"].STATE, "session_lockout.json")
    if config is not None:
        state_dir = getattr(config, "STATE", os.path.join(getattr(config, "ROOT", os.getcwd()), "state"))
        return os.path.join(state_dir, "session_lockout.json")
    return os.path.join(os.getcwd(), "state", "session_lockout.json")


def _session_date() -> str:
    """Today's ET trading date. The lockout is scoped to one session, so it needs the same day
    boundary the rest of the bot uses, not the container's local midnight."""
    return datetime.now(ET).date().isoformat()


class SessionLockoutManager:
    """Thread-safe latch for intraday Indecision Wick Trap session lockout.
    Persists lockout status to state/session_lockout.json using atomic writes.

    The latch is INTRADAY: it survives a restart within the same ET session, and expires with that
    session. It used to persist with no date at all, and nothing in the bot ever calls reset(), so on
    Railway - where state/ is a volume that outlives every deploy - the first symbol to print
    WBR > 3.5 stopped the scanner permanently. A session guard must not be able to become a
    permanent one.
    """

    def __init__(self, filepath: Optional[str] = None):
        self._filepath: Optional[str] = filepath
        self._lock = threading.RLock()
        self._locked: bool = False
        self._lock_reason: Optional[str] = None
        self._lock_symbol: Optional[str] = None
        self._lock_wbr: Optional[float] = None
        self._lock_time: Optional[datetime] = None
        self._lock_session: Optional[str] = None
        self.load()

    @property
    def filepath(self) -> str:
        return self._filepath or get_lockout_filepath()

    @filepath.setter
    def filepath(self, path: Optional[str]) -> None:
        self._filepath = path

    def _save(self) -> None:
        path = self.filepath
        data = self.get_info()
        dir_name = os.path.dirname(os.path.abspath(path))
        os.makedirs(dir_name, exist_ok=True)
        pid = os.getpid()
        tid = threading.get_ident()
        tmp_file = f"{path}.{pid}.{tid}.{_t.time_ns()}.tmp"
        payload = json.dumps(data, indent=2)
        fd = os.open(tmp_file, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(payload)
                f.flush()
                os.fsync(f.fileno())
            os.replace(tmp_file, path)
            try:
                dir_fd = os.open(dir_name, os.O_RDONLY)
                try:
                    os.fsync(dir_fd)
                finally:
                    os.close(dir_fd)
            except (OSError, AttributeError):
                pass
        except Exception:
            if os.path.exists(tmp_file):
                try:
                    os.unlink(tmp_file)
                except OSError:
                    pass
            raise

    def load(self, filepath: Optional[str] = None) -> bool:
        path = filepath or self.filepath
        if not os.path.exists(path):
            return False
        with self._lock:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                # A lockout from an EARLIER session is spent, not inherited. A record with no
                # session at all predates this field and cannot be shown to be today's, so it is
                # treated the same way: expired, and not re-persisted as locked.
                stored_session = data.get("session_date")
                if bool(data.get("locked", False)) and stored_session != _session_date():
                    self._locked = False
                    self._lock_symbol = None
                    self._lock_wbr = None
                    self._lock_reason = None
                    self._lock_time = None
                    self._lock_session = None
                    return False
                self._locked = bool(data.get("locked", False))
                self._lock_symbol = data.get("symbol")
                self._lock_wbr = data.get("wbr")
                self._lock_reason = data.get("reason")
                self._lock_session = stored_session
                locked_at_str = data.get("locked_at")
                if locked_at_str:
                    try:
                        self._lock_time = datetime.fromisoformat(locked_at_str)
                    except Exception:
                        self._lock_time = None
                else:
                    self._lock_time = None
                return self._locked
            except Exception:
                return False

    def trigger_lockout(self, symbol: str, wbr: float, reason: str) -> None:
        with self._lock:
            self._locked = True
            self._lock_symbol = symbol
            self._lock_wbr = wbr
            self._lock_reason = reason
            self._lock_time = datetime.now(ET)
            self._lock_session = _session_date()
            try:
                self._save()
            except Exception:
                pass

    def is_locked(self) -> bool:
        with self._lock:
            if self._locked and self._lock_session != _session_date():
                # The process stayed up across the session boundary. Expire in place so a stale
                # latch cannot silently gate the next morning's scan. Deliberately does NOT write:
                # this is called per symbol from inside the 24-thread final scan, and load() already
                # refuses a record whose session_date is not today, so the stale file is harmless.
                self._locked = False
                self._lock_symbol = None
                self._lock_wbr = None
                self._lock_reason = None
                self._lock_time = None
                self._lock_session = None
            return self._locked

    def get_info(self) -> Dict[str, Union[bool, Optional[str], Optional[float]]]:
        with self._lock:
            return {
                "locked": self._locked,
                "symbol": self._lock_symbol,
                "wbr": self._lock_wbr,
                "reason": self._lock_reason,
                "locked_at": self._lock_time.isoformat() if self._lock_time else None,
                "session_date": self._lock_session,
            }

    def reset(self) -> None:
        with self._lock:
            self._locked = False
            self._lock_reason = None
            self._lock_symbol = None
            self._lock_wbr = None
            self._lock_time = None
            self._lock_session = None
            try:
                self._save()
            except Exception:
                pass


SESSION_LOCKOUT = SessionLockoutManager()


# ---------------------------------------------------------------------------
# Candle rule (config.CANDLE_RULE). The opening candle is the first vs the last price-eligible print of
# 09:30-09:35, the same o_orb / c_orb the wick-trap geometry uses.
# ---------------------------------------------------------------------------
def candle_colour(o_orb, c_orb):
    """'green' / 'red' / 'flat' for the opening candle."""
    if o_orb is None or c_orb is None:
        return "flat"
    return "green" if c_orb > o_orb else "red" if c_orb < o_orb else "flat"


def candle_direction(o_orb, c_orb):
    """The only trade direction the opening candle allows: 'long', 'short' or None (flat)."""
    return {"green": "long", "red": "short"}.get(candle_colour(o_orb, c_orb))


def candle_refusal(card, pick=None):
    """Why a pick must NOT be traded under the candle rule, or None when it may. Fail-closed: a card
    without a candle, a blocked card, a colour/direction mismatch or a pick that disagrees with its
    card all refuse."""
    card = card or {}
    colour = card.get("candle")
    direction = card.get("direction")
    if colour not in ("green", "red", "flat"):
        return "opening candle unknown (candle rule is on)"
    o, c = card.get("candle_open"), card.get("candle_close")
    try:
        o, c = float(o), float(c)
    except (TypeError, ValueError):
        return "opening candle prices missing (candle rule is on)"
    if not (math.isfinite(o) and math.isfinite(c) and o > 0 and c > 0):
        return "opening candle prices invalid (candle rule is on)"
    if candle_colour(o, c) != colour:
        return "opening candle label disagrees with its prices"
    if card.get("candle_blocked"):
        return f"opening candle is {colour}: no break in the allowed direction"
    allowed = {"green": "long", "red": "short"}.get(colour)
    if allowed is None or direction != allowed:
        return f"opening candle is {colour}, {direction} not allowed"
    if pick is not None and pick.get("direction") != direction:
        return "pick direction differs from its card"
    return None
