# Copied from ORBStraddle ticks.py @05d370d; logic unchanged; edits: none
# Generated by scripts/orbs_parity/sync_copy.py from ORBStraddle + orbs/SYNC_EDITS.json. Do not
# hand-edit: change SYNC_EDITS.json and regenerate; tests/unit/orbs/test_sync.py checks it.
# --- end of ADT copy header ---
"""ORBStraddle tick store: keeps the 09:30-09:38 opening window in memory as it happens, so the board
is computable the instant the window closes instead of 21.6s later.

Feeds from AlpacaRelay's websocket fan-out (the same relay the REST scan uses), which passes Alpaca's
own wire format through unchanged. That is what makes this safe: the rows handed to scanner.scan_symbol
carry the SAME field names as the REST rows, so the card math below never learns which source it got.

Fail-closed by design. Any gap in the socket, any missing subscribe ack, any symbol shortfall voids the
whole day's stream board and the caller falls back to REST. A partially streamed board is never served:
a thin board looks exactly like a quiet morning, which is the failure P1-9 already fixed once.
"""
import json, math, os, re, ssl, threading, asyncio
from datetime import datetime, time as _time, timedelta
from zoneinfo import ZoneInfo

ET = ZoneInfo("America/New_York")
# Trades and quotes are all scan_symbol reads. Keeping only these keys is not a micro-optimisation:
# the raw relay dicts are ~3x larger and 250 symbols x 8 minutes of quotes is the memory risk here.
# "i" (the trade id) is deliberately NOT kept: scan_symbol never reads it, the relay has no
# replay buffer so there is nothing to dedupe against, and at ~2M trades it is pure weight.
TRADE_KEYS = ("t", "p", "s", "c")
QUOTE_KEYS = ("t", "bp", "ap", "bs", "as")
PRICE_EXCLUDED = {"W", "4", "B", "C", "T", "I", "V", "7", "P", "U", "Z", "H", "M", "N"}
# The watchlist is the top 250 by dollar volume - names that quote hundreds of times a second at the
# open. glm-5.3 put the realistic row count at single-digit millions, i.e. GBs, and an OOM here kills
# a LIVE-armed daemon at 09:37. So the store is bounded, and hitting the bound REFUSES the day rather
# than silently serving a truncated board.
# MEASURED on 2026-08-27 replayed through the real watchlist: 3,660,903 rows (2.01M trades, 1.65M
# quotes), ~257MB pickled. So a 4M cap would void a merely busy morning; 8M is the bound that stops
# an OOM without turning a normal day into a refusal.
# MEASURED: ~514 bytes resident per stored row, and a real 250-symbol morning (2026-08-27 replayed)
# holds 3,660,903 rows -> ~1.9GB. The cap is the OOM guard, so it is set just above a busy day, not
# at some round number: 6M is ~2.6GB against 26GB of machine RAM, and a day that exceeds it is
# refused rather than truncated.
MAX_ROWS = int(os.environ.get("ORBS_TICK_MAX_ROWS", "6000000"))
MIN_TRADES = int(os.environ.get("ORBS_TICK_MIN_TRADES", "5"))
MIN_QUOTES = int(os.environ.get("ORBS_TICK_MIN_QUOTES", "20"))


def _stored_parts(item):
    """Read legacy rows and nanosecond-aware rows."""
    if len(item) == 3:
        return item
    ts, row = item
    return ts, 0, row


class TickStore:
    """Thread-safe accumulator. One background thread owns an asyncio loop and the socket; the scanner
    reads snapshots from its own thread under a lock.

    price_only=True is for consumers that only ever price off last_price (the virtual
    broker): rows are counted nowhere and never retained - only the bounded per-symbol
    latest-price map is kept - so the archival MAX_ROWS cap can never freeze their prices,
    and history retention is O(symbols), not O(rows). The scanner's store keeps the
    default full retention because it must answer slice()/health() for the whole window."""

    def __init__(self, url, token, symbols, ssl_ctx=None, *, subscribe_quotes=True, price_only=False):
        self.url = url
        self.token = token
        self.symbols = list(dict.fromkeys(symbols))
        self._wanted = set(self.symbols)
        self.subscribe_quotes = subscribe_quotes
        self.price_only = price_only
        self._ssl = ssl_ctx
        self._lock = threading.Lock()
        self.trades = {}
        self._latest_prices = {}
        self.quotes = {}
        # health: every one of these is a reason to refuse the stream board
        self.connected_since = None      # datetime ET of the CURRENT unbroken connection
        self.gaps = []                   # [(down_at, up_at)] - any entry voids the day
        self.acked = set()               # symbols the relay confirmed for BOTH channels
        self.errors = []
        self.dropped = 0                 # rows/frames we could not parse
        self.rows = 0                    # total stored, against MAX_ROWS
        self.capped = False              # cap hit: the day is void, see health()
        self._thread = None
        self._loop = None
        self._stop = None
        self._down_at = None
        self._ws = None

    # ---------- lifecycle ----------
    def start(self):
        if self._thread: return
        self._thread = threading.Thread(target=self._run, name="tickstore", daemon=True)
        self._thread.start()

    def stop(self, timeout=10):
        """Unsubscribe and close. The relay refcounts subscriptions across bots, so a store that just
        drops its socket leaves the upstream subscribed for everyone else.

        Closes the SOCKET, not just a flag: `async for raw in ws` does not wake on an Event, so on a
        quiet morning the old version timed out, nulled the thread, and reported success while the
        subscription lived on. Returns True only if the thread is really gone."""
        if self._loop and self._stop and not self._stop.is_set():
            try:
                self._loop.call_soon_threadsafe(self._stop.set)
                self._loop.call_soon_threadsafe(self._close_socket)
            except RuntimeError:
                pass                          # loop already closed (auth refused): nothing to wake
        if self._thread:
            self._thread.join(timeout)
            if self._thread.is_alive():
                self._note_error("stop() timed out: the tick thread is still alive")
                return False                  # do NOT pretend: the caller must be able to see this
            self._thread = None
        return True

    def _close_socket(self):
        ws = self._ws
        if ws is not None:
            try: asyncio.ensure_future(ws.close())
            except Exception: pass

    def _run(self):
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)
        self._stop = asyncio.Event()
        try:
            self._loop.run_until_complete(self._main())
        except Exception as e:                       # a dead store must never kill the daemon
            self._note_error("tick loop died: %s" % e)
        finally:
            try: self._loop.close()
            except Exception: pass

    async def _main(self):
        import websockets
        backoff = 1
        while not self._stop.is_set():
            try:
                # ssl must be OMITTED for wss:// (websockets rejects an explicit ssl=None), so only
                # pass it when a context was actually supplied - caught by tests/smoke_stream.py.
                # Legacy websockets clients may spend 5 * close_timeout shutting down;
                # keep that below stop()'s 10s join budget even if the peer doesn't reply.
                kw = {"ping_interval": 20, "close_timeout": 1, "max_size": 8 * 1024 * 1024}
                if self._ssl is not None: kw["ssl"] = self._ssl
                async with websockets.connect(self.url, **kw) as ws:
                    self._ws = ws
                    await ws.recv()                                   # {"T":"success","msg":"connected"}
                    await ws.send(json.dumps({"action": "auth", "token": self.token}))
                    hello = json.loads(await ws.recv())
                    if not any(m.get("T") == "success" and m.get("msg") == "authenticated"
                               for m in _as_list(hello)):
                        self._note_error("relay auth refused: %s" % hello)
                        return                                        # a bad token will never fix itself
                    # NEVER a wildcard on trades/quotes - the relay is shared and that is a firehose.
                    await ws.send(json.dumps(self._subscription("subscribe", self.symbols)))
                    with self._lock:
                        if self._down_at is not None:
                            self.gaps.append((self._down_at, _now()))
                            self._down_at = None
                        self.connected_since = self.connected_since or _now()
                    backoff = 1
                    async for raw in ws:
                        if self._stop.is_set(): break
                        self._ingest(raw)
                        # recv() may return buffered frames without yielding. Give keepalive,
                        # close and subscription tasks a turn even during a busy tape.
                        await asyncio.sleep(0)
                    await self._unsubscribe(ws)
                    # Falling out of `async for` without an exception means the relay closed on us
                    # cleanly. That is still an outage and MUST be recorded, or a Railway redeploy
                    # mid-window reads as a healthy session.
                    if not self._stop.is_set():
                        self._mark_down("relay closed the connection cleanly")
            except Exception as e:
                self._mark_down("relay connection lost: %s" % e)
            finally:
                self._ws = None
                if self._stop.is_set(): break
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 15)
        # a clean stop still ends the unbroken run; nothing may claim coverage past here
        with self._lock:
            if self._down_at is None: self._down_at = _now()

    async def _unsubscribe(self, ws):
        try:
            await ws.send(json.dumps(self._subscription("unsubscribe", self.symbols)))
        except Exception:
            pass

    def _subscription(self, action, symbols):
        frame = {"action": action, "trades": symbols}
        if self.subscribe_quotes:
            frame["quotes"] = symbols
        return frame

    def _mark_down(self, why):
        with self._lock:
            if self._down_at is None: self._down_at = _now()
            self.connected_since = None
            self.errors.append(why[:200])

    def _note_error(self, why):
        with self._lock: self.errors.append(why[:200])

    # ---------- ingest ----------
    def _ingest(self, raw):
        try:
            msgs = _as_list(json.loads(raw))
        except Exception:
            with self._lock: self.dropped += 1
            return
        with self._lock:
            for m in msgs:
                if not isinstance(m, dict):
                    self.dropped += 1
                    continue
                t = m.get("T")
                if t in ("t", "q"):
                    if t == "q" and not self.subscribe_quotes:
                        continue
                    sym = m.get("S")
                    if not isinstance(sym, str) or not sym:
                        self.dropped += 1
                        continue
                    if sym not in self._wanted:
                        continue  # already-queued frames cannot recreate released state
                    conditions = m.get("c") or []
                    if not isinstance(conditions, (list, tuple)) or any(not isinstance(c, str) for c in conditions):
                        self.dropped += 1
                        continue
                    # Parse the timestamp ONCE, here, and carry it alongside the row. Measured on a
                    # real 250-symbol window (3.66M rows): re-parsing on every read cost 14.3s of the
                    # critical path, which is most of what streaming was supposed to save.
                    raw_t = m.get("t")
                    if not raw_t:
                        self.dropped += 1
                        continue
                    required = ("p", "s") if t == "t" else ("bp", "ap", "bs", "as")
                    if any(k not in m or m[k] is None for k in required):
                        self.dropped += 1
                        continue
                    try: ts, remainder_ns = _ts_parts(raw_t)
                    except Exception:
                        self.dropped += 1; continue
                    # The latest-price map updates BEFORE the row-cap check: the cap refuses the
                    # board, it must not freeze the prices a pricing consumer fills off. (Audit
                    # 2026-09-15: cap hit -> last_price stuck at the pre-cap print.)
                    if t == "t" and not (set(m.get("c") or []) & PRICE_EXCLUDED):
                        try:
                            price = float(m.get("p"))
                            prev = self._latest_prices.get(sym)
                            key = (ts, remainder_ns)
                            if math.isfinite(price) and price > 0 and (
                                prev is None or key > prev[:2]
                            ):
                                self._latest_prices[sym] = (
                                    ts, remainder_ns, price
                                )
                        except (TypeError, ValueError): pass
                    if self.price_only:
                        continue                  # pricing consumer: retain nothing but the price
                    if self.rows >= MAX_ROWS:
                        self.capped = True        # stop growing; health() voids the day
                        continue
                    keys = TRADE_KEYS if t == "t" else QUOTE_KEYS
                    book = self.trades if t == "t" else self.quotes
                    book.setdefault(sym, []).append(
                        (ts, remainder_ns, {k: m.get(k) for k in keys})
                    )
                    self.rows += 1
                elif t == "relay":
                    # Relay control frames ride the SAME open socket, so a dead upstream does
                    # not look like a socket drop: the connection stays up and no exception
                    # fires. Without this the outage is invisible and health() reports a
                    # covered window off a silent tape (audit 2026-09-15).
                    msg = str(m.get("msg") or "")
                    low = msg.lower()
                    if "upstream_disconnected" in low:
                        if self._down_at is None: self._down_at = _now()
                        self.connected_since = None
                        self.errors.append(("relay upstream disconnected: %s" % msg[:160])[:200])
                    elif "upstream" in low and "connect" in low and "disconnect" not in low:
                        # Recovered: whatever the window missed while upstream was down is a
                        # gap, and the gate is fail-closed - any gap voids the stream board.
                        if self._down_at is not None:
                            self.gaps.append((self._down_at, _now()))
                            self._down_at = None
                elif t == "subscription":
                    # Scanner cards need both channels; the paper burst lane opts into trades only.
                    tr, qu = set(m.get("trades") or []), set(m.get("quotes") or [])
                    self.acked |= (tr & qu) if self.subscribe_quotes else tr
                elif t == "error":
                    self.errors.append(str(m)[:200])

    # ---------- reads ----------
    def subscribe_more(self, symbols):
        """Add symbols to the live subscription. Used by the virtual broker (virtual.py), which
        learns its symbols as orders arrive, after the socket is already up. Updating self.symbols
        covers reconnects (the handshake re-subscribes the whole list); the frame below covers the
        connection that is open right now."""
        with self._lock:
            add = list(dict.fromkeys(s for s in symbols if s not in self._wanted))
            if not add: return
            self.symbols += add
            self._wanted.update(add)
        if self._loop is not None:
            # _send_subscribe is a COROUTINE. call_soon_threadsafe just calls it, which builds a
            # coroutine object and drops it ("coroutine was never awaited") - the frame never went
            # out, so symbols added after the socket was up were only ever picked up by the next
            # reconnect. run_coroutine_threadsafe actually schedules it. (QA 2026-09-02)
            try: asyncio.run_coroutine_threadsafe(self._send_subscribe(add), self._loop)
            except RuntimeError: pass              # loop closed: the next reconnect subscribes them

    async def _send_subscribe(self, symbols):
        ws = self._ws
        if ws is not None:
            with self._lock:
                symbols = [s for s in symbols if s in self._wanted]
            if not symbols:
                return
            try:
                await ws.send(json.dumps(self._subscription("subscribe", symbols)))
                with self._lock:
                    stale = [s for s in symbols if s not in self._wanted]
                if stale:
                    await ws.send(json.dumps(self._subscription("unsubscribe", stale)))
            except Exception:
                pass                               # a dead socket is handled by the reconnect loop

    def unsubscribe(self, symbols):
        """Release symbols the consumer no longer needs (closed positions). The subscription
        list shrinks so the next reconnect does not resubscribe, retained rows and the
        latest-price entry are dropped, and an unsubscribe frame goes out on the live socket:
        the relay refcounts subscriptions across bots, so a store that just stops reading
        leaves everyone else paying for the tape."""
        with self._lock:
            dropping = set(symbols) & self._wanted
            if not dropping: return
            drop = sorted(dropping)
            self._wanted.difference_update(dropping)
            self.symbols = [s for s in self.symbols if s not in dropping]
            self.acked.difference_update(dropping)
            for sym in drop:
                self.rows -= len(self.trades.pop(sym, ())) + len(self.quotes.pop(sym, ()))
                self._latest_prices.pop(sym, None)
        if self._loop is not None:
            try: asyncio.run_coroutine_threadsafe(self._send_unsubscribe(drop), self._loop)
            except RuntimeError: pass              # loop closed: nothing is subscribed anymore

    async def _send_unsubscribe(self, symbols):
        ws = self._ws
        if ws is not None:
            with self._lock:
                symbols = [s for s in symbols if s not in self._wanted]
            if not symbols:
                return
            try:
                await ws.send(json.dumps(self._subscription("unsubscribe", symbols)))
                with self._lock:
                    restored = [s for s in symbols if s in self._wanted]
                if restored:
                    await self._send_subscribe(restored)
            except Exception:
                pass                               # a dead socket is handled by the reconnect loop

    def last_price(self, sym):
        """(ts, price) of the newest trade print for sym, or None. The virtual broker prices fills
        off this; it must never see a stored dict it could mutate, so only scalars come out."""
        with self._lock:
            value = self._latest_prices.get(sym)
            return (value[0], value[2]) if value else None

    def slice(self, kind, sym, start_dt, end_dt):
        """Rows for one symbol in [start, end), as fresh dicts in TIME order.

        Two non-negotiables, both found by the glm-5.3 pre-implementation attack:
        - COPIES, never the stored dicts. scan_symbol rewrites q["bs"]/q["as"] in place for the
          round-lot fix; handing out references would corrupt the store and make a second read
          (the shadow diff, a retry) see already-multiplied sizes.
        - SORTED by timestamp. The store appends in ARRIVAL order; REST returns time order, and
          scan_symbol reads trades[-1] as "the latest print" to compute drift. An out-of-order
          retransmit at the tail would silently price the card off a stale trade."""
        with self._lock:
            rows = list((self.trades if kind == "trades" else self.quotes).get(sym) or [])
        keep = []
        for item in rows:
            ts, remainder_ns, row = _stored_parts(item)
            if start_dt <= ts < end_dt:
                keep.append((ts, remainder_ns, dict(row)))
        keep.sort(key=lambda item: (item[0], item[1]))
        return [row for _, _, row in keep]

    def _count(self, kind, sym, start_dt, end_dt):
        """Counting must not deep-copy the store. slice() builds a fresh dict per row; calling it
        twice per symbol just to read len() was ~3.7M pointless copies at 09:38:40."""
        with self._lock:
            rows = (self.trades if kind == "trades" else self.quotes).get(sym) or ()
            return sum(
                1
                for item in rows
                if start_dt <= _stored_parts(item)[0] < end_dt
            )

    def counts(self):
        with self._lock:
            return (sum(len(v) for v in self.trades.values()),
                    sum(len(v) for v in self.quotes.values()))

    def health(self, start_dt, end_dt, min_coverage=0.99, min_trades=MIN_TRADES, min_quotes=MIN_QUOTES):
        """The board-level gate. Returns (usable, health dict). Deliberately all-or-nothing: a mixed
        board (some symbols streamed, some REST) would hide a partial outage as a quiet morning.

        Hardened after the glm-5.3 attack, which showed the first draft checked the two things the
        relay can fake and skipped the ones that actually break:
        - the subscribe ack is an ECHO of our own request (relay builds it from client.subs before any
          upstream confirmation), so it can only ever DISPROVE coverage, never prove it. Kept as a
          cheap negative check, never trusted as a positive one.
        - the quote channel was not checked at all, yet SOFI is computed entirely from quotes. A dead
          quote subscription passed every original condition and produced z-scores over an empty
          window. Quotes now carry their own per-symbol floor.
        - "at least one trade in five minutes" is an outage, not coverage. Real floors, and 99% of
          symbols, not 95% (5% of 250 is 12 names, and the 12 that break are rarely the quiet ones).
        - the row cap is a REFUSAL, not a log line. Truncated-but-gated is still truncated."""
        with self._lock:
            gaps = list(self.gaps)
            since = self.connected_since
            acked = set(self.acked)
            errs = list(self.errors)
            down_at = self._down_at
            capped = self.capped
        thin_t = thin_q = stale_t = stale_q = 0
        for sym in self.symbols:
            stats = []
            for book in (self.trades, self.quotes):
                with self._lock:
                    count = 0; newest = None
                    for item in book.get(sym) or ():
                        ts, remainder_ns, _row = _stored_parts(item)
                        key = (ts, remainder_ns)
                        if start_dt <= ts < end_dt:
                            count += 1
                            if newest is None or key > newest:
                                newest = key
                stats.append((
                    count,
                    newest is not None
                    and (end_dt - newest[0]).total_seconds() > 120,
                ))
            if stats[0][0] < min_trades: thin_t += 1
            if stats[1][0] < min_quotes: thin_q += 1
            stale_t += stats[0][1]; stale_q += stats[1][1]
        n = len(self.symbols) or 1
        cov_t = (n - thin_t) / n
        cov_q = (n - thin_q) / n
        # "covered the window" means connected BEFORE it opened and still up when it closed
        covered = bool(since) and since <= start_dt and (down_at is None or down_at >= end_dt)
        missing_ack = [s for s in self.symbols if s not in acked]
        reasons = []
        if not self.symbols: reasons.append("no subscribed symbols")
        if stale_t / n > 1 - min_coverage: reasons.append("%d symbol(s) with stale trades at freeze" % stale_t)
        if self.subscribe_quotes and stale_q / n > 1 - min_coverage: reasons.append("%d symbol(s) with stale quotes at freeze" % stale_q)
        if capped: reasons.append("row cap hit - the store is truncated, not a board")
        if gaps: reasons.append("socket dropped %d time(s) during the session" % len(gaps))
        if not covered: reasons.append("socket did not cover the whole window")
        if missing_ack: reasons.append("relay never acked %d symbol(s)" % len(missing_ack))
        if cov_t < min_coverage: reasons.append("%d symbol(s) under %d trades" % (thin_t, min_trades))
        if self.subscribe_quotes and cov_q < min_coverage: reasons.append("%d symbol(s) under %d quotes" % (thin_q, min_quotes))
        if self.dropped: reasons.append("%d malformed frame(s)/row(s) dropped - feed integrity unproven" % self.dropped)
        trade_rows, quote_rows = self.counts()
        h = {"connected_since": since.isoformat() if since else None, "gaps": len(gaps),
             "acked": len(acked), "symbols": len(self.symbols), "capped": capped,
             "trade_coverage": round(cov_t, 4), "quote_coverage": round(cov_q, 4),
             "errors": errs[:5], "dropped": self.dropped, "reasons": reasons,
             "channels": ["trades", "quotes"] if self.subscribe_quotes else ["trades"],
             "trade_rows": trade_rows, "quote_rows": quote_rows,
             "gap_windows": [[a.isoformat(), b.isoformat()] for a, b in gaps]}
        return (not reasons), h


def _as_list(j):
    return j if isinstance(j, list) else [j]


def _now():
    return datetime.now(ET)


_TIMESTAMP_FRACTION = re.compile(r"\.(\d*)(?=[+-]\d{2}:\d{2}$)")


def _ts_parts(x):
    """Return market time plus nanoseconds below Python's microsecond limit."""
    raw = str(x)
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    fraction = _TIMESTAMP_FRACTION.search(raw)
    remainder_ns = 0
    if fraction:
        digits = fraction.group(1)
        if not digits:
            raise ValueError("market timestamp has an empty fractional second")
        if len(digits) > 9:
            raise ValueError("market timestamp exceeds nanosecond precision")
        nanoseconds = int((digits + "000000000")[:9])
        remainder_ns = nanoseconds % 1000
        raw = (
            raw[: fraction.start() + 1]
            + f"{nanoseconds // 1000:06d}"
            + raw[fraction.end() :]
        )
    stamp = datetime.fromisoformat(raw)
    if stamp.tzinfo is None: raise ValueError("market timestamp lacks timezone")
    return stamp.astimezone(ET), remainder_ns


def _ts(x):
    """Timezone-aware RFC-3339 normalized to Python datetime precision."""
    return _ts_parts(x)[0]


def _ts_key(x):
    """Exact ordering key through nanoseconds."""
    return _ts_parts(x)


class StreamSource:
    """What scan_symbol reads when the gate passed."""
    name = "stream"
    def __init__(self, store): self.store = store
    def rows(self, kind, sym, start_dt, end_dt): return self.store.slice(kind, sym, start_dt, end_dt)


class RestSource:
    """Today's behaviour, unchanged, and the fallback whenever the gate refuses."""
    name = "rest"
    def __init__(self, paged): self._paged = paged
    def rows(self, kind, sym, start_dt, end_dt):
        return self._paged(kind, sym, start_dt.isoformat(), end_dt.isoformat())
